#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="multibyte input"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_COL"
ts_check_test_command "$TS_HELPER_STRERROR"

ts_init_subtest "valid"
cat $TS_SELF/multibyte.data |
    LC_ALL=C ts_run $TS_CMD_COL 2>&1 |
    sed -e "s@$($TS_HELPER_STRERROR EILSEQ)@EILSEQ@" > $TS_OUTPUT
ts_finalize_subtest

ts_init_subtest "invalid"
printf '%s\n' $'abc\200\200jkl' |
	LC_ALL=C ts_run $TS_CMD_COL 2>&1 |
	sed -e "s@$($TS_HELPER_STRERROR EILSEQ)@EILSEQ@" > $TS_OUTPUT
ts_finalize_subtest


ts_finalize
