#!/bin/sh
# This command is deprecated.  The utility is in maintenance mode,
# meaning we keep them in source tree for backward compatibility
# only.  Do not waste time making this command better, unless the
# fix is about security or other very critical issue.
#
# See Documentation/deprecated.txt for more information.
stty sane
tput clear
tput rmacs
tput rmm
tput rmso
tput rmul
tput rs1
tput rs2
tput rs3
bot=$((${LINES:-$(tput lines)} - 1))
if test "${bot}" -le "0"; then bot=24; fi
tput csr 0 ${bot}
