.TH SCRIPTLIVE 1 "October 2019" "util-linux" "User Commands"
.SH "NAME"
scriptlive \- re-run session typescripts, using timing information
.SH "SYNOPSIS"
.B scriptlive
[options]
.RB [ \-t ]
.RI timingfile
.RB [ \-I|\-B ]
.RI typescript
.SH "DESCRIPTION"
This program re-run a typescript, using stdin typescript and timing information to ensure that
input happens in the same rhythm as it originally appeared when the script
was recorded.
.PP
The \fBsession is executed\fR in newly created pseudo terminal with user's $SHELL
(or defaults to /bin/bash).
.PP
.B Be careful!
Do not forget that the typescript may contains arbitrary commands.
It is recommended to use \fB"scriptreplay \-\-stream in \-\-log\-in typescript"\fR
(or with --log-io instead of --log-in) to verify the typescript before it is executed by
.BR scriptlive (1).
.PP
The timing information is what
.BR script (1)
outputs to file specified by
.BR \-\-log\-timing .
The typescript has to contain stdin information and it is what
.BR script (1) 
outputs to file specified by
.BR \-\-log-in
or
.BR \-\-log\-io .

.SH OPTIONS
.TP
.BR \-I , " \-\-log-in " \fIfile\fR
File containing \fBscript\fR's terminal input.
.TP
.BR \-B , " \-\-log-io " \fIfile\fR
File containing \fBscript\fR's terminal output and input.
.TP
.BR \-t , " \-\-timing " \fIfile\fR
File containing \fBscript\fR's timing output.  This option overrides old-style arguments.
.TP
.BR \-T , " \-\-log\-timing " \fIfile\fR
aliast to \fB\-t\fR, maintained for compatibility with
.B script (1)
command line options.
.BR \-d , " \-\-divisor " \fInumber\fR
Speed up the replay displaying this
.I number
of times.  The argument is a floating point number.  It's called divisor
because it divides the timings by this factor.  This option overrides old-style arguments.
.TP
.BR \-m , " \-\-maxdelay " \fInumber\fR
Set the maximum delay between transcript updates to
.I number
of seconds.  The argument is a floating point number.  This can be used to
avoid long pauses in the transcript replay.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH "EXAMPLE"
.nf
% script --log-timing file.tm --log-in script.in
Script started, file is script.out
% date
<etc, etc>
% exit
Script done, file is script.out
% scriptlive --log-timing file.tm --log-in script.in
.nf
.SH "SEE ALSO"
.BR script (1),
.BR scriptreplay (1)
.SH "COPYRIGHT"
Copyright \(co 2019 Karel Zak
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
.PP
Released under the GNU General Public License version 2 or later.
.SH "AUTHOR"
.MT kzak@\:redhat.com
Karel Zak
.ME .
.SH AVAILABILITY
The scriptlive command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
