.TH SCRIPTREPLAY 1 "October 2019" "util-linux" "User Commands"
.SH NAME
scriptreplay \- play back typescripts, using timing information
.SH SYNOPSIS
.B scriptreplay
[options]
.RB [ \-t ]
.I timingfile
.RI [ typescript
.RI [ divisor ]]
.SH DESCRIPTION
This program replays a typescript, using timing information to ensure that
output happens in the same rhythm as it originally appeared when the script
was recorded.
.PP
The replay simply displays the information again; the programs
that were run when the typescript was being recorded are \fBnot run again\fR.
Since the same information is simply being displayed,
.B scriptreplay
is only guaranteed to work properly if run on the same type of
terminal the typescript was recorded on.  Otherwise, any escape characters
in the typescript may be interpreted differently by the terminal to
which
.B scriptreplay
is sending its output.
.PP
The timing information is what
.BR script (1)
outputs to file specified by
.BR \-\-log-timing .
.PP
By default, the typescript to display is assumed to be named
.IR typescript ,
but other filenames may be specified, as the second parameter or with option
.BR \-\-log\-out .
.PP
If the third parameter or
.B \-\-divisor
is specified, it is used as a speed-up multiplier.
For example, a speed-up of 2 makes
.B scriptreplay
go twice as fast, and a speed-up of 0.1 makes it go ten times slower
than the original session.
.SH OPTIONS
.TP
.BR \-I , " \-\-log-in " \fIfile\fR
File containing \fBscript\fR's terminal input.
.TP
.BR \-O , " \-\-log-out " \fIfile\fR
File containing \fBscript\fR's terminal output.
.TP
.BR \-B , " \-\-log-io " \fIfile\fR
File containing \fBscript\fR's terminal output and input.
.TP
.BR \-t , " \-\-timing " \fIfile\fR
File containing \fBscript\fR's timing output.  This option overrides old-style arguments.
.TP
.BR \-T , " \-\-log\-timing " \fIfile\fR
This is an alias for \fB\-t\fR, maintained for compatibility with
.BR script (1)
command-line options.
.TP
.BR \-s , " \-\-typescript " \fIfile\fR
File containing \fBscript\fR's terminal output.  Deprecated alias to \fB\-\-log-out\fR.
This option overrides old-style arguments.
.TP
.BR \-c , " \-\-cr\-mode " \fImode\fR
Specifies how to use the CR (0x0D, carriage return) character from log files.
The default mode is
.IR auto ,
in this case CR is replaced with line break for stdin log, because otherwise
.B scriptreplay
would overwrite the same line.  The other modes are
.I never
and
.IR always .
.TP
.BR \-d , " \-\-divisor " \fInumber\fR
Speed up the replay displaying this
.I number
of times.  The argument is a floating-point number.  It's called divisor
because it divides the timings by this factor.  This option overrides old-style arguments.
.TP
.BR \-m , " \-\-maxdelay " \fInumber\fR
Set the maximum delay between updates to
.I number
of seconds.  The argument is a floating-point number.  This can be used to
avoid long pauses in the typescript replay.
.TP
.B \-\-summary
Display details about the session recorded in the specified timing file
and exit.  The session has to be recorded using
.I advanced
format (see
.BR script (1))
option \fB\-\-logging\-format\fR for more details).
.TP
.BR \-x , " \-\-stream " \fItype\fR
Forces
.B scriptreplay
to print only the specified stream.  The supported stream types
are
.IR in ,
.IR out ,
.IR signal ,
or
.IR info .
This option is recommended for multi-stream logs (e.g.,
.BR \-\-log-io )
in order to print only specified data.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH EXAMPLES
.nf
% script --log-timing file.tm --log-out script.out
Script started, file is script.out
% ls
<etc, etc>
% exit
Script done, file is script.out
% scriptreplay --log-timing file.tm --log-out script.out
.fi
.SH AUTHORS
The original
.B scriptreplay
program was written by
.MT joey@\:kitenet.net
Joey Hess
.ME .
The program was re-written in C by
.MT jay@\:gnu.org
James Youngman
.ME
and
.MT kzak@\:redhat.com
Karel Zak
.ME .
.SH COPYRIGHT
Copyright \(co 2008 James Youngman
.br
Copyright \(co 2008-2019 Karel Zak
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
.PP
Released under the GNU General Public License version 2 or later.
.SH SEE ALSO
.BR script (1),
.BR scriptlive (1)
.SH AVAILABILITY
The scriptreplay command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
