#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="setpgid"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_SETPGID"

$TS_CMD_SETPGID echo "success" >> $TS_OUTPUT 2>> $TS_ERRLOG

# qemu-user always reports '0' for the pgid field which prevents the test from
# working so we skip it.
ts_skip_qemu_user

PGID1="$(awk '{print $5}' /proc/self/stat)"
PGID2="$($TS_CMD_SETPGID awk '{print $5}' /proc/self/stat)"
test ! "$PGID1" = "$PGID2" && echo "not equal" >> $TS_OUTPUT

ts_finalize
