#!/bin/bash
#
# Copyright (C) 2022 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="procfs library"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_PROCFS"

test_data="$TS_SELF/procfs-data"
test_cmd() {
	"$TS_HELPER_PROCFS" --prefix "$test_data" "$@" \
		2>> "$TS_ERRLOG" \
	        | sed -e 's/   UID: .*/   UID: [redacted]/' \
		>> "$TS_OUTPUT"
}

ts_init_subtest "one-process"

test_cmd --one 1
test_cmd --one 2
test_cmd --one 3

ts_finalize_subtest


ts_init_subtest "stat-nth"

test_cmd --stat-nth 1 1
test_cmd --stat-nth 1 2
test_cmd --stat-nth 1 3
test_cmd --stat-nth 1 4

test_cmd --stat-nth 2 1
test_cmd --stat-nth 2 4

test_cmd --stat-nth 3 1
test_cmd --stat-nth 3 4

ts_finalize_subtest

ts_finalize
