#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file may be distributed under the terms of the
# GNU Lesser General Public License.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="timeutils library"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_TIMEUTILS"

ts_init_subtest "timestamp"

"$TS_HELPER_TIMEUTILS" --unittest-timestamp 2> "$TS_ERRLOG"

ts_finalize_subtest

ts_finalize
