.\" All Rites Reversed.  This file is in the PUBLIC DOMAIN.
.\" Kallisti.
.TH DDATE 6 "55 Confusion 3160" "" "Linux Programmer's Manual"
.SH NAME
ddate \- converts boring normal dates to fun Discordian Dates
.SH SYNOPSIS
.B ddate
.SH DESCRIPTION
.B ddate
prints the date in Discordian Date format.
.SH AUTHOR
.nf
Druel the Chaotic aka Jeremy Johnson (mpython@gnu.ai.mit.edu)
.br
Modifications for Unix by Lee Harvey Oswald Smith, K.S.C.
.br
Five tons of flax.
