#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="headers"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_IPCS"

ts_log "test: shm headers"
$TS_CMD_IPCS -m -t | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -m -p | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -m -c | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -m -l | grep "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -m -u | grep "^---"  >> $TS_OUTPUT
echo >> $TS_OUTPUT

ts_log "test: mesg headers"
$TS_CMD_IPCS -q -t | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -q -p | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -q -c | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -q -l | grep  "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -q -u | grep  "^---"  >> $TS_OUTPUT
echo >> $TS_OUTPUT

ts_log "test: sem headers"
$TS_CMD_IPCS -s -t | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -s -p | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -s -c | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -s -l | grep  "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -s -u | grep  "^---"  >> $TS_OUTPUT
echo >> $TS_OUTPUT

ts_log "test: all headers"
$TS_CMD_IPCS -a | grep -A1 "^---"  >> $TS_OUTPUT

$TS_CMD_IPCS -a -t | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -a -p | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -a -c | grep -A1 "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -a -l | grep "^---"  >> $TS_OUTPUT
$TS_CMD_IPCS -a -u | grep "^---"  >> $TS_OUTPUT

ts_finalize

