#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util--limitsinux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="headers"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_IPCS"

ts_init_subtest "shm-headers"
$TS_CMD_IPCS --shmems --time | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --shmems --pid | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --shmems --creator | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --shmems --limits | grep "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --shmems --summary | grep "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest

ts_init_subtest "mesg-headers"
$TS_CMD_IPCS --queues --time | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --queues --pid | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --queues --creator | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --queues --limits | grep  "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --queues --summary | grep  "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest

ts_init_subtest "sem-headers"
$TS_CMD_IPCS --semaphores --time | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --semaphores --pid | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --semaphores --creator | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --semaphores --limits | grep  "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --semaphores --summary | grep  "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest

ts_init_subtest "all-headers"
$TS_CMD_IPCS --all | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG

$TS_CMD_IPCS --all --time | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --all --pid | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --all --creator | grep -A1 "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --all --limits | grep "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
$TS_CMD_IPCS --all --summary | grep "^---"  >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest

ts_finalize
