#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="basic limits"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_IPCS"
ts_check_prog "bc"

. $TS_SELF/functions.sh

# TODO https://github.com/karelzak/util-linux/issues/51
SHMALL=$(</proc/sys/kernel/shmall)
if [ $(bc <<<"(2^64 / $PAGE_SIZE) <= $SHMALL") -eq 1 ]; then
	TS_KNOWN_FAIL="yes"
fi

ts_log "check for difference between kernel and IPC"
ipcs_limits_check >> $TS_OUTPUT

ts_finalize

