#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="limits overflow"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_IPCS"
ts_check_test_command "$TS_HELPER_SYSINFO"

ts_skip_nonroot
ts_check_prog "bc"

. "$TS_SELF"/functions.sh

ts_lock "ipcslimits"

ts_log "load original values"
for i in $IPCS_IDX; do
	SHM_ORG[$i]=$(cat ${IPCS_PROCFILES[$i]})
done >> $TS_OUTPUT

ts_log "maximize kernel setting"
for i in $IPCS_IDX; do
	echo ${IPCS_LIMITS[$i]} >> ${IPCS_PROCFILES[$i]}
done >> $TS_OUTPUT

ts_log "check for difference between kernel and IPC"
ipcs_limits_check >> $TS_OUTPUT

ts_log "write original values to kernel"
for i in $IPCS_IDX; do
	echo ${SHM_ORG[$i]} >> ${IPCS_PROCFILES[$i]}
done >> $TS_OUTPUT

ts_finalize

