#!/bin/bash
#
# Copyright (C) 2023 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="SOURCE column"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

. "$TS_SELF/lsfd-functions.bash"
ts_check_test_command "$TS_CMD_LSFD"

ts_cd "$TS_OUTDIR"

declare -a NAMESPACES=(
    cgorup
    ipc
    mnt
    net
    pid
    pid4c
    # older kernel doesn't support time namespace.
    # time
    # time4c
    user
    uts
)
ts_init_subtest namespace-ASSOC
{
    EXPR="false"
    for ns in "${NAMESPACES[@]}"; do
	EXPR=${EXPR}' || (ASSOC == "'"$ns"'")'
    done
    ${TS_CMD_LSFD} -p $$ -n -o ASSOC,SOURCE -Q "$EXPR"
} > "$TS_OUTPUT" 2>&1
ts_finalize_subtest

ts_finalize
