#!/bin/bash
#
# Copyright (C) 2023 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="DELETED column"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

PID=
FD=3
EXPR=

C=make-regular-file
ts_init_subtest $C
{
    target=util-linux-lsfd-test-make-regular-file
    coproc MKFDS { "$TS_HELPER_MKFDS" "$C" "$FD" file="$target"  delete=1; }
    if read -u ${MKFDS[0]} PID; then
	EXPR='(FD == '"$FD"')'
	${TS_CMD_LSFD} -p "$PID" -n -o DELETED -Q "${EXPR}"
	echo "$C: DELETED: " $?
	echo DONE >&"${MKFDS[1]}"
    fi
} >  "$TS_OUTPUT" 2>&1
wait "${MKFDS_PID}"
ts_finalize_subtest

C=ro-regular-file
ts_init_subtest $C
{
    coproc MKFDS { "$TS_HELPER_MKFDS" "$C" "$FD"; }
    if read -u ${MKFDS[0]} PID; then
	EXPR='(FD == '"$FD"')'
	${TS_CMD_LSFD} -p "$PID" -n -o DELETED -Q "${EXPR}"
	echo "$C: DELETED: " $?
	echo DONE >&"${MKFDS[1]}"
    fi
} >  "$TS_OUTPUT" 2>&1
wait "${MKFDS_PID}"
ts_finalize_subtest

ts_finalize
