#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="TYPE and STTYPE column"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

. "$TS_SELF/lsfd-functions.bash"
ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

PID=
FD=3
EXPR="(FD == 3)"

for C in ro-regular-file pidfd inotify socketpair; do
    ts_init_subtest $C
    {
	coproc MKFDS {
	    argv=()
	    case $C in
		socketpair)
		    argv[0]="$((FD + 1))"
		    argv[1]="socktype=DGRAM"
	    esac
	    "$TS_HELPER_MKFDS" $C $FD "${argv[@]}"
	}
	if read -r -u "${MKFDS[0]}" PID; then
	    ${TS_CMD_LSFD} -n -o ASSOC,STTYPE,TYPE -p "${PID}" -Q "${EXPR}"
	    echo "$C"':ASSOC,STTYPE,TYPE': $?

	    echo DONE >&"${MKFDS[1]}"
	fi
	wait "${MKFDS_PID}"
    } > "$TS_OUTPUT" 2>&1

    if [ "$C-$?" == "pidfd-$TS_EXIT_NOTSUPP" ]; then
	ts_skip_subtest "pidfd_open(2) is not available"
	continue
    fi

    case $C in
    pidfd)
	sed -i -E 's/UNKN|REG/[STTYPE]/' "$TS_OUTPUT"
    esac

    ts_finalize_subtest
done

ts_finalize
