#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="ainodeclass column"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

. "$TS_SELF/lsfd-functions.bash"
ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

PID=
FD=3
EXPR="(FD == 3)"

for C in pidfd inotify; do
    ts_init_subtest $C
    {
	coproc MKFDS { "$TS_HELPER_MKFDS" $C $FD ; }
	if read -r -u "${MKFDS[0]}" PID; then
	    ${TS_CMD_LSFD} -n -o ASSOC,STTYPE,AINODECLASS -p "${PID}" -Q "${EXPR}"
	    echo "$C"':ASSOC,STTYPE,AINODECLASS': $?

	    echo DONE >&"${MKFDS[1]}"
	fi
	wait "${MKFDS_PID}"
    } > "$TS_OUTPUT" 2>&1

    if [ "$C-$?" == "pidfd-$TS_EXIT_NOTSUPP" ]; then
	ts_skip_subtest "pidfd_open(2) is not available"
	continue
    fi

    STTYPE="$(head -n1 "$TS_OUTPUT" | awk '{print $2}')"
    if [ "$C-$STTYPE" == "pidfd-REG" ]; then
	ts_skip_subtest "pidfd is from pidfs instead of anon inode"
	continue
    fi

    ts_finalize_subtest
done

ts_finalize
