#!/bin/bash
#
# Copyright (C) 2024 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="fd opening a file cannot be stat(2)'ed"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"
ts_check_test_command "$TS_CMD_SETPRIV"

ts_check_prog "chmod"
ts_check_prog "dd"
ts_check_prog "id"
ts_check_prog "mkdir"
ts_check_prog "rm"
ts_check_prog "rmdir"

ts_cd "$TS_OUTDIR"

pid=$$
DIR=d"$pid"
FILE=${DIR}/f"$pid"

if ! mkdir -p "$DIR"; then
    ts_die "error in mkdir"
fi

if ! dd if=/dev/zero of="$FILE" bs=4096 count=1 status=none; then
    rmdir "$DIR"
    ts_die "error in dd"
fi

LAUNCHER=
if [ "$(id -u)" = 0 ]; then
    chown -R 1 $DIR
    LAUNCHER="$TS_CMD_SETPRIV --reuid=1"
    LSFD_XOPT="--_drop-privilege"
fi

PID=
EXPR=

{
    coproc MKFDS { $LAUNCHER "$TS_HELPER_MKFDS" mmap file="$FILE"; }
    if read -u ${MKFDS[0]} PID; then
	chmod u-rwx "$DIR"

	EXPR='(ASSOC == "mem") and (NAME =~ ".*/'"$FILE"'$")'
	${TS_CMD_LSFD} ${LSFD_XOPT} -p "$PID" -n -o ASSOC,TYPE,SOURCE -Q "$EXPR"
	echo "ASSOC,TYPE,SOURCE: " $?

	chmod u+rwx "$DIR"
	rm "$FILE"
	rmdir "$DIR"

	echo DONE >&"${MKFDS[1]}"
    fi
} > "$TS_OUTPUT" 2>&1
wait "${MKFDS_PID}"

ts_finalize
