#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="passing broken expressions to -Q option"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"

ts_cd "$TS_OUTDIR"

{
    $TS_CMD_LSFD -Q '('
    $TS_CMD_LSFD -Q ')'
    $TS_CMD_LSFD -Q '(FD == 1)garbage'
    $TS_CMD_LSFD -Q 'NOSUCHCOLUMN'
} > $TS_OUTPUT 2>&1

sed -i -e 's/syntax error.*/<bison syntax error message removed>/g' \
	$TS_OUTPUT $TS_ERRLOG

ts_finalize
