#!/bin/bash
#
# Copyright (C) 2021 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="read-only regular file"

. $TS_TOPDIR/functions.sh
ts_init "$*"

. $TS_SELF/lsfd-functions.bash

ts_check_test_command "$TS_CMD_LSFD"

ts_check_test_command "$TS_HELPER_MKFDS"

ts_check_prog "stat"
ts_check_prog "id"

ts_cd "$TS_OUTDIR"

PID=
FD=3
EXPR=

{
    target=/etc/passwd
    coproc MKFDS { "$TS_HELPER_MKFDS" --comm ABC ro-regular-file $FD offset=1 file=$target; }
    if read -u ${MKFDS[0]} PID; then
	EXPR='(PID == '"${PID}"') and (FD == '"$FD"')'
	${TS_CMD_LSFD} -n -o COMMAND,ASSOC,MODE,TYPE,NAME,POS -Q "${EXPR}"
	echo 'COMMAND,ASSOC,MODE,TYPE,NAME,POS': $?

	LSFD_PID=$(${TS_CMD_LSFD} --raw -n -o PID -Q "${EXPR}")
	echo 'PID[RUN]:' $?
	[ "${LSFD_PID}" == "${PID}" ]
	echo 'PID[STR]:' $?

	LSFD_INODE=$(${TS_CMD_LSFD} --raw -n -o INODE -Q "${EXPR}")
	echo 'INODE[RUN]:' $?
	[ "${LSFD_INODE}"  == "$(stat -c %i $target)" ]
	echo 'INODE[STR]:' $?

	LSFD_UID=$(${TS_CMD_LSFD} --raw -n -o UID -Q "${EXPR}")
	echo 'UID[RUN]:' $?
	[ "${LSFD_UID}" == $(id -u) ]
	echo 'UID[STR]:' $?

	LSFD_USER=$(${TS_CMD_LSFD} --raw -n -o USER -Q "${EXPR}")
	echo 'USER[RUN]:' $?
	[ "${LSFD_USER}" == $(id -u -n) ]
	echo 'USER[STR]:' $?

	LSFD_SIZE=$(${TS_CMD_LSFD} --raw -n -o SIZE -Q "${EXPR}")
	echo 'SIZE[RUN]:' $?
	[ "${LSFD_SIZE}" == $(stat -c %s $target) ]
	echo 'SIZE[STR]:' $?

	lsfd_compare_dev "${TS_CMD_LSFD}" $target "${EXPR}"

	kill -CONT ${PID}
	wait ${MKFDS_PID}
    fi
} > $TS_OUTPUT 2>&1

ts_finalize
