#!/bin/bash
#
# Copyright (C) 2021 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="block device with O_RDONLY"

. $TS_TOPDIR/functions.sh
ts_init "$*"
ts_skip_nonroot

. $TS_SELF/lsfd-functions.bash

ts_check_test_command "$TS_CMD_LSFD"

ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

ts_device_init
LSFD_LOOP_BDEV=$TS_LODEV
LSFD_LOOP_BDEV_BASENAME=${LSFD_LOOP_BDEV##*/}
LSFD_LOOP_BDEV_NUM=${LSFD_LOOP_BDEV_BASENAME#loop}

PID=
FD=3
EXPR=

{
    coproc MKFDS { "$TS_HELPER_MKFDS" ro-block-device $FD blkdev=${LSFD_LOOP_BDEV}; }
    if read -u ${MKFDS[0]} PID; then
	EXPR='(PID == '"${PID}"') and (FD == '"$FD"')'
	${TS_CMD_LSFD} -n -o ASSOC,MODE,TYPE,POS,BLKDRV,DEVTYPE -Q "${EXPR}"
	echo 'ASSOC,MODE,TYPE,,POS,,BLKDRV,DEVTYPE': $?

	LSFD_NAME=$(${TS_CMD_LSFD} --raw -n -o NAME -Q "${EXPR}")
	echo 'NAME[RUN]:' $?
	[ "${LSFD_NAME}" == "${LSFD_LOOP_BDEV}" ]
	echo 'NAME[STR]:' $?

	LSFD_SOURCE=$(${TS_CMD_LSFD} --raw -n -o SOURCE -Q "${EXPR}")
	echo 'SOURCE[RUN]:' $?
	[ "${LSFD_SOURCE}" == "${LSFD_LOOP_BDEV_BASENAME}" ]
	echo 'SOURCE[STR]:' $?

	LSFD_MAJ_MIN=$(${TS_CMD_LSFD} --raw -n -o MAJ:MIN -Q "${EXPR}")
	echo 'MAJ_MIN[RUN]:' $?
	[ "${LSFD_MAJ_MIN}" == 7:"${LSFD_LOOP_BDEV_NUM}" ]
	echo 'MAJ_MIN[STR]:' $?

	LSFD_RDEV=$(${TS_CMD_LSFD} --raw -n -o RDEV -Q "${EXPR}")
	echo 'RDEV[RUN]:' $?
	[ "${LSFD_RDEV}" == 7:"${LSFD_LOOP_BDEV_NUM}" ]
	echo 'RDEV[STR]:' $?

	lsfd_compare_dev "${TS_CMD_LSFD}" "${LSFD_LOOP_BDEV}" "${EXPR}"

	kill -CONT ${PID}
	wait ${MKFDS_PID}
    fi
} > $TS_OUTPUT 2>&1

ts_finalize
