#!/bin/bash
#
# Copyright (C) 2023 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="tun device and interface behind the device"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"
ts_skip_nonroot

[[ -e /dev/net/tun ]] || ts_skip "/dev/net/tun does not exist"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"
ts_check_test_command "$TS_CMD_UNSHARE"
ts_check_test_command "$TS_CMD_LSNS"

ts_cd "$TS_OUTDIR"

PID=
FD=3
IFNAME=
readonly MYNETNS=$($TS_CMD_LSNS -n -t net -p $$ -oNS)

if [[ -z "$MYNETNS" ]]; then
    ts_skip "the current netns is unknown"
fi

cdev_tun_test()
{
    local unshare=$1
    local tname
    local devnetns_available
    local netns

    if [[ -z "$unshare" ]]; then
	tname=domestic
	netns=$MYNETNS
    else
	tname=foreign
    fi

    ts_init_subtest "$tname"
    {
	coproc MKFDS { $unshare "$TS_HELPER_MKFDS" cdev-tun $FD ; }

	if read -u ${MKFDS[0]} PID IFNAME; then
	    EXPR='(FD == '"$FD"')'
	    ${TS_CMD_LSFD} -p "${PID}" -n -o ASSOC,MODE,TYPE,SOURCE -Q "${EXPR}"
	    echo 'ASSOC,MODE,TYPE,SOURCE': $?

	    if [[ -z "$netns" ]]; then
		netns=$($TS_CMD_LSNS -n -t net -p $PID -oNS)
	    fi

	    output=$(${TS_CMD_LSFD} -p "${PID}" -n --raw -o NAME -Q "${EXPR}")
	    if [[ "$output" =~ "iface=$IFNAME"(\\x20devnetns=$netns)? ]]; then
		echo 'NAME': 0
		if [[ -n "${BASH_REMATCH[1]}" ]]; then
		    devnetns_available=yes
		fi
	    else
		echo 'NAME': 1
		echo "expected NAME: iface=$IFNAME"
		echo "output NAME: $output"
		echo "netns: $netns"
	    fi

	    output=$(${TS_CMD_LSFD} -p "${PID}" -n --raw -o TUN.IFACE -Q "${EXPR}")
	    if [[ "$output" == "$IFNAME" ]]; then
		echo 'TUN.IFACE': 0
	    else
		echo 'TUN.IFACE': 1
		echo "expected TUN.IFACE: $IFNAME"
		echo "output TUN.IFACE: $output"
	    fi
	fi
    } > $TS_OUTPUT 2>&1
    ts_finalize_subtest

    ts_init_subtest "$tname"-devnetns
    if [[ -z "${devnetns_available}" ]]; then
	ts_skip_subtest "no method to access devnetns on this platform"
    else
	{
	    output=$(${TS_CMD_LSFD} -p "${PID}" -n --raw -o TUN.DEVNETNS -Q "${EXPR}")
	    if [[ "$output" == "$netns" ]]; then
		echo 'TUN.DEVNETNS': 0
	    else
		echo 'TUN.DEVNETNS': 1
		echo "expected TUN.DEVNETNS: $netns"
		echo "output TUN.DEVNETNS: $output"
	    fi
	} > $TS_OUTPUT 2>&1
    fi
    ts_finalize_subtest


    if [[ -n "$PID" ]]; then
	echo DONE >&"${MKFDS[1]}"
    fi

    wait ${MKFDS_PID}
}

cdev_tun_test
cdev_tun_test "$TS_CMD_UNSHARE" --net

ts_finalize
