#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="UDP and UDP-Lite sockets"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"
ts_check_native_byteorder

ts_cd "$TS_OUTDIR"

PID=
FDS=3
FDC=4
EXPR=(
    '(TYPE == "UDP") and (FD >= 3) and (FD <= 4)'
    '(TYPE == "UDP-Lite") and (FD >= 3) and (FD <= 4)'
)
EXPR_server=(
    '(TYPE == "UDP") and (FD == 3)'
    '(TYPE == "UDP-Lite") and (FD == 3)'
)
EXPR_client=(
    '(TYPE == "UDP") and (FD == 4)'
    '(TYPE == "UDP-Lite") and (FD == 4)'
)
COLNS=(
    'UDP'
    'UDPLite'
)
NAME=
LADDR=
LPORT=

for lite in 0 1; do
    coproc MKFDS { "$TS_HELPER_MKFDS" udp $FDS $FDC \
				      server-port=56789 \
				      client-port=45678 \
				      lite=$lite; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.LADDR,${COLNS[$lite]}.LPORT,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT \
		       -p "${PID}" -Q "${EXPR[$lite]}"
	echo "ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.LADDR,${COLNS[$lite]}.LPORT,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT": $?

	echo DONE >&"${MKFDS[1]}"
    fi
    wait "${MKFDS_PID}"

    coproc MKFDS { "$TS_HELPER_MKFDS" udp $FDS $FDC \
				      server-port=56789 \
				      client-port=45678 \
				      server-do-bind=no \
				      lite=$lite; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,TYPE,STTYPE,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.LADDR,${COLNS[$lite]}.LPORT,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT \
		       -p "${PID}" -Q "${EXPR_server[$lite]}"
	echo "ASSOC,TYPE,STTYPE,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.LADDR,${COLNS[$lite]}.LPORT,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT": $?

	NAME=$(${TS_CMD_LSFD} -n \
			      --raw \
			      -o NAME \
			      -p "${PID}" -Q "${EXPR_server[$lite]}")
	if [[ "$NAME" =~ ^socket:\[[[:digit:]]+\]$ ]]; then
	    echo "NAME pattern match: OK"
	else
	    echo "NAME pattern match: FAILED (NAME=$NAME)"
	fi

	echo DONE >&"${MKFDS[1]}"
    fi
    wait "${MKFDS_PID}"

    coproc MKFDS { "$TS_HELPER_MKFDS" udp $FDS $FDC \
				      server-port=56789 \
				      client-port=45678 \
				      client-do-bind=no \
				      lite=$lite; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,TYPE,STTYPE,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT \
		       -p "${PID}" -Q "${EXPR_client[$lite]}"
	echo "ASSOC,TYPE,STTYPE,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,${COLNS[$lite]}.RADDR,${COLNS[$lite]}.RPORT": $?

	LADDR=$(${TS_CMD_LSFD} -n \
			       --raw \
			       -o ${COLNS[$lite]}.LADDR \
			       -p "${PID}" -Q "${EXPR_client[$lite]}")
	LPORT=$(${TS_CMD_LSFD} -n \
			       --raw \
			       -o ${COLNS[$lite]}.LPORT \
			       -p "${PID}" -Q "${EXPR_client[$lite]}")

	if [[ 127.0.0.1:$LPORT == ${LADDR} ]]; then
	    echo "LADDR/LPORT pattern match: OK"
	else
	    echo "LADDR/LPORT pattern match: FAILED (LADDR=$LADDR, LPORT=$LPORT)"
	fi

	echo DONE >&"${MKFDS[1]}"
    fi
    wait "${MKFDS_PID}"

    coproc MKFDS { "$TS_HELPER_MKFDS" udp $FDS $FDC \
				      server-port=56789 \
				      client-port=45678 \
				      client-do-connect=no \
				      lite=$lite; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,UDP.LADDR,UDP.LPORT,UDP.RADDR,UDP.RPORT \
		       -p "${PID}" -Q "${EXPR[$lite]}"
	echo 'ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,UDP.LADDR,UDP.LPORT,UDP.RADDR,UDP.RPORT': $?

	echo DONE >&"${MKFDS[1]}"
    fi
    wait "${MKFDS_PID}"
done > "$TS_OUTPUT" 2>&1

ts_finalize
