#!/bin/bash
#
# Copyright (C) 2023 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="eventfd with fork"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

PID0=
PID1=
FD0=3
FD1=4
EXPR=
ID0=
ID1=
NAME0=
NAME1=
ENDPOINTS=

{
    coproc MKFDS { "$TS_HELPER_MKFDS" eventfd $FD0 $FD1 ; }
    if read -u ${MKFDS[0]} PID0 PID1; then
	EXPR='(FD == '"$FD0"') or (FD =='"$FD1"')'
	${TS_CMD_LSFD} -p "${PID0}" -n -o ASSOC,MODE,TYPE,SOURCE -Q "${EXPR}"
	echo 'parent: ASSOC,MODE,TYPE,SOURCE': $?

	NAME0=$(${TS_CMD_LSFD} -p "${PID0}" --raw -n -o NAME -Q "${EXPR}")
	echo 'parent: NAME': $?

	ID0=$(${TS_CMD_LSFD} -p "${PID0}" --raw -n -o EVENTFD.ID -Q "${EXPR}")
	echo 'parent: ID': $?

	EXPR='(FD == '"$FD0"') or (FD =='"$FD1"')'
	${TS_CMD_LSFD} -p "${PID1}" -n -o ASSOC,MODE,TYPE,SOURCE -Q "${EXPR}"
	echo 'child: ASSOC,MODE,TYPE,SOURCE': $?

	NAME1=$(${TS_CMD_LSFD} -p "${PID1}" --raw -n -o NAME -Q "${EXPR}")
	echo 'child: NAME': $?

	ID1=$(${TS_CMD_LSFD} -p "${PID1}" --raw -n -o EVENTFD.ID -Q "${EXPR}")
	echo 'child: ID': $?

	if [ "${NAME0}" == "${NAME1}" ]; then
	    echo 'NAME[STR]:' $?
	else
	    echo 'NAME[STR]:' $?
	    echo NAME0: "${NAME0}"
	    echo NAME1: "${NAME1}"
	fi

	if [ "${ID0}" == "${ID1}" ]; then
	    echo 'ID[STR]:' $?
	else
	    echo 'ID[STR]:' $?
	    echo ID0: "${ID0}"
	    echo ID0: "${ID1}"
	fi

	if [ "${NAME0}" == "id=${ID1}" ]; then
	    echo 'NAMExID[STR]:' $?
	else
	    echo 'NAMExID[STR]:' $?
	    echo NAME0: "${NAME0}"
	    echo ID0: "${ID0}"
	fi

	EXPR='(EVENTFD.ID == '"${ID0}"')'
	ENDPOINTS=$(${TS_CMD_LSFD} --raw -n -o PID,ASSOC,ENDPOINTS -Q "${EXPR}")
	tmp=$(printf "%d %d %d,test_mkfds,%d\n%d %d %d,test_mkfds,%d" \
		     "$PID0" "$FD0" "$PID1" "$FD1" \
		     "$PID1" "$FD1" "$PID0" "$FD0")
	if [ "$ENDPOINTS" == "$tmp" ]; then
	    echo 'ENDPOINTS[STR]:' $?
	else
	    echo 'ENDPOINTS[STR]:' $?
	    echo 'ENDPOINTS:' "$ENDPOINTS"
	    echo 'lsfd:' "$tmp"
	fi

	echo DONE >&"${MKFDS[1]}"
    fi
    wait ${MKFDS_PID}
} > $TS_OUTPUT 2>&1

ts_finalize
