#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="TCP sockets"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

# This test cases doesn't work well on Qemu user mode emulation.
#
# tests_mkfds command uses hton* functions when passing
# IP addresses and TCP ports to Linux via bind(2) and connect(2).
# On the other hand, Linux provides these information in host
# byte order via /proc/net/tcp that lsfd reads.
#
# If Qemu emulates a big-endian architecture (e.g. s390) but its
# host Linux runs on little-endian architecture (e.g. x86_64),
# this test case doesn't work.
#
# test_mkfds built for s390 passes htonl(127.0.0.1) value to
# x86_64 Linux. The linux may receive 1.0.0.127. The Linux
# prints "1.0.0.127" in /proc/net/tcp. lsfd reads the string.
# The string doesn't much 127.0.0.1.
ts_skip_qemu_user

ts_cd "$TS_OUTDIR"

PID=
FDS=3
FDC=4
FDA=5
EXPR='(TYPE == "TCP") and (FD >= 3) and (FD <= 5)'

{
    coproc MKFDS { "$TS_HELPER_MKFDS" tcp $FDS $FDC $FDA \
				      server-port=34567 \
				      client-port=23456 ; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,TCP.LADDR,TCP.LPORT,TCP.RADDR,TCP.RPORT \
		       -p "${PID}" -Q "${EXPR}"
	echo 'ASSOC,TYPE,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,INET.LADDR,INET.RADDR,TCP.LADDR,TCP.LPORT,TCP.RADDR,TCP.RPORT': $?

	kill -CONT "${PID}"
	wait "${MKFDS_PID}"
    fi
} > "$TS_OUTPUT" 2>&1

ts_finalize
