#!/bin/bash
#
# Copyright (C) 2022 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="UNIX dgram sockets"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"

ts_cd "$TS_OUTDIR"

PID=
FDS=3
FDC=4
EXPR='(TYPE == "UNIX") and ((FD == 3) or (FD == 4))'

{
    coproc MKFDS { "$TS_HELPER_MKFDS" unix-dgram $FDS $FDC \
				      path=test_mkfds-unix-dgram ; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,UNIX.PATH \
		       -p "${PID}" -Q "${EXPR}"
	echo 'ASSOC,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,UNIX.PATH': $?

	kill -CONT "${PID}"
	wait "${MKFDS_PID}"
    fi

    coproc MKFDS { "$TS_HELPER_MKFDS" unix-dgram $FDS $FDC \
				      path=test_mkfds-unix-dgram \
				      abstract=true ; }
    if read -r -u "${MKFDS[0]}" PID; then
	${TS_CMD_LSFD} -n \
		       -o ASSOC,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,UNIX.PATH \
		       -p "${PID}" -Q "${EXPR}"
	echo 'ASSOC,STTYPE,NAME,SOCK.STATE,SOCK.TYPE,SOCK.LISTENING,UNIX.PATH': $?

	kill -CONT "${PID}"
	wait "${MKFDS_PID}"
    fi
} > "$TS_OUTPUT" 2>&1

ts_finalize
