.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH DOMAINNAME 1 "26 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
domainname \- set or print domain of current host
.SH SYNOPSIS
.BR "domainname [ " name " ]"
.SH DESCRIPTION
.B domainname
prints the domainname of the current host, from the
.BR getdomainname (3)
library call.  If an argument is present and the effective UID is 0,
.B domainname
changes the name of the host, with the
.BR setdomainname (2)
system call.  This is usually done at boot time in the
.I /etc/rc.local
script.
.SH FILES
.I /etc/rc.local
.SH "SEE ALSO"
.BR getdomainname (3),
.BR setdomainname (2),
.BR uname (1),
.BR uname (2)
.SH AUTHOR
Lars Wirzenius by substituting in hostname.c

