.\" Copyright 2017 Red Hat, Inc.
.\"
.\" This file may be copied under the terms of the GNU Public License.
.TH FINCORE 1 "March 2017" "util-linux" "User Commands"
.SH NAME
fincore \- count pages of file contents in core
.SH SYNOPSIS
.B fincore
[options]
.I file ...
.SH DESCRIPTION
.B fincore
counts pages of file contents being resident in memory (in core), and reports
the numbers.  If an error occurs during counting, then an error message is
printed to the stderr and
.B fincore
continues processing the rest of files listed in a command line.

The default output is subject to change.  So whenever possible, you should
avoid using default outputs in your scripts.  Always explicitly define expected
columns by using
.B \-\-output
.I columns-list
in environments where a stable output is required.
.SH OPTIONS
.TP
.BR \-n , " \-\-noheadings"
Do not print a header line in status output.
.TP
.BR \-b , " \-\-bytes"
Print the SIZE column in bytes rather than in a human-readable format.
.TP
.BR \-o , " \-\-output \fIlist\fP"
Define output columns.  See the \fB\-\-help\fP output to get a list of the
currently supported columns. The default list of columns may be extended if \fIlist\fP is
specified in the format \fI+list\fP.
.TP
.BR \-r , " \-\-raw"
Produce output in raw format.  All potentially unsafe characters are hex-escaped
(\\x<code>).
.TP
.BR \-J , " \-\-json"
Use JSON output format.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.SH AUTHORS
.MT yamato@\:redhat.com
Masatake YAMATO
.ME
.SH "SEE ALSO"
.BR mincore (2),
.BR getpagesize (2),
.BR getconf (1)
.SH AVAILABILITY
The fincore command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
