//po4a: entry man manual
// Copyright 1993, 1994, 1995 by Theodore Ts'o.  All Rights Reserved.
// This file may be copied under the terms of the GNU General Public License.
ifdef::neverdefined[---]

= findfs(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: findfs

== NAME

findfs - find a filesystem by label or UUID

== SYNOPSIS

*findfs* _TAGNAME_**=**_value_

== DESCRIPTION

*findfs* will search the block devices in the system for a filesystem or partition
with the specified tag. The currently supported tags are:

____
**LABEL=**_label_::
Specifies a filesystem label.

**UUID=**_uuid_::
Specifies a filesystem UUID.

**PARTUUID=**_uuid_::
Specifies a partition UUID. Partition identifiers are supported for example for GUID Partition Table (GPT) partition tables.

**PARTLABEL=**_label_::
Specifies a partition label (name). Partition labels are supported for example for GPT and MAC partition tables.
____

If the filesystem or partition is found, the device name will be printed on stdout.
If the input is not in the format of _TAGNAME_**=**_value_, then the input will be
copied to the output without any modification.

You can get a complete overview about the filesystems and partitions in the system
with one of the following commands:

____
*lsblk --fs*

*partx --show* _disk_

*blkid*
____

== OPTIONS

include::man-common/help-version.adoc[]

== EXIT STATUS

*0*::
success
*1*::
label or UUID cannot be found
*2*::
usage error, wrong number of arguments or unknown option

== ENVIRONMENT

LIBBLKID_DEBUG=all::
enables libblkid debug output.

== AUTHORS

*findfs* was originally written by mailto:tytso@mit.edu[Theodore Ts'o] and re-written for the util-linux package by mailto:kzak@redhat.com[Karel Zak].

== SEE ALSO

*blkid*(8),
*lsblk*(8),
*partx*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
