.\" Copyright 1993, 1994, 1995 by Theodore Ts'o.  All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\"
.TH FINDFS 8 "March 2014" "util-linux" "System Administration"
.SH NAME
findfs \- find a filesystem by label or UUID
.SH SYNOPSIS
.B findfs
.BI NAME= value
.SH DESCRIPTION
.B findfs
will search the block devices in the system looking for a filesystem or
partition with specified tag. The currently supported tags are:
.TP
.B LABEL=<label>
Specifies filesystem label.
.TP
.B UUID=<uuid>
Specifies filesystem UUID.
.TP
.B PARTUUID=<uuid>
Specifies partition UUID. This partition identifier is supported for example for
GUID  Partition  Table (GPT) partition tables.
.TP
.B PARTLABEL=<label>
Specifies partition label (name). The partition labels are supported for example for
GUID Partition Table (GPT) or MAC partition tables.
.PP
If the filesystem or partition is found, the device name will be printed on
stdout.

The complete overview about filesystems and partitions you can get for example
by
.RS

.B lsblk \-\-fs

.B partx --show <disk>

.B blkid

.RE

.SH EXIT STATUS
.RS
.PD 0
.TP
.B 0
success
.TP
.B 1
label or uuid cannot be found
.TP
.B 2
usage error, wrong number of arguments or unknown option
.PD
.RE
.SH ENVIRONMENT
.IP LIBBLKID_DEBUG=all
enables libblkid debug output.
.SH AUTHORS
.B findfs
was originally written by
.MT tytso@mit.edu
Theodore Ts'o
.ME
and re-written for the util-linux package by
.MT kzak@redhat.com
Karel Zak
.ME .
.SH SEE ALSO
.BR blkid (8),
.BR lsblk (8),
.BR partx (8)
.SH AVAILABILITY
The findfs command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
