//po4a: entry man manual
= lsclocks(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: lsclocks

== NAME

lsclocks - display system clocks

== SYNOPSIS

*lsclocks* [option]

== DESCRIPTION

*lsclocks* is a simple command to display system clocks.

It allows to display information like current time and resolution of clocks like
CLOCK_MONOTONIC, CLOCK_REALTIME and CLOCK_BOOTTIME.

== OPTIONS

*-J*, *--json*::
Use JSON output format.

*-n*, *--noheadings*::
Don't print headings.

*-o*, *--output* _list_::
Specify which output columns to print. See the *OUTPUT COLUMNS*
section for details of available columns.

*--output-all*::
Output all columns.

*-r*, *--raw*::
Use raw output format.

*-r*, *--time* _clock_::
Show current time of one specific clock.

*--no-discover-dynamic*::
Do not try to discover dynamic clocks.

*-d*, *--dynamic-clock* _path_::
Also display specified dynamic clock.
Can be specified multiple times.

*--no-discover-rtc*::
Do not try to discover RTCs.

*-x*, *--rtc* _path_::
Also display specified RTC.
Can be specified multiple times.

*-c*, *--cpu-clock* _pid_::
Also display CPU clock of specified process.
Can be specified multiple times.

include::man-common/help-version.adoc[]

== OUTPUT COLUMNS

Each column has a type. Types are surround by < and >.

TYPE <``string``>::
Clock type.

ID <``number``>::
Numeric clock ID.

CLOCK <``string``>::
Name in the form *CLOCK_*

NAME <``string``>::
Shorter, easier to read name.

TIME <``number``>::
Current clock timestamp as returned by *clock_gettime()*.

ISO_TIME <``string``>::
ISO8601 formatted version of *TIME*.

RESOL_RAW <``number``>::
Clock resolution as returned by *clock_getres*(2).

RESOL <``number``>::
Human readable version of *RESOL_RAW*.

REL_TIME <``string``>::
*TIME* time formatted as time range.

NS_OFFSET <``number``>::
Offset of the current namespace to the parent namespace as read from */proc/self/timens_offsets*.


== AUTHORS

mailto:thomas@t-8ch.de[Thomas Weißschuh]

== SEE ALSO

*clock_getres*(2) *clock_gettime*(2)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
