.\" lslocks.8 --
.\" Copyright 2012 Davidlohr Bueso <dave@gnu.org>
.\" May be distributed under the GNU General Public License

.TH LSLOCKS 8 "February 2012" "util-linux" "System Administration"
.SH NAME
lslocks \-
list local system locks
.SH SYNOPSIS
.B lslocks
.RB [options]

.SH DESCRIPTION
.B lslocks
lists information about all the file held locks in a Linux system.

.SH OPTIONS
.IP "\fB\-p, \-\-pid\fP"
Specify the process id, if none is given, it will display all locks
.IP "\fB\-h, \-\-help\fP"
Print a help text and exit.
.IP "\fB\-o, \-\-output \fIlist\fP"
Specify which output columns to print. Use
.B "--help"
to get a list of all supported columns.
.IP "\fB\-n, \-\-noheadings\fP"
Do not print a header line.
.IP "\fB\-u, \-\-notruncate\fP"
Do not truncate text in columns.
.IP "\fB\-r, \-\-raw\fP"
Use the raw output format.

.SH OUTPUT
.IP "COMMAND"
The command name of the process holding the lock.

.IP "PID"
Process ID which holds the lock.

.IP "TYPE"
Type of lock, can be FLOCK (created with flock(2)) or POSIX (created with fcntl(2) and lockf(2))

.IP "SIZE"
Size of the locked file.

.IP "MODE"
Lock access permissions (read, write).

.IP "M"
Mandatory state of the lock: 0 if none; 1 if set.  (See chmod(1)).

.IP "START"
Relative byte offset of the lock.

.IP "END"
Ending offset of the lock.

.IP "PATH"
Full path of the lock - if none is found or no permissions to read the path it
will fallback to the device's mountpoint. The path might be truncated, use
.B "--notruncate"
to get the full path.

.SH NOTES
.nf
The lslocks command is meant to replace the lslk(8) command, originally written by
Victor A. Abell <abe@purdue.edu> and unmaintained since 2001.
.fi

.SH AUTHORS
.nf
Davidlohr Bueso <dave@gnu.org>
.fi

.SH "SEE ALSO"
.BR flock (1)
.BR fcntl (2)
.BR lockf (2)

.SH AVAILABILITY
The lslocks command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
