.\"
.\" Version 1.4 of namei
.\"
.TH NAMEI 1 "Local"
.SH NAME
namei - follow a pathname until a terminal point is found
.SH SYNOPSIS
.B namei
.RI [ options ]
.IR  pathname ...
.SH DESCRIPTION
.B Namei
uses its arguments as pathnames to any type
of Unix file (symlinks, files, directories, and so forth).
.B Namei
then follows each pathname until a terminal
point is found (a file, directory, char device, etc).
If it finds a symbolic link, we show the link, and start
following it, indenting the output to show the context.
.PP
This program is useful for finding a "too many levels of
symbolic links" problems.
.PP
For each line output,
.B namei
outputs a the following characters to identify the file types found:
.LP
.nf
   f: = the pathname we are currently trying to resolve
    d = directory
    l = symbolic link (both the link and it's contents are output)
    s = socket
    b = block device
    c = character device
    p = FIFO (named pipe)
    - = regular file
    ? = an error of some kind
.fi
.PP
.B Namei
prints an informative message when
the maximum number of symbolic links this system can have has been exceeded.
.SH OPTIONS
.IP "\fB\-l, \-\-long\fP"
Use a long listing format (same as -m -o -v).
.IP "\fB\-m, \-\-modes\fP"
Show the mode bits of each file type in the style of ls(1),
for example 'rwxr-xr-x'.
.IP "\fB\-o, \-\-owners\fP"
Show owner and group name of each file.
.IP "\fB\-n, \-\-nosymlinks\fP"
Don't follow symlinks.
.IP "\fB\-v, \-\-vertical\fP"
Vertical align of modes and owners.
.IP "\fB\-x, \-\-mountpoints\fP"
Show mount point directories with a 'D', rather than a 'd'.
.SH AUTHOR
The original
.B namei
program was written by Roger Southwick <rogers@amadeus.wr.tek.com>.

The program was re-written by Karel Zak <kzak@redhat.com>.
.SH BUGS
To be discovered.
.SH "SEE ALSO"
.BR ls (1),
.BR stat (1)
.SH AVAILABILITY
The namei command is part of the util-linux-ng package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux-ng/.
