.\" Copyright (c) 2017 Sami Kerola
.\" The 3-Clause BSD License
.TH UUIDPARSE "1" "2017-06-18" "util-linux" "User Commands"
.SH NAME
uuidparse \- a utility to parse unique identifiers
.SH SYNOPSIS
.B uuidparse
[options]
.I uuid
.SH DESCRIPTION
This command will parse unique identifier inputs from either command line
arguments or standard input.  The inputs are white-space separated.
.SH OUTPUT
.SS Variants
.nr WI \n(.lu-\n(.iu-\w'Microsoft'u-3n
.TS
tab(:);
l lw(\n(WIu).
NCS:T{
Network Computing System identifier.  These were the original UUIDs.
T}
DCE:T{
The Open Software Foundation's (OSF) Distributed Computing Environment UUIDs.
T}
Microsoft:T{
Microsoft Windows platform globally unique identifier (GUID).
T}
other:T{
Unknown variant.  Usually invalid input data.
T}
.TE
.SS Types
.TS
tab(:);
l l.
nil:Special type for zero in type file.
time-based:The DCE time based.
DCE:The DCE time and MAC Address.
name-based:RFC 4122 md5sum hash.
random:RFC 4122 random.
sha1-based:RFC 4122 sha-1 hash.
unknown:Unknown type.  Usually invalid input data.
.TE
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Use JSON output format.
.TP
\fB\-n\fR, \fB\-\-noheadings\fR
Do not print a header line.
.TP
\fB\-o\fR, \fB\-\-output\fR
Specify which output columns to print.  Use \-\-help to get a list of all
supported columns.
.TP
\fB\-r\fR, \fB\-\-raw\fR
Use the raw output format.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.SH AUTHORS
.MT kerolasa@iki.fi
Sami Kerola
.ME
.SH SEE ALSO
.BR uuidgen (1),
.BR libuuid (3),
.UR https://\:tools.ietf.org\:/html\:/rfc4122
RFC 4122
.UE
.SH AVAILABILITY
The uuidparse command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
