//po4a: entry man manual
////
Copyright (c) 1990 The Regents of the University of California.
All rights reserved.

This code is derived from software contributed to Berkeley by
Michael Rendell.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
This product includes software developed by the University of
California, Berkeley and its contributors.
4. Neither the name of the University nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

    @(#)col.1	6.8 (Berkeley) 6/17/91
////
= col(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: col

== NAME

col - filter reverse line feeds from input

== SYNOPSIS

*col* _options_

== DESCRIPTION

*col* filters out reverse (and half-reverse) line feeds so the output is in the correct order, with only forward and half-forward line feeds. It also replaces any whitespace characters with tabs where possible. This can be useful in processing the output of *nroff*(1) and *tbl*(1).

*col* reads from standard input and writes to standard output.

== OPTIONS

*-b*, *--no-backspaces*::
Do not output any backspaces, printing only the last character written to each column position.

*-f*, *--fine*::
Permit half-forward line feeds. Normally characters destined for a half-line boundary are printed on the following line.

*-h*, *--tabs*::
Output tabs instead of multiple spaces.

*-l*, *--lines* _number_::
Buffer at least _number_ lines in memory. By default, 128 lines are buffered.

*-p*, *--pass*::
Force unknown control sequences to be passed through unchanged. Normally *col* will filter out any control sequences other than those recognized and interpreted by itself, which are listed below.

*-x*, *--spaces*::
Output multiple spaces instead of tabs.

*-H*, *--help*::
Display help text and exit.

*-V*, *--version*::
Print version and exit.

== CONFORMING TO

The *col* utility conforms to the Single UNIX Specification, Version 2. The *-l* option is an extension to the standard.

== NOTES

The control sequences for carriage motion that *col* understands and their decimal values are listed in the following table:

*ESC-7*::
reverse line feed (escape then 7)
*ESC-8*::
half reverse line feed (escape then 8)
*ESC-9*::
half forward line feed (escape then 9)
*backspace*::
moves back one column (8); ignored in the first column
*newline*::
forward line feed (10); also does carriage return
*carriage return*::
(13)
*shift in*::
shift to normal character set (15)
*shift out*::
shift to alternate character set (14)
*space*::
moves forward one column (32)
*tab*::
moves forward to next tab stop (9)
*vertical tab*::
reverse line feed (11)

All unrecognized control characters and escape sequences are discarded.

*col* keeps track of the character set as characters are read and makes sure the character set is correct when they are output.

If the input attempts to back up to the last flushed line, *col* will display a warning message.

== HISTORY

A *col* command appeared in Version 6 AT&T UNIX.

== SEE ALSO

*expand*(1),
*nroff*(1),
*tbl*(1)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
