.\" This page is in the public domain
.Dd August 2, 2001
.Dt line 1
.Os Linux 2.4
.Sh NAME
.Nm line
.Nd read one line
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
copies one line (up to a newline) from standard input and writes it to
standard output. It always prints at least a newline and returns an exit
code of 1 on EOF.
.Sh SEE ALSO
.Xr read 2 ,
.Xr sh 1
