#!/bin/bash

# Copyright (C) 2014 Ondrej Oprala <ooprala@redhat.com

TS_TOPDIR="${0%/*}/../.."
TS_DESC="debugging"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

TESTPROG="$TS_HELPER_LIBMOUNT_DEBUG"

[ -x $TESTPROG ] || ts_skip "test not compiled"

# CACHE | LOCKS
ts_init_subtest "set-from-code"
ts_run $TESTPROG 20 2>&1 | grep -o '0x.*' &> $TS_OUTPUT
ts_finalize_subtest

# CACHE | LOCKS
ts_init_subtest "set-from-env-str"
LIBMOUNT_DEBUG=cache,locks ts_run $TESTPROG 2>&1 | grep -o '0x.*' &> $TS_OUTPUT
ts_finalize_subtest

# CACHE | LOCKS
ts_init_subtest "set-from-env-int"
LIBMOUNT_DEBUG=20 ts_run $TESTPROG 2>&1 | grep -o '0x.*' &> $TS_OUTPUT
ts_finalize_subtest

ts_finalize
