#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="race conditions"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_SCRIPT"

# this test may fail on systems with very heavy load
# https://github.com/util-linux/util-linux/issues/296
TS_KNOWN_FAIL="yes"

bingofile="$TS_OUTDIR/${TS_TESTNAME}-bingo"

count=1000
for i in `seq 1 $count`; do
	$TS_CMD_SCRIPT -q -c "printf 'Bingo\n'" $bingofile
done | grep -c Bingo >> $TS_OUTPUT

seen=$(<$TS_OUTPUT)
if [ "$seen" = "$count" ]; then
	echo "all bingos seen" > $TS_OUTPUT
else
	echo "only $seen of $count bingos seen" > $TS_OUTPUT
fi

rm -f $bingofile

ts_finalize

