#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2025 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="getino"

. "$TS_TOPDIR/functions.sh"
ts_init "$*"
ts_skip_nonroot

ts_check_test_command "$TS_CMD_GETINO"
ts_check_test_command "$TS_CMD_UNSHARE"
ts_check_test_command "$TS_CMD_RUNUSER"
ts_check_test_command "$TS_HELPER_STRERROR"
ts_check_prog "stat"

# make sure we do not use shell built-in command
if [ "$TS_USE_SYSTEM_COMMANDS" == "yes" ]; then
	TS_CMD_KILL="$(which kill)"
fi

# The pidfs was only introduced in kernel version 6.9,
# which means we cannot get a valid pidfd from earlier versions,
# so we can confidently anticipate the test failure.
if ts_kernel_ver_lt 6 9; then
	TS_KNOWN_FAIL="yes"
fi

ts_init_subtest "single-pid"
if "$TS_CMD_GETINO" 1 &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "multiple-pids"
if "$TS_CMD_GETINO" 1 1 1 1 1 &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "invalid-pid"
if ! "$TS_CMD_GETINO" "invalid-pid" &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "print-pid-option" 
res=$("$TS_CMD_GETINO" --print-pid 1 2>/dev/null | grep -Eo '^[[:digit:]]*:[[:digit:]]*$'); 
if [ -n "$res" ]; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest


function do_ns_check() {
  local ns_name="$1"
  local unshare_opts="$2"
  local ts_ns_ino unshare_ns_ino

  if [ -r /proc/self/ns/"${ns_name}" ]; then
    ts_ns_ino=$("$TS_CMD_GETINO" --"${ns_name}"ns $$ 2>>"$TS_ERRLOG")
    #shellcheck disable=SC2086
    unshare_ns_ino=$("$TS_CMD_UNSHARE" $unshare_opts bash -c \
                                    "$TS_CMD_GETINO --${ns_name}ns \$\$" 2>>"$TS_ERRLOG")

    if (( ts_ns_ino == unshare_ns_ino )); then
      ts_failed_subtest "${ns_name} namespace unchanged (NS ID: $ts_ns_ino)"
    fi
  else
    ts_skip "no ${ns_name} namespace support"
  fi
}

"$TS_CMD_GETINO" --ipcns $$ > /dev/null 2>&1 || ts_skip "namespace ioctl not supported"

ts_init_subtest "ipcns"
do_ns_check "ipc" "--ipc"
ts_finalize_subtest

ts_init_subtest "netns"
do_ns_check "net" "--net"
ts_finalize_subtest

ts_init_subtest "mntns"
do_ns_check "mnt" "--mount"
ts_finalize_subtest

ts_init_subtest "utsns"
do_ns_check "uts" "--uts"
ts_finalize_subtest

ts_init_subtest "timens"
do_ns_check "time" "--time"
ts_finalize_subtest

ts_init_subtest "pidns"
do_ns_check "pid" "--pid --fork"
ts_finalize_subtest

ts_init_subtest "cgroupns"
do_ns_check "cgroup" "--cgroup"
ts_finalize_subtest

ts_init_subtest "userns"
if [ -r /proc/self/ns/user ]; then
  getino_owner="$(stat --format=%U "$TS_CMD_GETINO")"
  ts_user_ns=$("$TS_CMD_GETINO" --userns $$ 2>>"$TS_ERRLOG")
  unshare_user_ns=$("$TS_CMD_RUNUSER" --user "$getino_owner" -- \
                      "$TS_CMD_UNSHARE" --user \
                        bash -c "$TS_CMD_GETINO --userns \$\$" 2>>"$TS_ERRLOG")

  if grep "$("$TS_HELPER_STRERROR" EACCES)" "$TS_ERRLOG" &>/dev/null; then
    ts_skip "missing permissions to obtain user namespace"
  else
    (( ts_user_ns == unshare_user_ns )) && ts_failed_subtest "user namespace unchanged"
  fi
else
  ts_skip "no user namespace support"
fi
ts_finalize_subtest


ts_finalize
