//po4a: entry man manual
= adjtime_config(5)
:doctype: manpage
:man manual: File formats
:man source: util-linux {release-version}
:page-layout: base
:configfile: adjtime_config

== NAME

adjtime_config - information about hardware clock setting and drift factor

== SYNOPSIS

_/etc/adjtime_

== DESCRIPTION

The file _/etc/adjtime_ contains descriptive information about the hardware mode clock setting and clock drift factor. The file is read and write by *hwclock*(8); and read by programs like rtcwake to get RTC time mode.

The file is usually located in _/etc_, but tools like *hwclock*(8) or *rtcwake*(8) can use alternative location by command line options if write access to _/etc_ is unwanted. The default clock mode is "UTC" if the file is missing.

The Hardware Clock is usually not very accurate. However, much of its inaccuracy is completely predictable - it gains or loses the same amount of time every day. This is called systematic drift. The util *hwclock*(8) keeps the file _/etc/adjtime_, that keeps some historical information. For more details see "*The Adjust Function*" and "*The Adjtime File*" sections from *hwclock*(8) man page.

The _adjtime_ file is formatted in ASCII.

=== First line

Three numbers, separated by blanks:

*drift factor*::
the systematic drift rate in seconds per day (floating point decimal)

*last adjust time*::
the resulting number of seconds since 1969 UTC of most recent adjustment or calibration (decimal integer)

*adjustment status*::
zero (for compatibility with *clock*(8)) as a floating point decimal

=== Second line

*last calibration time*::
The resulting number of seconds since 1969 UTC of most recent calibration. Zero if there has been no calibration yet or it is known that any previous calibration is moot (for example, because the Hardware Clock has been found, since that calibration, not to contain a valid time). This is a decimal integer.

=== Third line

*clock mode*::
Supported values are *UTC* or *LOCAL*. Tells whether the Hardware Clock is set to Coordinated Universal Time or local time. You can always override this value with options on the *hwclock*(8) command line.

== FILES

_/etc/adjtime_

== SEE ALSO

*hwclock*(8),
*rtcwake*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer-config.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
