.\" arch.1 -- 
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Public domain: may be freely distributed.
.TH ARCH 1 "4 July 1997" "Linux 2.0" "Linux Programmer's Manual"
.SH NAME
arch \- print machine architecture
.SH SYNOPSIS
.B arch
.SH DESCRIPTION
.B arch
is equivalent to
.B uname -m

On current Linux systems,
.B arch
prints things such as "i386" or "i486".
.SH SEE ALSO
.BR uname (1) ", " uname (2)
