.TH BLKREPORT 8 "February 2017" "util-linux" "System Administration"
.SH NAME
blkreport \- report zones on a device
.SH SYNOPSIS
.B blkreport
[options]
.RB [ \-z
.IR zone ]
.RB [ \-c
.IR count ]
.I device
.SH DESCRIPTION
.B blkreport
is used to report device zone information.  This is useful for
zoned devices that support the ZAC or ZBC command set.
.PP
By default,
.B blkreport
will report on up to 4k zones from the start of the block device.
Options may be used to modify this behavior, changing the starting zone or
the size of the report, as explained below.
.PP
The
.I device
argument is the pathname of the block device.
.SH OPTIONS
The
.I offset
and
.I length
option arguments may be followed by the multiplicative suffixes KiB (=1024),
MiB (=1024*1024), and so on for GiB, TiB, PiB, EiB, ZiB and YiB (the "iB" is
optional, e.g., "K" has the same meaning as "KiB") or the suffixes
KB (=1000), MB (=1000*1000), and so on for GB, TB, PB, EB, ZB and YB.
Additionally, the 0x prefix can be used to specify \fIoffset\fR and
\fIlength\fR in hex.
.TP
.BR \-z , " \-\-zone "\fIoffset\fP
The starting zone of the report specified as a sector offset.
The provided offset in sector units (512 bytes) should match the start of a zone.
The default value is zero.
.TP
.BR \-c , " \-\-count "\fIlength\fP
The maximum number of zones to be returned by the report.
The default is 4096, the maximum 65536.
.TP
.BR \-v , " \-\-verbose"
Display the number of zones returned in the report.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH AUTHOR
.MT shaun@tancheff.com
Shaun Tancheff
.ME
.SH SEE ALSO
.BR sg_rep_zones (8)
.SH AVAILABILITY
The blkreport command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
