.TH CHCPU 8 "July 2014" "util-linux" "System Administration"
.SH NAME
chcpu \- configure CPUs
.SH SYNOPSIS
.B chcpu
.BR \-c | \-d | \-e | \-g
.I cpu-list
.br
.B chcpu \-p
.I mode
.br
.B chcpu
.BR \-r | \-h | \-V
.SH DESCRIPTION
.B chcpu
can modify the state of CPUs.  It can enable or disable CPUs, scan for new
CPUs, change the CPU dispatching
.I mode
of the underlying hypervisor, and request CPUs from the hypervisor
(configure) or return CPUs to the hypervisor (deconfigure).
.PP
Some options have a
.I cpu-list
argument.  Use this argument to specify a comma-separated list of CPUs.  The
list can contain individual CPU addresses or ranges of addresses.  For
example,
.B 0,5,7,9-11
makes the command applicable to the CPUs with the addresses 0, 5, 7, 9, 10,
and 11.
.SH OPTIONS
.TP
.BR \-c , " \-\-configure " \fIcpu-list\fP
Configure the specified CPUs.  Configuring a CPU means that the hypervisor
takes a CPU from the CPU pool and assigns it to the virtual hardware on which
your kernel runs.
.TP
.BR \-d , " \-\-disable " \fIcpu-list\fP
Disable the specified CPUs.  Disabling a CPU means that the kernel sets it
offline.
.TP
.BR \-e , " \-\-enable " \fIcpu-list\fP
Enable the specified CPUs.  Enabling a CPU means that the kernel sets it
online.  A CPU must be configured, see \fB\-c\fR, before it can be enabled.
.TP
.BR \-g , " \-\-deconfigure " \fIcpu-list\fP
Deconfigure the specified CPUs.  Deconfiguring a CPU means that the
hypervisor removes the CPU from the virtual hardware on which the Linux
instance runs and returns it to the CPU pool.  A CPU must be offline, see
\fB\-d\fR, before it can be deconfigured.
.TP
.BR \-p , " \-\-dispatch " \fImode\fP
Set the CPU dispatching
.I mode
(polarization).  This option has an effect only if your hardware architecture
and hypervisor support CPU polarization.  Available
.I modes
are:
.RS 14
.TP 12
.PD 0
.B horizontal
The workload is spread across all available CPUs.
.TP 12
.B vertical
The workload is concentrated on few CPUs.
.RE
.PD 1
.TP
.BR \-r , " \-\-rescan"
Trigger a rescan of CPUs.  After a rescan, the Linux kernel recognizes
the new CPUs.  Use this option on systems that do not
automatically detect newly attached CPUs.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.

.SH RETURN CODES
.B chcpu
has the following return codes:
.TP
.B 0
success
.TP
.B 1
failure
.TP
.B 64
partial success
.RE
.SH AUTHOR
.MT heiko.carstens@de.ibm.com
Heiko Carstens
.ME
.SH COPYRIGHT
Copyright IBM Corp. 2011
.br
.SH "SEE ALSO"
.BR lscpu (1)
.SH AVAILABILITY
The chcpu command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
