.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Pathname modified by faith@cs.unc.edu
.TH CHROOT 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
chroot \- change root directory and execute a program there
.SH SYNOPSIS
.BI chroot " directory program" " [ " "arg ..." " ]"
.SH DESCRIPTION
.B chroot
changes the root directory for a process to a new directory
executes a program there.
.SH "SEE ALSO"
.BR chroot (2)
.SH AUTHOR
Rick Sladkey <jrs@world.std.com>
