.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH CTRLALTDEL 8 "October 2015" "util-linux" "System Administration"
.SH NAME
ctrlaltdel \- set the function of the Ctrl-Alt-Del combination
.SH SYNOPSIS
.BR "ctrlaltdel hard" | soft
.SH DESCRIPTION
Based on examination of the
.I linux/kernel/reboot.c
code, it is clear that there are two supported functions that the
Ctrl-Alt-Del sequence can perform.
.TP
.B hard
Immediately reboot the computer without calling
.BR sync (2)
and without any other preparation.  This is the default.
.TP
.B soft
Make the kernel send the SIGINT (interrupt) signal to the
.B init
process (this is always the process with PID 1).  If this option is used,
the
.BR init (8)
program must support this feature.  Since there are now several
.BR init (8)
programs in the Linux community, please consult the documentation for the
version that you are currently using.
.PP
When the command is run without any argument, it will display the current
setting.
.PP
The function of
.B ctrlaltdel
is usually set in the
.I /etc/rc.local
file.
.SH OPTIONS
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.SH FILES
.I /etc/rc.local
.SH AUTHORS
.UR poe@daimi.aau.dk
Peter Orbaek
.UE
.SH SEE ALSO
.BR init (8),
.BR systemd (1)
.SH AVAILABILITY
The ctrlaltdel command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
