.\" Copyright 2008 Hayden A. James (hayden.james@gmail.com)
.\" May be distributed under the GNU General Public License
.TH IPCMK "1" "July 2014" "util-linux" "User Commands"
.SH NAME
ipcmk \- make various IPC resources
.SH SYNOPSIS
.B ipcmk
[options]
.SH DESCRIPTION
.B ipcmk
allows you to create System V inter-process communication (IPC) objects:
shared memory segments, message queues,
and semaphore arrays.
.SH OPTIONS
.TP
Resources can be specified with these options:
.TP
.BR \-M , " \-\-shmem " \fIsize
Create a shared memory segment of
.I size
bytes.
The \fIsize\fR argument may be followed by the multiplicative suffixes KiB (=1024), MiB (=1024*1024), and so on for GiB, etc. (the
"iB" is optional, e.g., "K" has the same meaning as "KiB") or the suffixes KB (=1000), MB (=1000*1000), and so on for GB, etc.
.TP
.BR \-Q , " \-\-queue"
Create a message queue.
.TP
.BR \-S , " \-\-semaphore " \fInumber
Create a semaphore array with
.I number
of elements.
.PP
Other options are:
.TP
.BR \-p , " \-\-mode " \fImode
Access permissions for the resource.  Default is 0644.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH AUTHORS
.MT hayden.james@gmail.com
Hayden A. James
.ME
.SH SEE ALSO
.BR ipcrm (1),
.BR ipcs (1),
.BR sysvipc (7)
.SH AVAILABILITY
The ipcmk command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
