.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH IPCRM 8 "9 October 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
ipcs \- provide information on ipc facilities
.SH SYNOPSIS
.BI "ipcrm [ shm | msg | sem ] " id
.SH DESCRIPTION
.B ipcrm
will remove the resource speccified by
.IR id .
.SH SEE ALSO
.BR ipcs (8)
.SH AUTHOR
krishna balasubramanian (balasub@cis.ohio-state.edu)
