.TH IRQTOP "1" "February 2020" "util-linux" "User Commands"
.SH NAME
lsirq \- utility to display kernel interrupt information
.SH SYNOPSIS
.B lsirq
[options]
.SH DESCRIPTION
Display kernel interrupt counter information.
.PP
The default output is subject to change.  So whenever possible, you should
avoid using default outputs in your scripts.  Always explicitly define
expected columns by using
.BR \-\-output .
.SH OPTIONS
.TP
.BR \-n ", " \-\-noheadings
Don't print headings.
.TP
.BR \-o , " \-\-output " \fIlist\fP
Specify which output columns to print.  Use
.B \-\-help
to get a list of all supported columns.  The default list of columns may be
extended if list is specified in the format
.IR +list .
.TP
.BR \-s , " \-\-sort " \fIcolumn\fP
Specify sort criteria by column name.  See
.B \-\-help
output to get column names.
.TP
.BR \-J ", " \-\-json
Use JSON output format.
.TP
.BR \-P ", " \-\-pairs
Produce output in the form of key="value" pairs.  All potentially unsafe characters
are hex-escaped (\\x<code>).
.TP
.BR \-V ", " \-\-version
Display version information and exit.
.TP
.BR \-h ,\  \-\-help
Display help text and exit.
.SH AUTHORS
.MT pizhenwei@\:bytedance.com
Zhenwei Pi
.ME
.br
.MT kerolasa@\:iki.fi
Sami Kerola
.ME
.br
.MT kzak@\:redhat.com
Karel Zak
.ME
.SH AVAILABILITY
The lsirq command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
