//po4a: entry man manual
= nsenter(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: nsenter

== NAME

nsenter - run program in different namespaces

== SYNOPSIS

*nsenter* [options] [_program_ [_arguments_]]

== DESCRIPTION

The *nsenter* command executes _program_ in the namespace(s) that are specified in the command-line options (described below). If _program_ is not given, then "$\{SHELL}" is run (default: _/bin/sh_).

Enterable namespaces are:

*mount namespace*::
Mounting and unmounting filesystems will not affect the rest of the system, except for filesystems which are explicitly marked as shared (with *mount --make-shared*; see _/proc/self/mountinfo_ for the *shared* flag). For further details, see *mount_namespaces*(7) and the discussion of the *CLONE_NEWNS* flag in *clone*(2).

*UTS namespace*::
Setting hostname or domainname will not affect the rest of the system. For further details, see *uts_namespaces*(7).

*IPC namespace*::
The process will have an independent namespace for POSIX message queues as well as System V message queues, semaphore sets and shared memory segments. For further details, see *ipc_namespaces*(7).

*network namespace*::
The process will have independent IPv4 and IPv6 stacks, IP routing tables, firewall rules, the _/proc/net_ and _/sys/class/net_ directory trees, sockets, etc. For further details, see *network_namespaces*(7).

*PID namespace*::
Children will have a set of PID to process mappings separate from the *nsenter* process. *nsenter* will fork by default if changing the PID namespace, so that the new program and its children share the same PID namespace and are visible to each other. If *--no-fork* is used, the new program will be exec'ed without forking. For further details, see *pid_namespaces*(7).

*user namespace*::
The process will have a distinct set of UIDs, GIDs and capabilities. For further details, see *user_namespaces*(7).

*cgroup namespace*::
The process will have a virtualized view of _/proc/self/cgroup_, and new cgroup mounts will be rooted at the namespace cgroup root. For further details, see *cgroup_namespaces*(7).

*time namespace*::
The process can have a distinct view of *CLOCK_MONOTONIC* and/or *CLOCK_BOOTTIME* which can be changed using _/proc/self/timens_offsets_. For further details, see *time_namespaces*(7).

If you want to create a new namespace, use *unshare*(1). Once created, you can run a program in it using *nsenter*.

== OPTIONS

//TRANSLATORS: Keep {asterisk} untranslated.
Various of the options below that relate to namespaces take an optional _file_ argument. This should be one of the _/proc/[pid]/ns/{asterisk}_ files described in *namespaces*(7), or the pathname of a bind mount that was created on one of those files.

//TRANSLATORS: Keep {asterisk} untranslated.
*-a*, *--all*::
Enter all namespaces of the target process by the default _/proc/<pid>/ns/{asterisk}_
namespace paths. The default paths to the target process namespaces may be overridden
by namespace-specific options (e.g., **--all --mount=**_path_).
+
The user namespace will be ignored if it is the same as the caller's current user namespace. It prevents a caller that has dropped capabilities from regaining those capabilities via a call to *setns*(2). See the man page for more details.

*-t*, *--target* _PID[:inode]_::
Specify a target process to get contexts from. The paths to the contexts specified by _PID_ are:

_/proc/pid/ns/mnt_;;
the mount namespace
_/proc/pid/ns/uts_;;
the UTS namespace
_/proc/pid/ns/ipc_;;
the IPC namespace
_/proc/pid/ns/net_;;
the network namespace
_/proc/pid/ns/pid_;;
the PID namespace
_/proc/pid/ns/user_;;
the user namespace
_/proc/pid/ns/cgroup_;;
the cgroup namespace
_/proc/pid/ns/time_;;
the time namespace
_/proc/pid/root_;;
the root directory
_/proc/pid/cwd_;;
the working directory respectively

Optionally, a process can be addressed with the format _PID:inode_. The _inode_
identifies the unique process's file descriptor. To retrieve a process's inode
number you can use the *getino*(1) utility.

*-m*, *--mount*[**=**<__file__|:__nsid__>]::
Enter the mount namespace. If no argument is specified, enter the mount namespace of the target process. If _file_ or :__nsid__ is specified, enter the mount namespace specified by _file_ or _nsid_.

*-u*, *--uts*[**=**<__file__|:__nsid__>]::
Enter the UTS namespace. If no argument is specified, enter the UTS namespace of the target process. If _file_ or :__nsid__ is specified, enter the UTS namespace specified by _file_ or _nsid_.

*-i*, *--ipc*[**=**<__file__|:__nsid__>]::
Enter the IPC namespace. If no argument is specified, enter the IPC namespace of the target process. If _file_ or :__nsid__ is specified, enter the IPC namespace specified by _file_ or _nsid_.

*-n*, *--net*[**=**<__file__|:__nsid__>]::
Enter the network namespace. If no argument is specified, enter the network namespace of the target process. If _file_ or :__nsid__ is specified, enter the network namespace specified by _file_ or _nsid_.

*-N*, *--net-socket* _fd_::
Enter the network namespace of the target process's socket. It requires *--target* process specified. Supported since Linux 5.6.

*-p*, *--pid*[**=**<__file__|:__nsid__>]::
Enter the PID namespace. If no argument is specified, enter the PID namespace of the target process. If _file_ or :__nsid__ is specified, enter the PID namespace specified by _file_ or _nsid_.

*-U*, *--user*[**=**<__file__|:__nsid__>]::
Enter the user namespace. If no argument is specified, enter the user namespace of the target process. If _file_ or :__nsid__ is specified, enter the user namespace specified by _file_ or _nsid_. See also the *--setuid* and *--setgid* options.

*--user-parent*::
Enter the parent user namespace. Parent user namespace will be acquired from any other enabled namespace.
If combined with *--user* option the parent user namespace will be fetched from the user namespace and replace it.

*-C*, *--cgroup*[**=**<__file__|:__nsid__>]::
Enter the cgroup namespace. If no argument is specified, enter the cgroup namespace of the target process. If _file_ or :__nsid__ is specified, enter the cgroup namespace specified by _file_ or _nsid_.

*-T*, *--time*[**=**<__file__|:__nsid__>]::
Enter the time namespace. If no argument is specified, enter the time namespace of the target process. If _file_ or :__nsid__ is specified, enter the time namespace specified by _file_ or _nsid_.

*-G*, *--setgid* _gid_::
Set the group ID which will be used in the entered namespace and drop supplementary groups.
*nsenter* always sets GID for user namespaces, the default is 0.
If the argument "follow" is specified the GID of the target process is used.

*-S*, *--setuid* _uid_::
Set the user ID which will be used in the entered namespace.
*nsenter* always sets UID for user namespaces, the default is 0.
If the argument "follow" is specified the UID of the target process is used.

*--keep-caps*::
When the *--user* option is given, ensure that capabilities granted in the user namespace are preserved in the child process.

*--preserve-credentials*::
Don't modify UID and GID when entering the user namespace. The default is to drop supplementary groups and set GID and UID to 0.

*-r*, *--root*[**=**_directory_]::
Set the root directory. If no directory is specified, set the root directory to the root directory of the target process. If directory is specified, set the root directory to the specified directory. The specified _directory_ is opened before switching to the requested namespaces.

*-w*, *--wd*[**=**_directory_]::
Set the working directory. If no directory is specified, set the working directory to the working directory of the target process. If directory is specified, set the working directory to the specified directory. The specified _directory_ is opened before switching to the requested namespaces, which means the specified directory works as a "tunnel" to the current namespace. See also *--wdns*.

*-W*, *--wdns*[**=**_directory_]::
Set the working directory. The _directory_ is opened after switching to the requested namespaces and after calling *chroot*(2). The options *--wd* and *--wdns* are mutually exclusive.

*-e*, *--env*::
Pass environment variables from the target process to the new process being created. If this option is not provided, the environment variables will remain the same as in the current namespace.

*-F*, *--no-fork*::
Do not fork before exec'ing the specified program. By default, when entering a PID namespace, *nsenter* calls *fork* before calling *exec* so that any children will also be in the newly entered PID namespace.

*-Z*, *--follow-context*::
Set the SELinux security context used for executing a new process according to the already running process specified by *--target* PID. (The util-linux has to be compiled with SELinux support otherwise the option is unavailable.)

*-c*, *--join-cgroup*::
Add the initiated process to the cgroup of the target process.

include::man-common/help-version.adoc[]

== NOTES

The *--user-parent* option requires Linux 4.9 or higher, older kernels will raise inappropriate ioctl for device error.

Specifying namesapces by _nsid_ requires Linux 6.19 or higher.

== AUTHORS

mailto:biederm@xmission.com[Eric Biederman],
mailto:kzak@redhat.com[Karel Zak]

== SEE ALSO

*unshare*(1),
*lsns*(8),
*clone*(2),
*setns*(2),
*namespaces*(7)
*getino*(1)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
