//po4a: entry man manual
////
Copyright (c) 1983, 1991, 1993
	The Regents of the University of California.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
	This product includes software developed by the University of
	California, Berkeley and its contributors.
4. Neither the name of the University nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

    @(#)renice.8	8.1 (Berkeley) 6/9/93
////
= renice(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: renice

== NAME

renice - alter priority of running processes

== SYNOPSIS

*renice* [*-n*|*--priority*|*--relative*] _priority_ [*-g*|*-p*|*-u*] _identifier_...

== DESCRIPTION

*renice* alters the scheduling priority of one or more running processes. The first argument is the _priority_ value to be used. The other arguments are interpreted as process IDs (by default), process group IDs, user IDs, or user names. *renice*'ing a process group causes all processes in the process group to have their scheduling priority altered. *renice*'ing a user causes all processes owned by the user to have their scheduling priority altered.

By default, _priority_ is understood as an absolute value. But when option *--relative* is given,
or when option *-n* is given and the environment variable POSIXLY_CORRECT is set, then _priority_
is understood as a relative value.

== OPTIONS

*-n* _priority_|__delta__::
Specify the absolute scheduling priority (when POSIXLY_CORRECT is not set) or a relative
priority (when POSIXLY_CORRECT *is* set).  See *NOTES* below for more details.
Using option *-n* is optional, but when used, it must be the first argument.

*--priority* _priority_::
Specify the absolute scheduling _priority_ to be used.
This is the default, when no option is specified.

*--relative* _delta_::
Specify a relative priority. The actual scheduling priority gets incremented/decremented
by the given _delta_. (This is the same as the *-n* option when POSIXLY_CORRECT is set.)

*-g*, *--pgrp*::
Interpret the succeeding arguments as process group IDs.

*-p*, *--pid*::
Interpret the succeeding arguments as process IDs (the default).

*-u*, *--user*::
Interpret the succeeding arguments as usernames or UIDs.

include::man-common/help-version.adoc[]

== FILES

_/etc/passwd_::
to map user names to user IDs

== NOTES

Users other than the superuser may alter the priority only of processes they own.
Furthermore, an unprivileged user can only _increase_ the "nice value" (that is:
lower the urgency), and such changes are irreversible unless (since Linux 2.6.12)
the user has a suitable "nice" resource limit (see *getrlimit*(2)).

The superuser may alter the priority of any process and set the priority to any value in the range -20 to 19. Useful priorities are: 19 (the affected processes will run only when nothing else in the system wants to), 0 (the "base" scheduling priority), anything negative (to make things go very fast).

For historical reasons, the *-n* option in this implementation does not follow the POSIX
specification: instead of setting a *relative* priority, it sets an *absolute* priority
by default. As this may not be desirable, this behavior can be changed by setting the
environment variable POSIXLY_CORRECT, to be fully POSIX compliant. See *--relative* and
*--priority* for options that do not change behavior depending on environment variables.

== HISTORY

The *renice* command appeared in 4.0BSD.

== EXAMPLE

The following command changes the priority of the processes with PIDs 987 and 32, plus all processes owned by the users daemon and root:

____
*renice +1 987 -u daemon root -p 32*
____

== SEE ALSO

*nice*(1),
*chrt*(1),
*getpriority*(2),
*setpriority*(2),
*credentials*(7),
*sched*(7)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
