//po4a: entry man manual
= rfkill(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: rfkill

== NAME

rfkill - tool for enabling and disabling wireless devices

== SYNOPSIS

*rfkill* [options] [_command_] [_ID_|_type_ ...]

== DESCRIPTION

*rfkill* lists, enabling and disabling wireless devices.

The command "list" output format is deprecated and maintained for backward compatibility only. The new output format is the default when no command is specified or when the option *--output* is used.

The default output is subject to change. So whenever possible, you should avoid using default outputs in your scripts. Always explicitly define expected columns by using the *--output* option together with a columns list in environments where a stable output is required.

== OPTIONS

*-J*, *--json*::
Use JSON output format.

*-n*, *--noheadings*::
Do not print a header line.

*-o*, *--output*::
Specify which output columns to print. Use *--help* to get a list of available columns.

*--output-all*::
Output all available columns.

*-r*, *--raw*::
Use the raw output format.

include::man-common/help-version.adoc[]

== COMMANDS

*help*::
Display help text and exit.

*event*::
Listen for rfkill events and display them on stdout.

*list* [__id__|__type__ ...]::
List the current state of all available devices. The command output format is deprecated, see the *DESCRIPTION* section. It is a good idea to check with *list* command _id_ or _type_ scope is appropriate before setting *block* or *unblock*. Special _all_ type string will match everything. Use of multiple _ID_ or _type_ arguments is supported. Possible types are all, {wlan | wifi}, bluetooth, {uwb | ultrawideband}, wimax, wwan, gps, fm, nfc.

**block** __id__|__type__ [...]::
Disable the corresponding device.

**unblock** __id__|__type__ [...]::
Enable the corresponding device. If the device is hard-blocked, for example via a hardware switch, it will remain unavailable though it is now soft-unblocked.

**toggle** __id__|__type__ [...]::
Enable or disable the corresponding device.

== EXAMPLE
....
  rfkill --output ID,TYPE
  rfkill block all
  rfkill unblock wlan
  rfkill block bluetooth uwb wimax wwan gps fm nfc
....

== AUTHORS

*rfkill* was originally written by mailto:johannes@sipsolutions.net[Johannes Berg] and mailto:marcel@holtmann.org[Marcel Holtmann]. The code has been later modified by mailto:kerolasa@iki.fi[Sami Kerola] and mailto:kzak@redhat.com[Karel Zak] for the util-linux project.

This manual page was written by mailto:linux@youmustbejoking.demon.co.uk[Darren Salt] for the Debian project (and may be used by others).

== SEE ALSO

*powertop*(8),
*systemd-rfkill*(8),
https://docs.kernel.org/driver-api/rfkill.html[Linux kernel documentation]

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
