.\" -*- nroff -*-
.TH RFKILL "8" "2017-07-06" "util-linux" "System Administration"
.SH NAME
rfkill \- tool for enabling and disabling wireless devices
.SH SYNOPSIS
.B rfkill
.RI [ options ]
.RI [ command ]
.RI [ id|type \ ...]

.SH DESCRIPTION
.B rfkill
lists, enabling and disabling wireless devices.

The command "list" output format is deprecated and maintained for backward
compatibility only. The new output format is the default when no command is
specified or when the option \fB\-\-output\fR is used.

The default output is subject to change.  So whenever possible, you should
avoid using default outputs in your scripts.  Always explicitly define expected
columns by using the \fB\-\-output\fR option together with a columns list in
environments where a stable output is required.


.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Use JSON output format.
.TP
\fB\-n\fR, \fB\-\-noheadings\fR
Do not print a header line.
.TP
\fB\-o\fR, \fB\-\-output\fR
Specify which output columns to print.  Use \-\-help to get a list of
available columns.
.TP
.B \-\-output\-all
Output all available columns.
.TP
\fB\-r\fR, \fB\-\-raw\fR
Use the raw output format.
.TP
.B \-\-help
Display help text and exit.
.TP
.B \-\-version
Display version information and exit.
.SH COMMANDS
.TP
.B help
Display help text and exit.
.TP
.B event
Listen for rfkill events and display them on stdout.
.TP
\fBlist \fR[\fIid\fR|\fItype\fR ...]
List the current state of all available devices.  The command output format is deprecated, see the section DESCRIPTION.
It is a good idea to check with
.B list
command
.IR id " or " type
scope is appropriate before setting
.BR block " or " unblock .
Special
.I all
type string will match everything.  Use of multiple
.IR id " or " type
arguments is supported.
.TP
\fBblock \fBid\fR|\fBtype\fR [...]
Disable the corresponding device.
.TP
\fBunblock \fBid\fR|\fBtype\fR [...]
Enable the corresponding device.  If the device is hard\-blocked, for example
via a hardware switch, it will remain unavailable though it is now
soft\-unblocked.
.SH EXAMPLE
rfkill --output ID,TYPE
.br
rfkill block all
.br
rfkill unblock wlan
.br
rfkill block bluetooth uwb wimax wwan gps fm nfc
.SH AUTHORS
.B rfkill
was originally written by
.MT johannes@\:sipsolutions.\:net
Johannes Berg
.ME
and
.MT marcel@\:holtmann.\:org
Marcel Holtmann
.ME .
The code has been later modified by
.MT kerolasa@\:iki.\:fi
Sami Kerola
.ME
and
.MT kzak@\:redhat.\:com
Karel Zak
.ME
for util-linux project.
.PP
This manual page was written by
.MT linux@\:youmustbejoking.\:demon.\:co.uk
Darren Salt
.ME ,
for the Debian project (and may be used by others).
.SH SEE ALSO
.BR powertop (8),
.BR systemd-rfkill (8),
.UR https://\:git.\:kernel.\:org/\:pub/\:scm/\:linux/\:kernel/\:git/\:torvalds/\:linux.git/\:tree/\:Documentation/\:driver-api/\:rfkill.rst
Linux kernel documentation
.UE
.SH AVAILABILITY
The rfkill command is part of the util\-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util\-linux/
Linux Kernel Archive
.UE .
