.TH SETARCH 8 "July 2014" "util-linux" "System Administration"
.SH NAME
setarch \- change reported architecture in new program environment and set personality flags
.SH SYNOPSIS
.B setarch
.I arch
[options]
.RI [ program
.RI [ arguments ]]
.sp
.B setarch
.BR \-\-list | \-h | \-V
.SH DESCRIPTION
.B setarch
currently only affects the output of \fBuname -m\fR.
For example, on an AMD64 system, running 'setarch i386 program' will cause 'program' to see
.IR i686
instead of
.IR x86_64
as the machine type.  It also allows to set various personality options.
The default
.B program
is /bin/sh.
.SH OPTIONS
.TP
\fB\-\-list\fR
List the architectures that can be set.
.TP
\fB\-\-uname\-2.6\fR
Causes the program to see a kernel version number beginning with 2.6.
.TP
.BR \-v , " \-\-verbose"
Be verbose.
.TP
\fB\-3\fR, \fB\-\-3gb\fR
Specifies that processes should use a maximum of 3GB of address space on systems where it is supported (ADDR_LIMIT_3GB).
.TP
\fB\-\-4gb\fR
Ignored (for backward compatibility only).
.TP
\fB\-B\fR, \fB\-\-32bit\fR
Turns on ADDR_LIMIT_32BIT.
.TP
\fB\-F\fR, \fB\-\-fdpic\-funcptrs\fR
Userspace function pointers point to descriptors (turns on FDPIC_FUNCPTRS).
.TP
\fB\-I\fR, \fB\-\-short\-inode\fR
Turns on SHORT_INODE.
.TP
\fB\-L\fR, \fB\-\-addr\-compat\-layout\fR
Changes the way virtual memory is allocated (turns on the ADDR_COMPAT_LAYOUT).
.TP
\fB\-R\fR, \fB\-\-addr\-no\-randomize\fR
Disables randomization of the virtual address space (turns on ADDR_NO_RANDOMIZE).
.TP
\fB\-S\fR, \fB\-\-whole\-seconds\fR
Turns on WHOLE_SECONDS.
.TP
\fB\-T\fR, \fB\-\-sticky\-timeouts\fR
Turns on STICKY_TIMEOUTS.
.TP
\fB\-X\fR, \fB\-\-read\-implies\-exec\fR
Turns on READ_IMPLIES_EXEC.
.TP
\fB\-Z\fR, \fB\-\-mmap\-page\-zero\fR
Turns on MMAP_PAGE_ZERO.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH EXAMPLES
setarch ppc32 rpmbuild --target=ppc --rebuild foo.src.rpm
.br
setarch ppc32 -v -vL3 rpmbuild --target=ppc --rebuild bar.src.rpm
.br
setarch ppc32 --32bit rpmbuild --target=ppc --rebuild foo.src.rpm
.SH AUTHOR
.MT sopwith@redhat.com
Elliot Lee
.ME
.br
.MT jnovy@redhat.com
Jindrich Novy
.ME
.SH AVAILABILITY
The setarch command is part of the util-linux package and is available from
.UR ftp://\:ftp.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
