.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.TH SETSID 1 "July 2014" "util-linux" "User Commands"
.SH NAME
setsid \- run a program in a new session
.SH SYNOPSIS
.B setsid
[options]
.I program
.RI [ arguments ]
.SH DESCRIPTION
.B setsid
runs a program in a new session. The command calls
.BR fork (2)
if already a process group leader.  Otherwise, it executes a program in the
current process.  This default behavior is possible to override by
the \fB\-\-fork\fR option.
.SH OPTIONS
.TP
.BR \-c , " \-\-ctty"
Set the controlling terminal to the current one.
.TP
.BR \-f , " \-\-fork"
Always create a new process.
.TP
.BR \-w , " \-\-wait"
Wait for the execution of the program to end, and return the exit value of
this program as the return value of
.BR setsid .
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH "SEE ALSO"
.BR setsid (2)
.SH AUTHOR
Rick Sladkey <jrs@world.std.com>
.SH AVAILABILITY
The setsid command is part of the util-linux package and is available from
https://www.kernel.org/pub/linux/utils/util-linux/.
