.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Path modifications by faith@cs.unc.edu
.TH SETSID 1 "November 1993" "util-linux" "User Commands"
.SH NAME
setsid \- run a program in a new session
.SH SYNOPSIS
.B setsid
.I program
.RI [ arg ...]
.SH DESCRIPTION
.B setsid
runs a program in a new session.
.SH OPTIONS
.TP
\fB\-c\fP, \fB\-\-ctty\fP
Set the controlling terminal to the current one.
.TP
\fB\-w\fP, \fB\-\-wait\fP
Wait the execution of the program to end, and return the exit value of
the child as return value of the
.BR setsid .
.SH "SEE ALSO"
.BR setsid (2)
.SH AUTHOR
Rick Sladkey <jrs@world.std.com>
.SH AVAILABILITY
The setsid command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
