.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Path modifications by faith@cs.unc.edu
.TH SETSID 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
setsid \- run a program in a new session
.SH SYNOPSIS
.BI setsid " program" " [ " "arg ..." " ]"
.SH DESCRIPTION
.B setsid
runs a program in a new session.
.SH "SEE ALSO"
.BR setsid (2)
.SH AUTHOR
Rick Sladkey <jrs@world.std.com>
