.\" wdctl.8 --
.\" Copyright (C) 2012 Karel Zak <kzak@redhat.com>
.\" May be distributed under the GNU General Public License
.TH WDCTL "8" "July 2014" "util-linux" "System Administration"
.SH NAME
wdctl \- show hardware watchdog status
.SH SYNOPSIS
.B wdctl
[options]
.RI [ device ...]
.SH DESCRIPTION
Show hardware watchdog status.  The default device is
.IR /dev/watchdog .
If more than one device is specified then the output is separated by
one blank line.
.PP
Note that the number of supported watchdog features is hardware specific.
.SH OPTIONS
.TP
.BR \-f , " \-\-flags " \fIlist
Print only the specified flags.
.TP
.BR \-F , " \-\-noflags"
Do not print information about flags.
.TP
.BR \-I , " \-\-noident"
Do not print watchdog identity information.
.TP
.BR \-n , " \-\-noheadings"
Do not print a header line for flags table.
.IP "\fB\-o\fR, \fB\-\-output \fIlist\fP"
Define the output columns to use in table of watchdog flags.  If no
output arrangement is specified, then a default set is used.  Use
.B \-\-help
to get list of all supported columns.
.TP
.BR \-O , " \-\-oneline"
Print all wanted information on one line in key="value" output format.
.TP
.BR \-r , " \-\-raw"
Use the raw output format.
.TP
.BR \-s , " \-settimeout " \fIseconds
Set the watchdog timeout in seconds.
.TP
.BR \-T , " \-\-notimeouts"
Do not print watchdog timeouts.
.IP "\fB\-x\fR, \fB\-\-flags\-only\fP"
Same as \fB\-I \-T\fP.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH AUTHORS
.MT kzak@\:redhat\:.com
Karel Zak
.ME
.br
.MT lennart@\:poettering\:.net
Lennart Poettering
.ME
.SH AVAILABILITY
The
.B wdctl
command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
