.\" wdctl.8 --
.\" Copyright (C) 2012 Karel Zak <kzak@redhat.com>
.\" May be distributed under the GNU General Public License

.TH WDCTL 8 "May 2012" "util-linux" "System Administration"
.SH NAME
wdctl \-
show hardware watchdog status
.SH SYNOPSIS
.B wdctl
.RB [options]

.SH DESCRIPTION
Show hardware watchdog status. Note that number of supported watchdog
features is hardware specific.

.SH OPTIONS
.IP "\fB\-d, \-\-device \fIpath\fP"
Device to use, default is /dev/watchdog.
.IP "\fB\-f, \-\-flags \fI<list>\fP"
Print selected flags only.
.IP "\fB\-F, \-\-noflags\fP"
Don't print information about flags
.IP "\fB\-n, \-\-noheadings\fP"
Do not print a header line.
.IP "\fB\-I, \-\-noident\fP"
Don't print watchdog identity information
.IP "\fB\-T, \-\-notimeouts\fP"
Don't print watchdog timeouts
.IP "\fB\-o, \-\-output \fIlist\fP"
Define the output columns to use in table of watchdog flags. If no output
arrangement is specified, then a default set is used.  Use \fB\-\-help\fP to
get list of all supported columns.
.IP "\fB\-P, \-\-pairs\fP"
Use key="value" output format.
.IP "\fB\-V, \-\-version\fP"
Output version information and exit.
.IP "\fB\-r, \-\-raw\fP"
Use the raw output format.
.IP "\fB\-x, \-\-flags-only\fP"
Same as \fB\-I \-T\fP.
.IP "\fB\-h, \-\-help\fP"
Print a help text and exit.

.SH AUTHORS
.nf
Karel Zak <kzak@redhat.com>
Lennart Poettering <lennart@poettering.net>
.fi
.SH AVAILABILITY
The wdctl command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
