#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="by devname"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MKSWAP"
ts_check_test_command "$TS_CMD_SWAPON"
ts_check_test_command "$TS_CMD_SWAPOFF"

ts_skip_nonroot
ts_check_losetup

ts_device_init
DEVICE=$TS_LODEV

$TS_CMD_MKSWAP $DEVICE > /dev/null 2>> $TS_OUTPUT \
 || ts_die "Cannot make swap $DEVICE"

ts_device_has "TYPE" "swap" $DEVICE || ts_die "Cannot find swap on $DEVICE"

$TS_CMD_SWAPON $DEVICE >> $TS_OUTPUT 2>&1

grep -q "^$DEVICE\b" /proc/swaps || ts_die "Cannot find $DEVICE in /proc/swaps"

$TS_CMD_SWAPOFF $DEVICE

# swapon/mkswap warns if system sets different permissions for loop devices
sed --in-place '/insecure permissions .*, 0660 suggested/d' $TS_OUTPUT

ts_log "Success"
ts_finalize

