#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="fix signature"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MKSWAP"
ts_check_test_command "$TS_CMD_SWAPON"
ts_check_test_command "$TS_CMD_SWAPOFF"
ts_check_test_command "$TS_HELPER_SYSINFO"

ts_skip_nonroot
ts_check_losetup

PAGESIZE=$($TS_HELPER_SYSINFO pagesize)

#
# Create a swap-area
#
ts_device_init
DEVICE=$TS_LODEV

$TS_CMD_MKSWAP $DEVICE > /dev/null 2>> $TS_OUTPUT \
 || ts_die "Cannot make swap $DEVICE"

ts_device_has "TYPE" "swap" $DEVICE || ts_die "Cannot find swap on $DEVICE"

#
# Rewrite signature to swsuspend
#
echo "S2SUSPEND " > $TS_OUTPUT.signature
dd if=$TS_OUTPUT.signature of=$DEVICE \
	seek=$(( $PAGESIZE - 10 )) count=10 bs=1 conv=notrunc &> /dev/null

ts_device_has "TYPE" "swsuspend" $DEVICE || ts_die "Cannot find swsuspend on $DEVICE"

#
# Swapon
#
$TS_CMD_SWAPON $DEVICE &> /dev/null

grep -q "^$DEVICE\b" /proc/swaps || ts_die "Cannot find $DEVICE in /proc/swaps"

$TS_CMD_SWAPOFF $DEVICE

# swapon/mkswap warns if system sets different permissions for loop devices
sed --in-place '/insecure permissions .*, 0660 suggested/d' $TS_OUTPUT

ts_log "Success"
ts_finalize

