#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="by label"
LABEL="testSwapLabel"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MKSWAP"
ts_check_test_command "$TS_CMD_SWAPON"
ts_check_test_command "$TS_CMD_SWAPOFF"

ts_skip_nonroot
ts_check_losetup

set -o pipefail

DEVICE=$(ts_device_init)
[ "$?" == 0 ] || ts_die "Cannot init device"

$TS_CMD_MKSWAP -L $LABEL $DEVICE > /dev/null 2>> $TS_OUTPUT \
 || ts_die "Cannot make swap on $DEVICE" $DEVICE

ts_device_has "LABEL" $LABEL $DEVICE \
 || ts_die "Cannot find LABEL '$LABEL' on $DEVICE" $DEVICE

$TS_CMD_SWAPON -L $LABEL 2>&1 >> $TS_OUTPUT

grep -q $DEVICE /proc/swaps || ts_die "Cannot find $DEVICE in /proc/swaps" $DEVICE

$TS_CMD_SWAPOFF $DEVICE
ts_device_deinit $DEVICE

ts_log "Success"
ts_finalize

