#!/bin/bash

#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="regressions"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_COLCRT"
ts_check_prog "timeout"
ts_check_prog "env"

check_input_file() {
	ts_init_subtest ${1##*/}
	timeout 2 env LC_ALL=C.UTF-8 $TS_CMD_COLCRT < $1 >> $TS_OUTPUT 2>> $TS_ERRLOG
	echo "return value: $?" >> $TS_OUTPUT
	ts_finalize_subtest
}

check_input_file "$TS_SELF/crash1"
check_input_file "$TS_SELF/crash2"
check_input_file "$TS_SELF/hang1"

ts_finalize
