.\"
.\"  chsh.1 -- change your login shell
.\"  (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\"  This program is free software.  You can redistribute it and
.\"  modify it under the terms of the GNU General Public License.
.\"  There is no warranty.
.\"
.TH CHSH 1 "July 2014" "util-linux" "User Commands"
.SH NAME
chsh \- change your login shell
.SH SYNOPSIS
.B chsh
.RB [ \-s
.IR shell ]
.RB [ \-l ]
.RB [ \-h ]
.RB [ \-v ]
.RI [ username ]
.SH DESCRIPTION
.B chsh
is used to change your login shell.
If a shell is not given on the command line,
.B chsh
prompts for one.

.B chsh
supports non-local entries (kerberos, LDAP, etc.\&) if linked with libuser,
otherwise use \fBypchsh\fR, \fBlchsh\fR or any other implementation for
non-local entries.
.SH OPTIONS
.TP
.BR \-s , " \-\-shell " \fIshell
Specify your login shell.
.TP
.BR \-l , " \-\-list\-shells"
Print the list of shells listed in
.I /etc/shells
and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.TP
.BR \-v , " \-\-version"
Display version information and exit.
.SH VALID SHELLS
.B chsh
will accept the full pathname of any executable file on the system.
.sp
The default behavior for non-root users is to accept only shells
listed in the
.I /etc/shells
file, and issue a warning for root user.  It can also be configured
at compile-time to only issue a warning for all users.

.SH EXIT STATUS
Returns 0 if operation was successful, 1 if operation failed or command syntax was not valid.
.SH AUTHORS
Salvatore Valente <svalente@mit.edu>
.SH SEE ALSO
.BR login (1),
.BR login.defs (5),
.BR passwd (5),
.BR shells (5)
.SH AVAILABILITY
The chsh command is part of the util-linux package and is available from
https://www.kernel.org/pub/linux/utils/util-linux/.
