.TH NOLOGIN 8 "September 2013" "util-linux" "System Administration"
.SH NAME
nologin \- politely refuse a login
.SH SYNOPSIS
.B nologin
.RB [ \-V ]
.RB [ \-h ]
.SH DESCRIPTION
.B nologin
displays a message that an account is not available and exits non-zero.  It is
intended as a replacement shell field to deny login access to an account.
.PP
If the file /etc/nologin.txt exists, nologin displays its contents to the
user instead of the default message.
.PP
The exit code returned by
.B nologin
is always 1.
.PP
.SH OPTIONS
.IP "\fB\-h, \-\-help\fP"
Display help text and exit.
.IP "\fB-V, \-\-version"
Display version information and exit.
.SH NOTES
.B nologin
is a per-account way to disable login (usually used for system accounts like http or ftp).
.BR nologin (8)
uses /etc/nologin.txt as an optional source for a non-default message, the login
access is always refused independently of the file.
.PP
.BR pam_nologin (8)
PAM module usually prevents all non-root users from logging into the system.
.BR pam_nologin (8)
functionality is controlled by /var/run/nologin or the /etc/nologin file.
.SH AUTHORS
.UR kzak@redhat.com
Karel Zak
.UE
.SH SEE ALSO
.BR login (1),
.BR passwd (5),
.BR pam_nologin (8)
.SH HISTORY
The
.B nologin
command appeared in 4.4BSD.
.SH AVAILABILITY
The nologin command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
