.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH PASSWD 1 "22 June 1994" "Linux 1.2" "Linux Programmer's Manual"
.SH NAME
passwd \- change password
.SH SYNOPSIS
.BR "passwd [ " name " [ " password " ] ]"
.SH DESCRIPTION
Without arguments
.B passwd
will change the password for the current user. First the user is asked for
the old password, then prompted twice for the new password in order to
catch typing errors. The new password must be at least six characters long,
and have both upper and lower case letters or non-letters. The new password
must not be equal to the old password, and it must not match the username.

The one and two argument forms may only be used by the superuser. Using the
one argument form, the superuser may change the password for that user.
The superuser is not asked for the users old password, and the rules 
for proper passwords are not applied since the superuser may have legitimate
reasons to choose a non-conformant password.

The two argument form gives the 
.I user
the password stated as the second argument. This may be useful when
giving many users an initial generated password.

Giving an empty string as the second argument erases the password for the
user.

.SH FILES
.I /etc/passwd
.br
.I /etc/shells
.SH "SEE ALSO"
.BR chsh (1),
.BR chfn (1)
.SH BUGS
A password consisting of all digits is allowed.
.br
No warnings are printed if the superuser chooses a poor password.
.br
The
.B \-f
and
.B \-s
options are not supported.
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
