//po4a: entry man manual
////
Copyright (C) 2010 Michael Krapp

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
////
= utmpdump(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: utmpdump

== NAME

utmpdump - dump UTMP and WTMP files in raw format

== SYNOPSIS

*utmpdump* [options] _filename_

== DESCRIPTION

*utmpdump* is a simple program to dump UTMP and WTMP files in raw format, so they can be examined. *utmpdump* reads from stdin unless a _filename_ is passed.

== OPTIONS

*-f*, *--follow*::
Output appended data as the file grows.

*-o*, *--output* _file_::
Write command output to _file_ instead of standard output.

*-r*, *--reverse*::
Undump, write back edited login information into the utmp or wtmp files.

include::man-common/help-version.adoc[]

== NOTES

*utmpdump* can be useful in cases of corrupted utmp or wtmp entries. It can dump out utmp/wtmp to an ASCII file, which can then be edited to remove bogus entries, and reintegrated using:

____
*utmpdump -r < ascii_file > wtmp*
____

But be warned, *utmpdump* was written for debugging purposes only.

=== File formats

Only the binary version of the *utmp*(5) is standardised. Textual dumps may become incompatible in future.

The version 2.28 was the last one that printed text output using *ctime*(3) timestamp format. Newer dumps use millisecond precision ISO-8601 timestamp format in UTC-0 timezone. Conversion from former timestamp format can be made to binary, although attempt to do so can lead the timestamps to drift amount of timezone offset.

== BUGS

You may *not* use the *-r* option, as the format for the utmp/wtmp files strongly depends on the input format. This tool was *not* written for normal use, but for debugging only.

== AUTHORS

Michael Krapp

== SEE ALSO

*last*(1),
*w*(1),
*who*(1),
*utmp*(5)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
