#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux-ng.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
. ./commands.sh
. ./functions.sh

TS_COMPONENT="mount"
TS_DESC="uuid"

ts_init "$*"
ts_skip_nonroot

set -o pipefail

DEVICE=$(ts_device_init)
[ "$?" == 0 ] || ts_die "Cannot init device"

mkfs.ext3 $DEVICE &> /dev/null
[ "$?" == "0" ] || ts_die "Cannot make ext3 on $DEVICE" $DEVICE

ts_device_has_uuid $DEVICE
[ "$?" == "0" ] || ts_die "Cannot found UUID on $DEVICE" $DEVICE

UUID=$(ts_uuid_by_devname $DEVICE)

ts_udev_dev_support "by-uuid" $UUID
[ "$?" == "0" ] || ts_skip "udev ignores /dev/loop*" $DEVICE

[ -d "$TS_MOUNTPOINT" ] || mkdir -p $TS_MOUNTPOINT

# variant A)
$TS_CMD_MOUNT -U $UUID $TS_MOUNTPOINT 2>&1 >> $TS_OUTPUT
grep -q $DEVICE /proc/mounts
[ "$?" == "0" ] || ts_die "A) Cannot found $DEVICE in /proc/mounts" $DEVICE
$TS_CMD_UMOUNT $DEVICE
[ "$?" == "0" ] || ts_die "A) Cannot umount $DEVICE" $DEVICE

# variant B)
$TS_CMD_MOUNT UUID=$UUID $TS_MOUNTPOINT 2>&1 >> $TS_OUTPUT
grep -q $DEVICE /proc/mounts
[ "$?" == "0" ] || ts_die "B) Cannot found $DEVICE in /proc/mounts" $DEVICE
$TS_CMD_UMOUNT $DEVICE
[ "$?" == "0" ] || ts_die "B) Cannot umount $DEVICE" $DEVICE

ts_device_deinit $DEVICE

ts_log "Success"
ts_finalize

