#!/bin/bash

#
# test for mount --move and --bind
#

. commands.sh
. functions.sh

TS_COMPONENT="mount"
TS_DESC="move "

ts_init
ts_skip_nonroot

touch $TS_OUTPUT

PWD=$(pwd)

DIR_SRC="$PWD/$TS_OUTDIR/mnt-move-src"
DIR_A="$PWD/$TS_OUTDIR/mnt-move-A"
DIR_B="$PWD/$TS_OUTDIR/mnt-move-B"

mkdir $DIR_SRC $DIR_A $DIR_B

# bind
$TS_CMD_MOUNT --bind $DIR_SRC $DIR_A

# check the bind
egrep -q "^$DIR_SRC $DIR_A" /etc/mtab

if [ "$?" != "0" ]; then
        echo "Cannot found binded $DIR_SRC in /etc/mtab" >> $TS_OUTPUT
	rmdir $DIR_SRC $DIR_A $DIR_B
        ts_finalize
fi

# move
$TS_CMD_MOUNT --move $DIR_A $DIR_B

# check the move
egrep -q "^$DIR_SRC $DIR_B" /etc/mtab

if [ "$?" != "0" ]; then
        echo "Cannot found moved $DIR_SRC in /etc/mtab" >> $TS_OUTPUT
	$TS_CMD_UMOUNT $DIR_SRC
	rmdir $DIR_SRC $DIR_A $DIR_B
        ts_finalize
fi

# clean up
$TS_CMD_UMOUNT $DIR_SRC
rmdir $DIR_SRC $DIR_A $DIR_B

echo "Success" >> $TS_OUTPUT

ts_finalize

