#!/bin/bash

#
# test for /sbin/mount.<type> suuport
#

. commands.sh
. functions.sh

TS_COMPONENT="mount"
TS_DESC="special program"

MOUNTER="/sbin/mount.mytest"

ts_init "$*"
ts_skip_nonroot

cat > $MOUNTER << EOF
#!/bin/bash
# This util-linux-ng regression test component
# It's safe to remove me...
#
echo "\$0 called with \"\$*\""
EOF
chmod +x $MOUNTER

$TS_CMD_MOUNT -v -v -v -t mytest  /foo /bar &> $TS_OUTPUT

rm -f $MOUNTER

ts_finalize

