#!/bin/bash

#
# test for mount -o remount,ro
#
. commands.sh
. functions.sh

TS_COMPONENT="mount"
TS_DESC="remount"

ts_init
ts_skip_nonroot

# mountpoint
MOUNTPOINT="$(pwd)/$TS_OUTDIR/mnt-remount"
mkdir -p $MOUNTPOINT

DEVICE=$(ts_device_init)
[ "$?" == 0 ] || ts_die "Cannot init device"

mkfs.ext2 $DEVICE &> /dev/null
[ "$?" == "0" ] || ts_die "Cannot make ext2 on $DEVICE" $DEVICE

# mount read-write
$TS_CMD_MOUNT $DEVICE $MOUNTPOINT
[ "$?" == "0" ] || ts_die "Cannot mount $MOUNTPOINT" $DEVICE

# check the mount
egrep -q "^$DEVICE $MOUNTPOINT" /etc/mtab
[ "$?" == "0" ] || ts_die "Cannot found $MOUNTPOINT in /etc/mtab" $DEVICE

# remount
$TS_CMD_MOUNT -o remount,ro $MOUNTPOINT
[ "$?" == "0" ] || ts_die "Cannot remount $MOUNTPOINT" $DEVICE

# check the remount
egrep -q "^$DEVICE $MOUNTPOINT ext2 ro 0 0" /etc/mtab
[ "$?" == "0" ] || ts_die "Cannot found remounted $MOUNTPOINT in /etc/mtab" $DEVICE

ts_device_deinit $DEVICE

echo "Success" >> $TS_OUTPUT
ts_finalize

