#!/bin/bash

# 
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
# 
# This file is part of util-linux-ng.
# 
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

# Test swap device initialization and usage

. commands.sh
. functions.sh

TS_COMPONENT="mkswap"
TS_DESC="doit"

ts_init
ts_skip_nonroot

set -o pipefail

touch $TS_OUTPUT

LABEL="testSwap"

ldd $TS_CMD_SWAPON | grep -q 'libvolume_id' 2>&1 >> $TS_OUTPUT
if [ "$?" == "0" ]; then
	HAS_VOLUMEID="yes"
fi

ts_device_init || ts_finalize
$TS_CMD_MKSWAP -L $LABEL $DEVICE 2>&1 >> $TS_OUTPUT

# check it
if [ "$($TS_CMD_MOUNT --guess-fstype $DEVICE)" != "swap" ]; then
	echo "Cannot found Linux swap on $DEVICE" >> $TS_OUTPUT
	ts_device_deinit
	ts_finalize
fi

if [ -n "$HAS_VOLUMEID" ] && [ ! -L "/dev/disk/by-label/$LABEL" ]; then
	ts_device_deinit
	ts_skip "udev ignores /dev/loop*"
fi

# try connect it to system (and found the device by label)
$TS_CMD_SWAPON -L $LABEL 2>&1 >> $TS_OUTPUT

# check it
grep -q $DEVICE /proc/swaps

if [ "$?" != "0" ]; then
	echo "Cannot found $DEVICE in /proc/swaps" >> $TS_OUTPUT
	ts_device_deinit
	ts_finalize
fi

# swapoff doesn't exist in build tree
if [ ! -x "$TS_CMD_SWAPOFF" ]; then
	ln -sf $TS_CMD_SWAPON $TS_CMD_SWAPOFF
	REMSWAPOFF="true"
fi
$TS_CMD_SWAPOFF $DEVICE 2>&1 >> $TS_OUTPUT
ts_device_deinit

if [ -n "$REMSWAPOFF" ]; then
	rm -f $TS_CMD_SWAPOFF
fi

ts_finalize

