#!/bin/bash

#
# test for mount -o remount,ro
#

. commands.sh
. functions.sh

TS_COMPONENT="mount"
TS_DESC="remount"

ts_init
ts_skip_nonroot

touch $TS_OUTPUT

# mountpoint
MOUNTPOINT="$(pwd)/$TS_OUTDIR/mnt-remount"
mkdir -p $MOUNTPOINT

ts_device_init || ts_finalize
mkfs.ext2 $DEVICE &> /dev/null

# mount read-write
$TS_CMD_MOUNT $DEVICE $MOUNTPOINT

# check the mount
egrep -q "^$DEVICE $MOUNTPOINT" /etc/mtab

if [ "$?" != "0" ]; then
        echo "Cannot found $MOUNTPOINT in /etc/mtab" >> $TS_OUTPUT
	ts_device_deinit
        ts_finalize
fi

# remount
$TS_CMD_MOUNT -o remount,ro $MOUNTPOINT

# check the remount
egrep -q "^$DEVICE $MOUNTPOINT ext2 ro 0 0" /etc/mtab

if [ "$?" != "0" ]; then
        echo "Cannot found remounted $MOUNTPOINT in /etc/mtab" >> $TS_OUTPUT
        ts_device_deinit
	ts_finalize
fi

ts_device_deinit

echo "Success" >> $TS_OUTPUT
ts_finalize

