#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

#
# WARNING: the look command expects that the /usr/share/dict/words uses
#          directory order!
#
# for example:
#
#	cat words.raw | grep -E --invert-match "'s$" | \
#		grep -E "^[[:alnum:]'&!,./-]+$" | \
#		sort --ignore-case --dictionary-order | \
#		uniq >  words
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="separator"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LOOK"

$TS_CMD_LOOK apple-pie $TS_TOPDIR/ts/look/words >> $TS_OUTPUT
ts_finalize

