#!/bin/bash

# Copyright (C) 2023 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="Documentation/boilerplate"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_BOILERPLATE"

ts_init_subtest exec

"$TS_HELPER_BOILERPLATE" >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
echo "ret=$?" >> "$TS_OUTPUT"

ts_finalize_subtest

ts_init_subtest help

"$TS_HELPER_BOILERPLATE" --help >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
echo "ret=$?" >> "$TS_OUTPUT"

ts_finalize_subtest

ts_finalize
