#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="fallocate"

. $TS_TOPDIR/functions.sh
ts_init "$*"

IMAGE=${TS_OUTDIR}/${TS_TESTNAME}.file
rm -f $IMAGE

$TS_CMD_FALLOCATE -o 128 -l 256 $IMAGE > $TS_OUTPUT 2>&1
stat -c "%s" $IMAGE > $TS_OUTPUT 2>&1

rm -f $IMAGE

ts_finalize
