#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="mountpoint"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MOUNTPOINT"

ln -s / ./symlink-to-root

echo "default" >> $TS_OUTPUT 2>&1
$TS_CMD_MOUNTPOINT ./symlink-to-root >> $TS_OUTPUT 2>&1
echo $? >> $TS_OUTPUT 2>&1

echo "try --nofollow" >> $TS_OUTPUT 2>&1
$TS_CMD_MOUNTPOINT --nofollow ./symlink-to-root >> $TS_OUTPUT 2>&1
echo $? >> $TS_OUTPUT 2>&1

echo "mutually exclusive" >> $TS_OUTPUT 2>&1
$TS_CMD_MOUNTPOINT --devno --nofollow / >> $TS_OUTPUT 2>&1
echo $? >> $TS_OUTPUT 2>&1

rm -f ./symlink-to-root

ts_finalize
