#!/usr/bin/env bash

#
# Copyright (C) 2026 Aditya Dutt <duttaditya18@gmail.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="path-is-within"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_STRUTILS"

function ts_within {
	$TS_HELPER_STRUTILS --path-is-within "$1" "$2" \
		>> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
}

ts_log "same path"
ts_within /foo/bar /foo/bar
ts_within / /

ts_log "path below dir"
ts_within /foo/bar/baz /foo/bar
ts_within /foo/bar/baz/xxx /foo/bar
ts_within /foo/bar /

ts_log "path above dir"
ts_within /foo /foo/bar
ts_within / /foo

ts_log "common prefix is not enough"
ts_within /foo/barX /foo/bar
ts_within /foo/bar /foo/barX
ts_within /foobar /foo

ts_log "redundant and trailing slashes"
ts_within /foo//bar /foo/bar
ts_within /foo/bar/ /foo/bar
ts_within /foo/bar///baz /foo/bar
ts_within /foo/bar /foo//bar
ts_within /foo/bar /foo/bar/
ts_within /foo/bar/baz //foo///bar//

ts_log "relative paths"
ts_within foo/bar foo
ts_within foo/bar /foo
ts_within /foo/bar foo

ts_log "empty paths"
ts_within "" /foo
ts_within /foo ""
ts_within "" ""

ts_finalize
