#!/bin/bash

# Copyright (C) 2023 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="time_t size"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_SYSINFO"
[ -n "$UL_ALLOW_32BIT_TIME" ] && ts_skip "32bit time allowed"

"$TS_HELPER_SYSINFO" 'sz(time_t)' >> "$TS_OUTPUT"

ts_finalize
