#!/bin/bash

#
# Copyright (C) 2009 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="caching"

. "$TS_TOPDIR"/functions.sh

ts_init "$*"

ts_skip_nonroot
ts_check_test_command "$TS_CMD_BLKID"
ts_check_test_command "$TS_CMD_MKSWAP"
ts_check_losetup

ts_device_init

"$TS_CMD_MKSWAP" -q -p 4096 -e little \
	-U 11111111-1111-1111-1111-111111111111 \
	"$TS_LODEV" \
	>> "$TS_OUTPUT" 2>> "$TS_ERRLOG"

"$TS_CMD_BLKID" "$TS_LODEV" \
	| sed -e "s|$TS_LODEV|DEVICE|" \
	>> "$TS_OUTPUT" 2>> "$TS_ERRLOG"

cat "$BLKID_FILE" \
	| sed -e 's/DEVNO="[^"]*"/DEVNO=""/' \
	      -e 's/TIME="[^"]*"/TIME=""/' \
	      -e "s|$TS_LODEV|DEVICE|" \
	>> "$TS_OUTPUT"

ts_finalize
