#!/bin/bash

#
# Copyright (C) 2015 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="mbr-wholedisk"

. $TS_TOPDIR/functions.sh

ts_init "$*"

ts_check_test_command "$TS_CMD_BLKID"

ts_skip_nonroot

# set global variable TS_DEVICE
ts_scsi_debug_init dev_size_mb=50

#
# This looks like VFAT, but it's MBR
#
ts_init_subtest "fake-vfat"
dd if=${TS_SELF}/mbr-wholedisk-vfat.img of=${TS_DEVICE} &> /dev/null
udevadm settle
$TS_CMD_BLKID -p -o udev ${TS_DEVICE} >> $TS_OUTPUT
ts_finalize_subtest

ts_finalize
