#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="offset"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_SFDISK"
ts_check_test_command "$TS_CMD_BLKID"
ts_check_test_command "$TS_CMD_PARTX"

ts_check_prog "mkfs.ext2"
ts_skip_nonroot

# set global variable TS_DEVICE
ts_scsi_debug_init dev_size_mb=50 sector_size=512

$TS_CMD_SFDISK ${TS_DEVICE} >> $TS_OUTPUT 2>> $TS_ERRLOG <<EOF
label: gpt
label-id: b181c399-4711-4c52-8b65-9e764541218d

,5M,L
,5M,L
,5M,L
, ,
EOF
ts_fdisk_clean $TS_DEVICE
udevadm settle


mkfs.ext2 -b 4096 -L FOO -U ccf3dc28-f697-4577-971b-0bc79300a700 ${TS_DEVICE}2 &> /dev/null
udevadm settle
ts_device_has "TYPE" "ext2" ${TS_DEVICE}2 ||
		ts_die "Cannot find ext2 on ${TS_DEVICE}2"

DEVNAME=$(basename $TS_DEVICE)
offset=$(( $(cat /sys/block/${DEVNAME}/${DEVNAME}2/start) * 512))
size=$(( $(cat /sys/block/${DEVNAME}/${DEVNAME}2/size) * 512))

$TS_CMD_PARTX --delete ${TS_DEVICE} &> /dev/null

$TS_CMD_BLKID -p -o udev --offset=${offset} --size=${size} $TS_DEVICE \
		>> $TS_OUTPUT 2>> $TS_ERRLOG

ts_finalize
