#!/bin/bash

#
# Copyright (C) 2022 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="topology probing"

. "$TS_TOPDIR"/functions.sh

ts_init "$*"

ts_skip_nonroot
ts_check_losetup
ts_check_test_command "$TS_CMD_BLKID"
ts_check_test_command "$TS_CMD_SFDISK"

ts_device_init


ts_init_subtest disk
echo -e 'label: dos\n- - - -' | "$TS_CMD_SFDISK" -q "$TS_LODEV"

"$TS_CMD_BLKID" -i -o udev "$TS_LODEV" \
	2> "$TS_ERRLOG" \
	| sed -E -e 's/^ID_FS_DISKSEQ=[[:digit:]]+$/ID_FS_DISKSEQ=S/' \
	| sort > "$TS_OUTPUT"

ts_finalize_subtest


ts_init_subtest partition

"$TS_CMD_BLKID" -i -o udev "$TS_LODEV"p1 \
	2> "$TS_ERRLOG" \
	| sed -E -e 's/^ID_FS_DISKSEQ=[[:digit:]]+$/ID_FS_DISKSEQ=S/' \
	| sort > "$TS_OUTPUT"

ts_finalize_subtest

ts_finalize
