#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2026 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="usages"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_BLKID"
ts_check_prog "xz"

FS_IMG_DIR="$TS_SELF/images-fs"
REG_FS_IMG="$TS_OUTDIR/usages-reg-fs.img"
SWAP_IMG="$TS_OUTDIR/usages-swap.img"
CRYPTO_IMG="$TS_OUTDIR/usages-crypto.img"
RAID_IMG="$TS_OUTDIR/usages-raid.img"

xz --decompress --stdout "$FS_IMG_DIR"/ext4.img.xz > "$REG_FS_IMG" 2>>"$TS_ERRLOG"
xz --decompress --stdout "$FS_IMG_DIR"/swap0.img.xz > "$SWAP_IMG" 2>>"$TS_ERRLOG"
xz --decompress --stdout "$FS_IMG_DIR"/luks2.img.xz > "$CRYPTO_IMG" 2>>"$TS_ERRLOG"
xz --decompress --stdout "$FS_IMG_DIR"/mdraid.img.xz > "$RAID_IMG" 2>>"$TS_ERRLOG"

# Regular filesystem image
ts_init_subtest "filesystem"
$TS_CMD_BLKID --probe --usages filesystem "$REG_FS_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
sed -i -e "s@$REG_FS_IMG@<removed>@" "$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest

ts_init_subtest "nofilesystem"
$TS_CMD_BLKID --probe --usages nofilesystem "$REG_FS_IMG" \
						>>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


# Swap image
ts_init_subtest "other"
$TS_CMD_BLKID --probe --usages other "$SWAP_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
sed -i -e "s@$SWAP_IMG@<removed>@" "$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest

ts_init_subtest "noother"
$TS_CMD_BLKID --probe --usages noother "$SWAP_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


# Crypto image
ts_init_subtest "crypto"
$TS_CMD_BLKID --probe --usages crypto "$CRYPTO_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
sed -i -e "s@$CRYPTO_IMG@<removed>@" "$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest

ts_init_subtest "nocrypto"
$TS_CMD_BLKID --probe --usages nocrypto "$CRYPTO_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


# RAID image
ts_init_subtest "raid"
$TS_CMD_BLKID --probe --usages raid "$RAID_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
sed -i -e "s@$RAID_IMG@<removed>@" "$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest

ts_init_subtest "noraid"
$TS_CMD_BLKID --probe --usages noraid "$RAID_IMG" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest

ts_finalize
