#!/bin/bash

#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

#
# Test default 1MiB (2048 sectors) alignment for 512/512 disk *without*
# topology.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="align 512/512"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_FDISK"

ts_skip_nonroot
ts_check_losetup

ts_device_init 50
DEVICE=$TS_LODEV

ts_log "Create partitions"
$TS_CMD_FDISK ${DEVICE} >> $TS_OUTPUT 2>&1 <<EOF
n
p
1

+10M
n
p
2

+10M
n
p
3

+10M
n
e


n

+5M
n

+5M
n


p
q
EOF

ts_fdisk_clean $DEVICE

ts_finalize
