#!/bin/bash

#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#


#
# Test alignment for 512/512 disk *with* topology -- aligned to optimal
# I/O size (32KiB)
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="align 512/4K +MD"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_FDISK"

ts_skip_nonroot
ts_check_prog "mdadm"

# set global variable TS_DEVICE
ts_scsi_debug_init dev_size_mb=50 sector_size=512 physblk_exp=3
DEVNAME=$(basename $TS_DEVICE)

ts_log "Create partitions"
$TS_CMD_FDISK ${TS_DEVICE} >> $TS_OUTPUT 2>&1 <<EOF
n
p
1

+20M
n
p
2


p
w
q
EOF

udevadm settle
ts_log "Alignment offsets:"
cat /sys/block/${DEVNAME}/${DEVNAME}{1,2}/alignment_offset >> $TS_OUTPUT 2>&1

ts_lock "md"

MD_DEVNAME=md8
MD_DEVICE=/dev/${MD_DEVNAME}

mdadm -q -S ${MD_DEVICE} &> /dev/null
udevadm settle

mdadm -q --create ${MD_DEVICE} --metadata=0.90 --chunk=64 \
	    --level=0 --raid-devices=2 ${TS_DEVICE}1 ${TS_DEVICE}2 >> $TS_OUTPUT 2>&1
udevadm settle

ts_log "Create partitions (MD)"
$TS_CMD_FDISK ${MD_DEVICE} >> $TS_OUTPUT 2>&1 <<EOF
n
p
1

+10M
n
p
2

+10M
p
w
q
EOF

udevadm settle
ts_log "Alignment offsets (MD):"
cat /sys/block/${MD_DEVNAME}/${MD_DEVNAME}p{1,2}/alignment_offset >> $TS_OUTPUT 2>&1

mdadm -q -S ${MD_DEVICE} >> $TS_OUTPUT 2>&1

udevadm settle
ts_unlock "md"

ts_fdisk_clean $TS_DEVICE
ts_fdisk_clean $MD_DEVICE

ts_finalize
