#!/bin/bash

#
# Copyright (C) 2022 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="mkswap"

. "$TS_TOPDIR"/functions.sh

ts_init "$*"

ts_check_test_command "$TS_CMD_MKSWAP"
ts_check_test_command "$TS_HELPER_SYSINFO"
ts_check_prog "xz"
ts_check_prog "cmp"

BYTE_ORDER="$("$TS_HELPER_SYSINFO" byte-order)"
UUID=4c08e1cd-3c82-46bf-a55b-0c3270d6dfeb

for PAGESIZE in 4096 8192; do
	name="${BYTE_ORDER}-${PAGESIZE}"
	outimg="$TS_OUTDIR/${name}.img"
	origimg="$TS_OUTDIR/${name}.img.orig"

	ts_init_subtest $name

	rm -f "$outimg"
	truncate -s $(( PAGESIZE * 10 )) "$outimg" > $TS_ERRLOG 2>&1

	"$TS_CMD_MKSWAP" -q -L label -U "$UUID" -p "$PAGESIZE" "$outimg" \
		> "$TS_OUTPUT" 2> "$TS_ERRLOG" || ts_log "mkswap failed"
	xz -dc "$TS_SELF/${name}.img.xz" > "$origimg"

	cmp "$origimg" "$outimg" > "$TS_ERRLOG" 2>&1

	ts_finalize_subtest
done

ts_finalize
