#!/usr/bin/env bash

#
# Copyright (C) 2026 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="colors"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_COLUMN"
ts_cd "$TS_OUTDIR"

COLOR_NAMES=( black blink blue bold brown cyan darkgray gray green halfbright 
                lightblue lightcyan lightgray lightgreen lightmagenta lightred
                magenta red yellow )

ts_init_subtest "names"
    for n in "${COLOR_NAMES[@]}"; do
        $TS_CMD_COLUMN --table --color=always --table-column "name=COL1,color=${n}" \
            "$TS_SELF"/files/table >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
    done
ts_finalize_subtest

ts_init_subtest "header-only"
    for n in "${COLOR_NAMES[@]}"; do
        $TS_CMD_COLUMN --table --color=always --table-column "name=COL1,headercolor=${n}" \
            "$TS_SELF"/files/table >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
    done
ts_finalize_subtest

ts_init_subtest "ansi-esc-seq"
    for s in "7;37" "1;33" "3;31" "9;35" "1;4;31;45" "2;32;46" "4;38;5;123"; do
        $TS_CMD_COLUMN --table --color=always --table-column "name=COL1,color=${s}" \
            "$TS_SELF"/files/table >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
    done
ts_finalize_subtest


ts_init_subtest "colorscheme"
    XDG_CONFIG_HOME="$TS_SELF/files" $TS_CMD_COLUMN --table --color=always \
        --table-colorscheme test --table-column "name=COL1,colorkey=cols,headercolorkey=header" \
        "$TS_SELF"/files/table >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
ts_finalize_subtest


ts_finalize
