#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="simple"

. $TS_TOPDIR/functions.sh
ts_init "$*"

rm -f $TS_SELF/input
echo {a..z}  > $TS_SELF/input
$TS_CMD_TAILF  $TS_SELF/input > $TS_OUTPUT 2>&1 &
sleep 0.1
echo {0..9} >> $TS_SELF/input
sleep 0.1
rm -f $TS_SELF/input

ts_finalize
