#!/bin/bash
#
# Copyright (C) 2023 Masatake YAMATO <yamato@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="flock"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSLOCKS"
ts_check_test_command "$TS_CMD_LSFD"
ts_check_test_command "$TS_HELPER_MKFDS"
ts_check_prog "sed"
ts_check_prog "ps"
ts_check_prog "tee"

ts_cd "$TS_OUTDIR"

FILE0=util-linux-lslocks-target-file
FILE=${FILE0}--$$
FD=17
DFD=18
COLS=COMMAND,TYPE,SIZE,MODE,START,END
OPTS="--raw --noheadings"
METHODS=(
    flock-sh
    flock-ex
    posix-r-
    posix--w
    posix-rw
    ofd-r-
    ofd--w
    ofd-rw
    lease-w
)

OFD_METHODS=(
    flock-sh
    flock-ex
    ofd-r-
    ofd--w
    ofd-rw
    lease-w
)

DFD=18
COLS_WITH_HOLDERS=COMMAND,TYPE,SIZE,MODE,START,END,HOLDERS
run_lslocks()
{
    local m=$1

    {
	rm -f "${FILE}"
	coproc MKFDS { "$TS_HELPER_MKFDS" make-regular-file $FD file="$FILE" lock=$m; }
	if read -r -u "${MKFDS[0]}" PID; then
	    "$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS}" | tee debug-$m
	    echo "# $m + ${COLS} + ${OPTS}": ${PIPESTATUS[0]}
	    if [[ $(wc -l < debug-$m) == 0 ]]; then
		echo "# DEBUG: $PID"

		echo "# DEBUG START: ps"
		ps "$PID"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS}"
		"$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		"$TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump fdinfo"
		for fd in /proc/$PID/fdinfo/*; do
		    echo "#   fd=$fd"
		    cat $fd
		done
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump locks"
		cat /proc/locks
		echo "# DEBUG END: $$"

		rm debug-$m
	    fi

	    "$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o PATH | sed -e 's#.*\('"$FILE0"'\)--[0-9]\+ *$#\1#' | tee debug-$m
	    echo "# $m + PATH + ${OPTS}": ${PIPESTATUS[0]}
	    if [[ $(wc -l < debug-$m) == 0 ]]; then
		echo "# DEBUG: $PID"

		echo "# DEBUG START: ps"
		ps "$PID"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o PATH
		"$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		"$TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump fdinfo"
		for fd in /proc/$PID/fdinfo/*; do
		    echo "#   fd=$fd"
		    cat $fd
		done
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump locks"
		cat /proc/locks
		echo "# DEBUG END: $$"

		rm debug-$m
	    fi

	    echo DONE >&"${MKFDS[1]}"
	fi
    } > "$TS_OUTPUT" 2>&1

    wait "${MKFDS_PID}"
}

run_lslocks_with_co_holders()
{
    local m=$1

    {
	rm -f "${FILE}"
	coproc MKFDS { "$TS_HELPER_MKFDS" make-regular-file $FD file="$FILE" lock=$m dupfd=$DFD; }
	if read -r -u "${MKFDS[0]}" PID; then
	    "$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS_WITH_HOLDERS}" | sed -e "s/${PID},/1,/g" | tee debug-$m
	    echo "# $m + ${COLS_WITH_HOLDERS} + ${OPTS}": ${PIPESTATUS[0]}
	    if [[ $(wc -l < debug-$m) == 0 ]]; then
		echo "# DEBUG: $PID"

		echo "# DEBUG START: ps"
		ps "$PID"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS_WITH_HOLDERS}"
		"$TS_CMD_LSLOCKS" ${OPTS} --pid "${PID}" -o "${COLS_WITH_HOLDERS}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: $TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		"$TS_CMD_LSFD" -Q 'FD >= 0' --pid "${PID}"
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump fdinfo"
		for fd in /proc/$PID/fdinfo/*; do
		    echo "#   fd=$fd"
		    cat $fd
		done
		echo "# DEBUG END: $$"

		echo "# DEBUG START: dump locks"
		cat /proc/locks
		echo "# DEBUG END: $$"

		rm debug-$m
	    fi
	    echo DONE >&"${MKFDS[1]}"

	fi
    } > "$TS_OUTPUT" 2>&1

    wait "${MKFDS_PID}"
}

for m in "${METHODS[@]}"; do
    ts_init_subtest "$m"
    run_lslocks "$m"
    ts_finalize_subtest
done

for m in "${OFD_METHODS[@]}"; do
    ts_init_subtest "$m+HOLDERS"
    run_lslocks_with_co_holders "$m"
    ts_finalize_subtest
done

ts_finalize
