#!/bin/bash

# Copyright (C) 2022 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="enosys"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_ENOSYS"
ts_check_enosys_syscalls fallocate fsopen execve

ts_init_subtest basic

FALLOCATE_TEST="$TS_HELPER_ENOSYS fallocate"

$FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s fallocate $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s fsopen -s fallocate $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s fallocate -s fsopen $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s fallocate:12 $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s fallocate:ENOMEM $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"

ts_finalize_subtest

ts_init_subtest exec

FALLOCATE_TEST="$TS_HELPER_ENOSYS exec"

$FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s execve $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"

ts_finalize_subtest

ts_init_subtest ioctl

FALLOCATE_TEST="$TS_HELPER_ENOSYS ioctl"

$FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s ioctl $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -i FIOCLEX $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -i "$("$TS_CMD_ENOSYS" -m | grep FIOCLEX | awk '{ print $1 }')" $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -s ioctl -i FIOCLEX $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -i FIOCLEX:12 $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"
"$TS_CMD_ENOSYS" -i FIOCLEX:ENOMEM $FALLOCATE_TEST > /dev/null 2>> "$TS_OUTPUT"

ts_finalize_subtest

ts_finalize
