.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH UPDATE 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
update \- periodically flush Linux filesystem buffers
.SH SYNOPSIS
.B update [ interval ]
.SH DESCRIPTION
.B update
executes
.BR sync (2)
every
.I interval
seconds.  By default, the
.I interval
is 30 seconds.  It is generally started at boot time in
.IR /etc/rc .
.SH "SEE ALSO"
.BR sync (2),
.BR sync (8),
.BR init (8)
.SH AUTHOR
Linus Torvalds (torvalds@cs.helsinki.fi)
.br
With modifications by Rick Sladkey (jrs@world.std.com)
