#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux-ng.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
. ./commands.sh
. ./functions.sh

TS_COMPONENT="namei"
TS_DESC="logic"

ts_init "$*"

SANDBOX="$TS_OUTDIR/namei"

mkdir -p $SANDBOX/namei1/namei2
touch $SANDBOX/namei1/namei2/a $SANDBOX/namei1/namei2/b

$TS_CMD_NAMEI $SANDBOX/namei1/namei2/a   >> $TS_OUTPUT 2>&1
$TS_CMD_NAMEI $SANDBOX/namei1/namei2/b   >> $TS_OUTPUT 2>&1
$TS_CMD_NAMEI $SANDBOX/namei1/namei2/a/b >> $TS_OUTPUT 2>&1

ts_finalize

