#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="dlopen"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

# incorrect warning: top_builddir is referenced but not assigned.
# shellcheck disable=SC2154
if [ -e "$top_builddir/meson.conf" ]; then
  #meson build
  libpath=${top_builddir}/liblastlog2
else
  #automake/autoconf build
  libpath=${top_builddir}/.libs
fi

ts_check_test_command $TS_HELPER_LIBLASTLOG2_DLOPEN

$TS_HELPER_LIBLASTLOG2_DLOPEN ${libpath}/liblastlog2.so >/dev/null || ts_failed "returned an error"

ts_finalize
