#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="rename_user"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command  $TS_HELPER_LIBLASTLOG2_RENAME_USER

$TS_HELPER_LIBLASTLOG2_RENAME_USER || ts_failed "returned an error"

rm tst-rename-user.db

ts_finalize
