#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="sqlite3_time"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command $TS_HELPER_LIBLASTLOG2_Y2038_SQLITE2_TIME

$TS_HELPER_LIBLASTLOG2_Y2038_SQLITE2_TIME >/dev/null || ts_failed "returned an error"

rm y2038-sqlite3-time.db

ts_finalize
