#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="y2038_ll2_read_all"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command $TS_HELPER_LIBLASTLOG2_Y2038_LL2_READ_ALL

$TS_HELPER_LIBLASTLOG2_Y2038_LL2_READ_ALL >/dev/null || ts_failed "returned an error"

rm y2038-ll2_read_all.db

ts_finalize
