#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="cid-kmsg-delta"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_HELPER_DMESG"

export TZ="GMT"
export DMESG_TEST_BOOTIME="1234567890.123456"

$TS_HELPER_DMESG -d -K $TS_SELF/cid-kmsg-input >> $TS_OUTPUT 2>/dev/null

# dmesg kmsg output can have varying number of caller_id padding spaces
# normalize caller_id padding by removing leading spaces
sed -i 's/\[ *T/\[T/g' $TS_OUTPUT
sed -i 's/\[ *C/\[C/g' $TS_OUTPUT

ts_finalize
