#!/bin/bash
#
# Copyright (C) 2009 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="mkfs checksums"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MKMINIX"

ts_skip_nonroot
ts_check_losetup

IMAGE="$TS_OUTDIR/${TS_TESTNAME}-loop.img"
ts_device_init
DEVICE=$TS_LODEV

ts_log "create minix fs"
$TS_CMD_MKMINIX $DEVICE 2>&1 >> $TS_OUTPUT

ts_log "fsck minix fs"
$TS_CMD_FSCKMINIX $DEVICE 2>&1 >> $TS_OUTPUT

ts_finalize

