//po4a: entry man manual
////
Copyright 1999 Andreas Dilger (adilger@enel.ucalgary.ca)

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, and the entire permission notice in its entirety,
   including the disclaimer of warranties.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the author may not be used to endorse or promote
   products derived from this software without specific prior
   written permission.

THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF
WHICH ARE HEREBY DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
USE OF THIS SOFTWARE, EVEN IF NOT ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

Created  Wed Mar 10 17:42:12 1999, Andreas Dilger
////
= uuid_unparse(3)
:doctype: manpage
:man manual: Programmer's Manual
:man source: util-linux {release-version}
:page-layout: base
:lib: libuuid
:firstversion: 2.15.1

== NAME

uuid_unparse - convert a UUID from binary representation to a string

== SYNOPSIS

*#include <uuid.h>*

*void uuid_unparse(const uuid_t __uu__, char *__out__);* +
*void uuid_unparse_upper(const uuid_t __uu__, char *__out__);* +
*void uuid_unparse_lower(const uuid_t __uu__, char *__out__);*

== DESCRIPTION

The *uuid_unparse*() function converts the supplied UUID _uu_ from the binary representation into a 36-byte string (plus trailing '\0') of the form 1b4e28ba-2fa1-11d2-883f-0016d3cca427 and stores this value in the character string pointed to by _out_. The case of the hex digits returned by *uuid_unparse*() may be upper or lower case, and is dependent on the system-dependent local default.

If the case of the hex digits is important then the functions *uuid_unparse_upper*() and *uuid_unparse_lower*() may be used.

== CONFORMING TO

This library unparses UUIDs compatible with OSF DCE 1.1.

== AUTHORS

Theodore Y. Ts'o

== SEE ALSO

*uuid*(3),
*uuid_clear*(3),
*uuid_compare*(3),
*uuid_copy*(3),
*uuid_generate*(3),
*uuid_time*(3),
*uuid_is_null*(3),
*uuid_parse*(3)

include::man-common/bugreports.adoc[]

include::man-common/footer-lib.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
