#!/bin/bash

#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#


TS_TOPDIR="${0%/*}/../.."
TS_DESC="movedata"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_SFDISK"
ts_check_test_command "$TS_HELPER_MD5"

ts_skip_nonroot
ts_check_prog "mkfs.ext4"

# set global variable TS_DEVICE
ts_scsi_debug_init dev_size_mb=100 sector_size=512

# create a partition
echo ',10M,L' | $TS_CMD_SFDISK --no-reread ${TS_DEVICE} &> /dev/null
udevadm settle

mkfs.ext4 ${TS_DEVICE}1 &> /dev/null
udevadm settle
CHECKSUM=$("$TS_HELPER_MD5" < "${TS_DEVICE}1")

function checksum() {
	local dev="$1"
	CHECK=$("$TS_HELPER_MD5" < "${dev}")
	if [ "$CHECKSUM" != "$CHECK" ]; then
		echo "Checksum does not match!" >> $TS_OUTPUT
	fi
}

ts_init_subtest "up"
echo '+1000,' | $TS_CMD_SFDISK --no-reread --move-data=$TS_OUTPUT.log -N1 ${TS_DEVICE} >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_fdisk_clean $TS_DEVICE
udevadm settle
checksum ${TS_DEVICE}1
ts_finalize_subtest

udevadm settle

ts_init_subtest "down"
echo "-500," | $TS_CMD_SFDISK --no-reread --move-data=$TS_OUTPUT.log -N1 ${TS_DEVICE} >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_fdisk_clean $TS_DEVICE
udevadm settle
checksum ${TS_DEVICE}1
ts_finalize_subtest

udevadm settle

ts_init_subtest "non-overlay"
echo "+30M," | $TS_CMD_SFDISK --no-reread --move-data=$TS_OUTPUT.log -N1 ${TS_DEVICE} >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_fdisk_clean $TS_DEVICE
udevadm settle
checksum ${TS_DEVICE}1
ts_finalize_subtest


ts_finalize
