#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="mkfs endianness"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MKCRAMFS"
ts_check_test_command "$TS_CMD_HEXDUMP"

ts_skip_nonroot

IMAGE_DATA="$TS_OUTDIR/${TS_TESTNAME}-data"
IMAGE_CREATED="$TS_OUTDIR/${TS_TESTNAME}-cramfs.img"	#Image created during the test and compared against the known images.

test_image() {
	local TO_ENDIANNESS="$1"; shift
	ts_log "create $TO_ENDIANNESS endian"

	$TS_CMD_MKCRAMFS -N "$TO_ENDIANNESS" -b 4096 "$IMAGE_DATA" \
		"$IMAGE_CREATED" >> $TS_OUTPUT 2>> $TS_ERRLOG

	$TS_CMD_HEXDUMP -C $IMAGE_CREATED >> $TS_OUTPUT

	rm "$IMAGE_CREATED"
}

#generate test data, must be owner root
rm -rf "$IMAGE_DATA"
mkdir -p $IMAGE_DATA/dirA/dirB
yes "Testing cramfs 1234567890 Endianness check 1234567890 Endianness check" \
	| dd of=$IMAGE_DATA/dirA/dirB/a bs=512 count=1 &> /dev/null
yes "Testing cramfs 1234567890 Endianness check 1234567890 Endianness check" \
	| dd of=$IMAGE_DATA/dirA/dirB/b bs=512 count=30 &> /dev/null
# sudo may use whatever group
chgrp -R 0 $IMAGE_DATA

#perform tests for both endians
test_image "little"
test_image "big"

ts_finalize

