#!/bin/bash

#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="color with week numbers"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_CAL"
ts_inhibit_custom_colorscheme

has_ncurses=$( ts_has_ncurses_support )
if [ "$has_ncurses" != "yes" ]; then
	ts_skip "without-ncurses"
fi

# --color output depends on terminal type
export TERM=linux

USETERM=$( ts_has_option "useterm" "$*" )

[ "$USETERM" == "yes" ] && TS_VERBOSE="yes"

function call_cal {
	if [ "$USETERM" == "yes" ]; then
		 XDG_CONFIG_HOME="$TS_SELF" $TS_CMD_CAL --color=always "$@"
	fi
	XDG_CONFIG_HOME="$TS_SELF" $TS_CMD_CAL --color=always "$@" >> $TS_OUTPUT
}

ts_init_subtest "first-day-week-numbers"
call_cal -w --color=always 1 1 1
ts_finalize_subtest

ts_init_subtest "reformation-corner-cases-1-week-numbers"
call_cal -w --color=always 2 9 1752
ts_finalize_subtest

ts_init_subtest "reformation-corner-cases-2-week-numbers"
call_cal -w --color=always 3 9 1752
ts_finalize_subtest

ts_init_subtest "reformation-corner-cases-3-week-numbers"
call_cal -w --color=always 13 9 1752
ts_finalize_subtest

ts_init_subtest "reformation-corner-cases-4-week-numbers"
call_cal -w --color=always 14 9 1752
ts_finalize_subtest

ts_init_subtest "last-day-week-numbers"
call_cal -w --color=always -3 31 12 9999
ts_finalize_subtest

ts_finalize
