#!/bin/bash

#
# Copyright (C) 2007-2018 Karel Zak <kzak@redhat.com>
# Copyright (C) 2023      Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="year"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_CAL"

export TERM=linux

USETERM=$( ts_has_option "useterm" "$*" )
MYTIME="29 11 2006"

function call_cal {

	ts_init_subtest "$(echo "$1" | cut -d ' ' -f 1)"
	ts_log "$1"
	shift
	if [ "$USETERM" == "yes" ]; then
		$TS_CMD_CAL "$@"
	fi
	$TS_CMD_CAL "$@" >> $TS_OUTPUT
	ts_finalize_subtest
}

call_cal "6 columns" --year --columns 6 $MYTIME
call_cal "5 columns" --year --columns 5 $MYTIME
call_cal "auto columns" --year --columns auto $MYTIME

ts_finalize

