#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="September 1752 with week numbers"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_CAL"

export TERM=linux

USETERM=$( ts_has_option "useterm" "$*" )
MYMONTH="09 1752"
MYYEAR="1752"

[ "$USETERM" == "yes" ] && TS_VERBOSE="yes"
ts_log ""


function call_cal {
	ts_log "$1"
	shift
	if [ "$USETERM" == "yes" ]; then
		$TS_CMD_CAL "$@"
	fi
	$TS_CMD_CAL "$@" >> $TS_OUTPUT
}


call_cal "Gregorian - Monday-based month with week numbers" -1mw $MYMONTH

call_cal "Gregorian - Sunday-based month with week numbers" -1sw $MYMONTH

call_cal "Julian - Monday-based month with week numbers" -1mjw $MYMONTH

call_cal "Julian - Sunday-based month with week numbers" -1sjw $MYMONTH

call_cal "Gregorian - Monday-based three months with week numbers" -3mw $MYMONTH

call_cal "Gregorian - Sunday-based three months with week numbers" -3sw $MYMONTH

call_cal "Julian - Monday-based three months with week numbers" -3mjw $MYMONTH

call_cal "Julian - Sunday-based three months with week numbers" -3sjw $MYMONTH

call_cal "Gregorian - Monday-based year with week numbers" -1mw $MYYEAR

call_cal "Gregorian - Sunday-based year with week numbers" -1sw $MYYEAR

call_cal "Julian - Monday-based year with week numbers" -1mjw $MYYEAR

call_cal "Julian - Sunday-based year with week numbers" -1sjw $MYYEAR

call_cal "Gregorian - address by week number" --week=40 --iso $MYYEAR

ts_finalize
