#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="week number corner cases"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_CAL"

export TERM=linux

USETERM=$( ts_has_option "useterm" "$*" )

[ "$USETERM" == "yes" ] && TS_VERBOSE="yes"

function call_cal {
	local testname=$(echo "$2" | sed 's/-//g')

	ts_init_subtest "$testname"
	ts_log "$1"
	shift
	for x in 2001 2002 2003 2009 2010 2011 2012 ; do
		if [ "$USETERM" == "yes" ]; then
			$TS_CMD_CAL "$@" 1 $x
		fi
		$TS_CMD_CAL "$@" 1 $x >> $TS_OUTPUT
	done
	ts_finalize_subtest
}

call_cal "Gregorian - Monday-based week with week numbers" -ymw
call_cal "Gregorian - Sunday-based week with week numbers" -ysw
call_cal "Julian - Monday-based week with week numbers" -ymjw
call_cal "Julian - Sunday-based week with week numbers" -ysjw
call_cal "Gregorian - Monday-based week with week number" -3mw
call_cal "Gregorian - Sunday-based week with week numbers - 3 month" -3sw
call_cal "Julian - Monday-based week with week numbers - 3 month" -3mjw
call_cal "Julian - Sunday-based week with week numbers - 3 month" -3sjw

ts_finalize

