.\" addpart.8 -- man page for addpart
.\" Copyright 2007 Karel Zak <kzak@redhat.com>
.\" Copyright 2007 Red Hat, Inc.
.\" May be distributed under the GNU General Public License
.TH ADDPART 8 "January 2015" "util-linux" "System Administration"
.SH NAME
addpart \- tell the kernel about the existence of a partition
.SH SYNOPSIS
.B addpart
.I device partition start length
.SH DESCRIPTION
.B addpart
tells the Linux kernel about the existence of the specified partition.
The command is a simple wrapper around the "add partition" ioctl.

This command doesn't manipulate partitions on a block device.

.SH PARAMETERS
.TP
.I device
The disk device.
.TP
.I partition
The partition number.
.TP
.I start
The beginning of the partition (in 512-byte sectors).
.TP
.I length
The length of the partition (in 512-byte sectors).

.SH SEE ALSO
.BR delpart (8),
.BR fdisk (8),
.BR parted (8),
.BR partprobe (8),
.BR partx (8)
.SH AVAILABILITY
The addpart command is part of the util-linux package and is available from
https://www.kernel.org/pub/linux/utils/util-linux/.
