.\" -*- nroff -*-
.\" Copyright 1998 Andries E. Brouwer (aeb@cwi.nl)
.\" Copyright 2007 Karel Zak <kzak@redhat.com>
.\"
.\" May be distributed under the GNU General Public License
.TH BLOCKDEV 8 "Jun 2007" ""
.SH NAME
blockdev \- call block device ioctls from the command line
.SH SYNOPSIS
.B blockdev
.RI [ options ]
.I commands devices
.br
.B blockdev
.B \-\-report
.RI [ devices ]
.SH DESCRIPTION
The utility
.B blockdev
allows one to call block device ioctls from the command line.
.SH OPTIONS
.TP
.B \-V
Print version and exit.
.TP
.B \-q
Be quiet.
.TP
.B \-v
Be verbose.
.TP
.B \-\-report
Print a report for
.IR devices .
Note that the partition StartSec is in 512-byte sectors.
.SH COMMANDS
.TP
.B \--setro
Set read-only.
.TP
.B \--setrw
Set read-write.
.TP
.B \--getro
Get read-only. Print 1 if the device is read-only, 0 otherwise.
.TP
.B \--getss
Print sectorsize in bytes - usually 512.
.TP
.B \--getbsz
Print blocksize in bytes.
.TP
.BI \--setbsz " N"
Set blocksize to
.I N
bytes.
.TP
.B \--getsize
Print device size in sectors (BLKGETSIZE). Deprecated in favor of the
.B \--getsz
option.
.TP
.B \--getsize64
Print device size in bytes (BLKGETSIZE64)
.TP
.B \--getsz
Get size in 512-byte sectors (BLKGETSIZE64 / 512).
.TP
.BI \--setra " N"
Set readahead to
.I N
512-byte sectors.
.TP
.B \--getra
Print readahead (in 512-byte sectors).
.TP
.BI \--setfra " N"
Set filesystem readahead (same like --setra on 2.6 kernels).
.TP
.B \--getfra
Get filesystem readahead.
.TP
.B \--flushbufs
Flush buffers.
.TP
.B \--rereadpt
Reread partition table.
.SH AUTHOR
blockdev was written by Andries E. Brouwer.
.SH AVAILABILITY
The blockdev command is part of the util-linux-ng package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux-ng/.

