.\" delpart.8 -- man page for delpart
.\" Copyright 2007 Karel Zak <kzak@redhat.com>
.\" Copyright 2007 Red Hat, Inc.
.\" May be distributed under the GNU General Public License
.TH DELPART 8 "January 2015" "util-linux" "System Administration"
.SH NAME
delpart \- tell the kernel to forget about a partition
.SH SYNOPSIS
.B delpart
.I device partition
.SH DESCRIPTION
.B delpart
asks the Linux kernel to forget about the specified \fIpartition\fR
(a number) on the specified \fIdevice\fR.
The command is a simple wrapper around the "del partition" ioctl.

This command doesn't manipulate partitions on a block device.

.SH SEE ALSO
.BR addpart (8),
.BR fdisk (8),
.BR parted (8),
.BR partprobe (8),
.BR partx (8)
.SH AVAILABILITY
The delpart command is part of the util-linux package and is available from
https://www.kernel.org/pub/linux/utils/util-linux/.
