//po4a: entry man manual
////
Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
May be distributed under the GNU General Public License
////
= fdformat(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: fdformat

== NAME

fdformat - low-level format a floppy disk

== SYNOPSIS

*fdformat* [options] _device_

== DESCRIPTION

*fdformat* does a low-level format on a floppy disk. _device_ is usually one of the following (for floppy devices the major = 2, and the minor is shown for informational purposes only):

....
/dev/fd0d360  (minor = 4)
/dev/fd0h1200 (minor = 8)
/dev/fd0D360  (minor = 12)
/dev/fd0H360  (minor = 12)
/dev/fd0D720  (minor = 16)
/dev/fd0H720  (minor = 16)
/dev/fd0h360  (minor = 20)
/dev/fd0h720  (minor = 24)
/dev/fd0H1440 (minor = 28)
....
....
/dev/fd1d360 (minor = 5)
/dev/fd1h1200 (minor = 9)
/dev/fd1D360 (minor = 13)
/dev/fd1H360 (minor = 13)
/dev/fd1D720 (minor = 17)
/dev/fd1H720 (minor = 17)
/dev/fd1h360 (minor = 21)
/dev/fd1h720 (minor = 25)
/dev/fd1H1440 (minor = 29)
....

The generic floppy devices, _/dev/fd0_ and _/dev/fd1_, will fail to work with *fdformat* when a non-standard format is being used, or if the format has not been autodetected earlier. In this case, use *setfdprm*(8) to load the disk parameters.

== OPTIONS

*-f*, *--from* _N_::
Start at the track _N_ (default is 0).

*-t*, *--to* _N_::
Stop at the track _N_.

*-r*, *--repair* _N_::
Try to repair tracks failed during the verification (max _N_ retries).

*-n*, *--no-verify*::
Skip the verification that is normally performed after the formatting.

include::man-common/help-version.adoc[]

== NOTES

This utility does not handle USB floppy disk drives. Use *ufiformat*(8) instead.

== AUTHORS

mailto:almesber@nessie.cs.id.ethz.ch[Werner Almesberger]

== SEE ALSO

*fd*(4),
*emkfs*(8),
*mkfs*(8),
*setfdprm*(8),
*ufiformat*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
