.\" Copyright 1992, 1993, 1994 Rickard E. Faith (faith@cs.unc.edu)
.\" May be freely distributed.
.TH FSCK.MINIX 8 "June 2015" "util-linux" "System Administration"
.SH NAME
fsck.minix \- check consistency of Minix filesystem
.SH SYNOPSIS
.B fsck.minix
[options]
.I device
.SH DESCRIPTION
.B fsck.minix
performs a consistency check for the Linux MINIX filesystem.
.PP
The program assumes the filesystem is quiescent.
.B fsck.minix
should not be used on a mounted device unless you can be sure nobody is
writing to it.  Remember that the kernel can write to device when it
searches for files.
.PP
The \fIdevice\fR name will usually have the following form:
.RS
.TS
tab(:);
l l.
/dev/hda[1\(en63]:IDE disk 1
/dev/hdb[1\(en63]:IDE disk 2
/dev/sda[1\(en15]:SCSI disk 1
/dev/sdb[1\(en15]:SCSI disk 2
.TE
.RE
.PP
If the filesystem was changed, i.e., repaired, then
.B fsck.minix
will print "FILE SYSTEM HAS CHANGED" and will
.BR sync (2)
three times before exiting.  There is
.I no
need to reboot after check.
.SH WARNING
.B fsck.minix
should
.B not
be used on a mounted filesystem.  Using
.B fsck.minix
on a mounted filesystem is very dangerous, due to the possibility that
deleted files are still in use, and can seriously damage a perfectly good
filesystem!  If you absolutely have to run
.B fsck.minix
on a mounted filesystem, such as the root filesystem, make sure nothing
is writing to the disk, and that no files are "zombies" waiting for
deletion.
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-list\fR
List all filenames.
.TP
\fB\-r\fR, \fB\-\-repair\fR
Perform interactive repairs.
.TP
\fB\-a\fR, \fB\-\-auto\fR
Perform automatic repairs.  This option implies
.B \-\-repair
and serves to answer all of the questions asked with the default.  Note
that this can be extremely dangerous in the case of extensive filesystem
damage.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose.
.TP
\fB\-s\fR, \fB\-\-super\fR
Output super-block information.
.TP
\fB\-m\fR, \fB\-\-uncleared\fR
Activate MINIX-like "mode not cleared" warnings.
.TP
\fB\-f\fR, \fB\-\-force\fR
Force a filesystem check even if the filesystem was marked as valid.
Marking is done by the kernel when the filesystem is unmounted.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.SH DIAGNOSTICS
There are numerous diagnostic messages.  The ones mentioned here are the
most commonly seen in normal usage.
.PP
If the device does not exist,
.B fsck.minix
will print "unable to read super block".  If the device exists, but is not
a MINIX filesystem,
.B fsck.minix
will print "bad magic number in super-block".
.SH EXIT STATUS
The exit status returned by
.B fsck.minix
is the sum of the following:
.PP
.RS
.PD 0
.TP
.B 0
No errors
.TP
.B 3
Filesystem errors corrected, system should be rebooted if filesystem was
mounted
.TP
.B 4
Filesystem errors left uncorrected
.TP
.B 7
Combination of exit statuses 3 and 4
.TP
.B 8
Operational error
.TP
.B 16
Usage or syntax error
.PD
.RE
.SH AUTHORS
.MT torvalds@\:cs.\:helsinki.\:fi
Linus Torvalds
.ME
.br
Exit status values by
.MT faith@\:cs.\:unc.\:edu
Rik Faith
.ME
.br
Added support for filesystem valid flag:
.MT greg%\:wind.\:uucp@\:plains.\:nodak.\:edu
Dr.\& Wettstein
.ME .
.br
Check to prevent fsck of mounted filesystem added by
.MT quinlan@\:yggdrasil.\:com
Daniel Quinlan
.ME .
.br
Minix v2 fs support by
.MT schwab@\:issan.\:informatik.\:uni-dortmund.\:de
Andreas Schwab
.ME ,
updated by
.MT janl@\:math.\:uio.\:no
Nicolai Langfeldt
.ME .
.br
Portability patch by
.MT rmk@\:ecs.\:soton.\:ac.\:uk
Russell King
.ME .
.SH SEE ALSO
.BR fsck (8),
.BR fsck.ext2 (8),
.BR mkfs (8),
.BR mkfs.ext2 (8),
.BR mkfs.minix (8),
.BR reboot (8)
.SH AVAILABILITY
The fsck.minix command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
