//po4a: entry man manual
////
Copyright 1992, 1993, 1994 Rickard E. Faith (faith@cs.unc.edu)
May be freely distributed.
////
= fsck.minix(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: fsck.minix

== NAME

fsck.minix - check consistency of Minix filesystem

== SYNOPSIS

*fsck.minix* [options] _device_

== DESCRIPTION

*fsck.minix* performs a consistency check for the Linux MINIX filesystem.

The program assumes the filesystem is quiescent. *fsck.minix* should not be used on a mounted device unless you can be sure nobody is writing to it. Remember that the kernel can write to device when it searches for files.

The _device_ name will usually have the following form:

____
[cols=",",]
|===
|/dev/hda[1-63] |IDE disk 1
|/dev/hdb[1-63] |IDE disk 2
|/dev/sda[1-15] |SCSI disk 1
|/dev/sdb[1-15] |SCSI disk 2
|===
____

If the filesystem was changed, i.e., repaired, then *fsck.minix* will print "FILE SYSTEM HAS BEEN CHANGED" and will *sync*(2) three times before exiting. There is _no_ need to reboot after check.

== WARNING

*fsck.minix* should *not* be used on a mounted filesystem. Using *fsck.minix* on a mounted filesystem is very dangerous, due to the possibility that deleted files are still in use, and can seriously damage a perfectly good filesystem! If you absolutely have to run *fsck.minix* on a mounted filesystem, such as the root filesystem, make sure nothing is writing to the disk, and that no files are "zombies" waiting for deletion.

== OPTIONS

*-l*, *--list*::
List all filenames.

*-r*, *--repair*::
Perform interactive repairs.

*-a*, *--auto*::
Perform automatic repairs. This option implies *--repair* and serves to answer all of the questions asked with the default. Note that this can be extremely dangerous in the case of extensive filesystem damage.

*-v*, *--verbose*::
Be verbose.

*-s*, *--super*::
Output super-block information.

*-m*, *--uncleared*::
Activate MINIX-like "mode not cleared" warnings.

*-f*, *--force*::
Force a filesystem check even if the filesystem was marked as valid. Marking is done by the kernel when the filesystem is unmounted.

include::man-common/help-version.adoc[]

== DIAGNOSTICS

There are numerous diagnostic messages. The ones mentioned here are the most commonly seen in normal usage.

If the device does not exist, *fsck.minix* will print "unable to read super block". If the device exists, but is not a MINIX filesystem, *fsck.minix* will print "bad magic number in super-block".

== EXIT STATUS

The exit status returned by *fsck.minix* is the sum of the following:

*0*::
No errors
*3*::
Filesystem errors corrected, system should be rebooted if filesystem was mounted
*4*::
Filesystem errors left uncorrected
*7*::
Combination of exit statuses 3 and 4
*8*::
Operational error
*16*::
Usage or syntax error


== AUTHORS

mailto:torvalds@cs.helsinki.fi[Linus Torvalds]. Exit status values by mailto:faith@cs.unc.edu[Rik Faith] Added support for filesystem valid flag: mailto:greg%wind.uucp@plains.nodak.edu[Dr. Wettstein]. Check to prevent fsck of mounted filesystem added by mailto:quinlan@yggdrasil.com[Daniel Quinlan]. Minix v2 fs support by mailto:schwab@issan.informatik.uni-dortmund.de[Andreas Schwab], updated by mailto:janl@math.uio.no[Nicolai Langfeldt]. Portability patch by mailto:rmk@ecs.soton.ac.uk[Russell King].

== SEE ALSO

*fsck*(8),
*fsck.ext2*(8),
*mkfs*(8),
*mkfs.ext2*(8),
*mkfs.minix*(8),
*reboot*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
