//po4a: entry man manual
= mkfs(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: mkfs

== NAME

mkfs - build a Linux filesystem

== SYNOPSIS

*mkfs* [options] [*-t* _type_] [_fs-options_] _device_ [_size_]

== DESCRIPTION

*This mkfs frontend is deprecated in favour of filesystem specific mkfs.<type> utils.*

*mkfs* is used to build a Linux filesystem on a device, usually a hard disk partition. The _device_ argument is either the device name (e.g., _/dev/hda1_, _/dev/sdb2_), or a regular file that shall contain the filesystem. The _size_ argument is the number of blocks to be used for the filesystem.

The exit status returned by *mkfs* is 0 on success and 1 on failure.

In actuality, *mkfs* is simply a front-end for the various filesystem builders (**mkfs.**__fstype__) available under Linux. The filesystem-specific builder is searched for via your *PATH* environment setting only. Please see the filesystem-specific builder manual pages for further details.

== OPTIONS

*-t*, *--type* _type_::
Specify the _type_ of filesystem to be built. If not specified, the default filesystem type (currently ext2) is used.

_fs-options_::
Filesystem-specific options to be passed to the real filesystem builder.

*-V*, *--verbose*::
Produce verbose output, including all filesystem-specific commands that are executed. Specifying this option more than once inhibits execution of any filesystem-specific commands. This is really only useful for testing.

include::man-common/help-version.adoc[]
(Option *-V* will display version information only when it is the only parameter, otherwise it will work as *--verbose*.)

== BUGS

All generic options must precede and not be combined with filesystem-specific options. Some filesystem-specific programs do not automatically detect the device size and require the _size_ parameter to be specified.

== AUTHORS

mailto:david@ods.com[David Engel],
mailto:waltje@uwalt.nl.mugnet.org[Fred N. van Kempen],
mailto:sommel@sci.kun.nl[Ron Sommeling].

The manual page was shamelessly adapted from Remy Card's version for the ext2 filesystem.

== SEE ALSO

*fs*(5),
*badblocks*(8),
*fsck*(8),
*mkdosfs*(8),
*mke2fs*(8),
*mkfs.bfs*(8),
*mkfs.ext2*(8),
*mkfs.ext3*(8),
*mkfs.ext4*(8),
*mkfs.minix*(8),
*mkfs.msdos*(8),
*mkfs.vfat*(8),
*mkfs.xfs*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
