.\" Copyright 1992, 1993, 1994 Rickard E. Faith (faith@cs.unc.edu)
.\" May be freely distributed.
.TH MKFS.MINIX 8 "June 2015" "util-linux" "System Administration"
.SH NAME
mkfs.minix \- make a Minix filesystem
.SH SYNOPSIS
.B mkfs.minix
[options]
.I device
.RI [ size-in-blocks ]
.SH DESCRIPTION
.B mkfs.minix
creates a Linux MINIX filesystem on a device (usually a disk partition).

The
.I device
is usually of the following form:

.nf
.RS
/dev/hda[1\(en8] (IDE disk 1)
/dev/hdb[1\(en8] (IDE disk 2)
/dev/sda[1\(en8] (SCSI disk 1)
/dev/sdb[1\(en8] (SCSI disk 2)
.RE
.fi

The device may be a block device or an image file of one, but this is not
enforced.  Expect not much fun on a character device :-).
.PP
The
.I size-in-blocks
parameter is the desired size of the file system, in blocks.
It is present only for backwards compatibility.
If omitted the size will be determined automatically.
Only block counts strictly greater than 10 and strictly less than
65536 are allowed.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-check\fR
Check the device for bad blocks before creating the filesystem.  If any
are found, the count is printed.
.TP
\fB\-n\fR, \fB\-\-namelength\fR \fIlength\fR
Specify the maximum length of filenames.  Currently, the only allowable
values are 14 and 30 for file system versions 1 and 2.  Version 3 allows
only value 60.  The default is 30.
.TP
\fB\-i\fR, \fB\-\-inodes\fR \fInumber\fR
Specify the number of inodes for the filesystem.
.TP
\fB\-l\fR, \fB\-\-badblocks\fR \fIfilename\fR
Read the list of bad blocks from
.IR filename .
The file has one bad-block number per line.  The count of bad blocks read
is printed.
.TP
.B \-1
Make a Minix version 1 filesystem.  This is the default.
.TP
.BR \-2 , " \-v"
Make a Minix version 2 filesystem.
.TP
.B \-3
Make a Minix version 3 filesystem.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.  The long option cannot be combined
with other options.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.SH "EXIT CODES"
The exit code returned by
.B mkfs.minix
is one of the following:
.IP 0
No errors
.IP 8
Operational error
.IP 16
Usage or syntax error
.SH "SEE ALSO"
.BR fsck (8),
.BR mkfs (8),
.BR reboot (8)
.SH AVAILABILITY
The mkfs.minix command is part of the util-linux package and is available from
https://www.kernel.org/pub/linux/utils/util-linux/.
