//po4a: entry man manual
////
Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
Copyright 1998 Andries E. Brouwer (aeb@cwi.nl)
Copyright 2012 Davidlohr Bueso <dave@gnu.org>
Copyright (C) 2013 Karel Zak <kzak@redhat.com>
May be distributed under the GNU General Public License
////
= mkfs.minix(8)
:doctype: manpage
:man manual: System Administration
:man source: util-linux {release-version}
:page-layout: base
:command: mkfs.minix

== NAME

mkfs.minix - make a Minix filesystem

== SYNOPSIS

*mkfs.minix* [options] _device_ [_size-in-blocks_]

== DESCRIPTION

*mkfs.minix* creates a Linux MINIX filesystem on a device (usually a disk partition).

The _device_ is usually of the following form:

....
/dev/hda[1-8] (IDE disk 1)
/dev/hdb[1-8] (IDE disk 2)
/dev/sda[1-8] (SCSI disk 1)
/dev/sdb[1-8] (SCSI disk 2)
....

The device may be a block device or an image file of one, but this is not enforced. Expect not much fun on a character device :-).

The _size-in-blocks_ parameter is the desired size of the file system, in blocks. It is present only for backwards compatibility. If omitted the size will be determined automatically. Only block counts strictly greater than 10 and strictly less than 65536 are allowed.

== OPTIONS

*-c*, *--check*::
Check the device for bad blocks before creating the filesystem. If any are found, the count is printed.

*-n*, *--namelength* _length_::
Specify the maximum length of filenames. Currently, the only allowable values are 14 and 30 for file system versions 1 and 2. Version 3 allows only value 60. The default is 30.

*--lock*[=_mode_]::
Use exclusive BSD lock for device or file it operates. The optional argument _mode_ can be *yes*, *no* (or 1 and 0) or *nonblock*. If the _mode_ argument is omitted, it defaults to *yes*. This option overwrites environment variable *$LOCK_BLOCK_DEVICE*. The default is not to use any lock at all, but it's recommended to avoid collisions with *systemd-udevd*(8) or other tools.

*-i*, *--inodes* _number_::
Specify the number of inodes for the filesystem.

*-l*, *--badblocks* _filename_::
Read the list of bad blocks from _filename_. The file has one bad-block number per line. The count of bad blocks read is printed.

*-1*::
Make a Minix version 1 filesystem. This is the default.

*-2*, *-v*::
Make a Minix version 2 filesystem.

*-3*::
Make a Minix version 3 filesystem.

include::man-common/help-version.adoc[]
The long option cannot be combined with other options.

== ENVIRONMENT

LOCK_BLOCK_DEVICE=<mode>::
use exclusive BSD lock. The mode is "1" or "0". See *--lock* for more details.

== EXIT STATUS

The exit status returned by *mkfs.minix* is one of the following:

0::
No errors
8::
Operational error
16::
Usage or syntax error

== SEE ALSO

*fsck*(8),
*mkfs*(8),
*reboot*(8)

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
