.TH MKFS.CRAMFS 8 "April 2013" "util-linux" "System Administration"
.SH NAME
mkfs.cramfs \- make compressed ROM file system
.SH SYNOPSIS
.B mkfs.cramfs
[options]
.I directory file
.SH DESCRIPTION
Files on cramfs file systems are zlib-compressed one page at a time to
allow random read access.  The metadata is not compressed, but is
expressed in a terse representation that is more space-efficient than
conventional file systems.
.PP
The file system is intentionally read-only to simplify its design; random
write access for compressed files is difficult to implement.  cramfs
ships with a utility (mkcramfs) to pack files into new cramfs images.
.PP
File sizes are limited to less than 16\ MB.
.PP
Maximum file system size is a little under 272\ MB.  (The last file on the
file system must begin before the 256\ MB block, but can extend past it.)
.SH ARGUMENTS
The
.I directory
is simply the root of the directory tree that we want to generate a
compressed filesystem out of.
.PP
The
.I file
will contain the cram file system, which later can be mounted.
.SH OPTIONS
.TP
\fB\-v\fR
Enable verbose messaging.
.TP
\fB\-E\fR
Treat all warnings as errors, which are reflected as command return value.
.TP
\fB\-b\fR \fIblocksize\fR
Use defined block size, which has to be divisible by page size.
.TP
\fB\-e\fR \fIedition\fR
Use defined file system edition number in superblock.
.TP
\fB\-N\fR \fIbig, little, host\fR
Use defined endianness.  Value defaults to
.IR host .
.TP
\fB\-i\fR \fIfile\fR
Insert a
.I file
to cramfs file system.
.TP
\fB\-n\fR \fIname\fR
Set name of the cramfs file system.
.TP
\fB\-p\fR
Pad by 512 bytes for boot code.
.TP
\fB\-s\fR
This option is ignored.  Originally the \-s turned on directory entry
sorting.
.TP
\fB\-z\fR
Make explicit holes.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help text and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.SH "EXIT STATUS"
.RS
.PD 0
.TP
.B 0
success
.TP
.B 8
operation error, such as unable to allocate memory
.PD
.RE
.SH "SEE ALSO"
.BR fsck.cramfs (8),
.BR mount (8)
.SH AVAILABILITY
The example command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
