.\" partx.8 -- man page for partx
.\" Copyright 2007 Karel Zak <kzak@redhat.com>
.\" Copyright 2007 Red Hat, Inc.
.\" Copyright 2010 Davidlohr Bueso <dave@gnu.org>
.\" May be distributed under the GNU General Public License
.\"
.TH PARTX "8" "December 2014" "util-linux" "System Administration"
.SH NAME
partx \- tell the kernel about the presence and numbering of on-disk partitions
.SH SYNOPSIS
.B partx
.RB [ \-a | \-d | \-P | \-r | \-s | \-u ]
.RB [ \-t " \fItype\fR]"
.RB [ \-n " \fIM" : \fIN\fR]
.RB [ \- "] " \fIdisk
.br
.B partx
.RB [ \-a | \-d | \-P | \-r | \-s | \-u ]
.RB [ \-t " \fItype\fR]"
.IR partition " [" disk ]
.SH DESCRIPTION
Given a device or disk-image,
.B partx
tries to parse the partition table and list its contents.  It
can also tell the kernel to add or remove partitions from its
bookkeeping.
.PP
The
.I disk
argument is optional when a
.I partition
argument is provided.  To force scanning a partition as if it were a whole disk
(for example to list nested subpartitions), use the argument "\-" (hyphen-minus).
For example:

.RS 7
.TP
partx \-\-show \- /dev/sda3
.RE
.PP
This will see sda3 as a whole-disk rather than as a partition.
.PP
.B partx is not an fdisk program
\(en adding and removing partitions does not change the disk, it just
tells the kernel about the presence and numbering of on-disk
partitions.
.SH OPTIONS
.TP
.BR \-a , " \-\-add"
Add the specified partitions, or read the disk and add all partitions.
.TP
.BR \-b , " \-\-bytes"
Print the SIZE column in bytes rather than in human-readable format.
.TP
.BR \-d , " \-\-delete"
Delete the specified partitions or all partitions.
.TP
.BR \-g , " \-\-noheadings"
Do not print a header line with \fB\-\-show\fR or \fB\-\-raw\fR.
.TP
.BR \-l , " \-\-list"
List the partitions.  Note that all numbers are in 512-byte sectors.
This output format is DEPRECATED in favour of
.BR \-\-show .
Do not use it in newly written scripts.
.TP
.BR \-n , " \-\-nr " \fIM : \fIN
Specify the range of partitions.  For backward compatibility also the
format \fIM\fB\-\fIN\fR is supported.
The range may contain negative numbers, for example
.B \-\-nr \-1:\-1
means the last partition, and
.B \-\-nr \-2:\-1
means the last two partitions.  Supported range specifications are:
.RS 14
.TP
.I M
Specifies just one partition (e.g.\& \fB\-\-nr 3\fR).
.TP
.IB M :
Specifies the lower limit only (e.g.\& \fB\-\-nr 2:\fR).
.TP
.BI : N
Specifies the upper limit only (e.g.\& \fB\-\-nr :4\fR).
.TP
.IB M : N
Specifies the lower and upper limits (e.g.\& \fB\-\-nr 2:4\fR).
.RE
.TP
.BR \-o , " \-\-output " \fIlist
Define the output columns to use for
.BR \-\-show ,
.B \-\-pairs
and
.B \-\-raw
output.  If no output arrangement is specified, then a default set is
used.  Use
.B \-\-help
to get
.I list
of all supported columns.  This option cannot be combined with the
.BR \-\-add ,
.BR \-\-delete ,
.B \-\-update
or
.B \-\-list
options.
.TP
.B \-\-output\-all
Output all available columns.
.TP
.BR \-P , " \-\-pairs"
List the partitions using the KEY="value" format.
.TP
.BR \-r , " \-\-raw"
List the partitions using the raw output format.
.TP
.BR \-s , " \-\-show"
List the partitions.
The output columns can be selected and rearranged with the
\fB\-\-output\fR option.
All numbers (except SIZE) are in 512-byte sectors.
.TP
.BR \-t , " \-\-type " \fItype
Specify the partition table type.
.TP
.B \-\-list\-types
List supported partition types and exit.
.TP
.BR \-u , " \-\-update"
Update the specified partitions.
.TP
.BR \-S , " \-\-sector\-size " \fIsize
Overwrite default sector size.
.TP
.BR \-v , " \-\-verbose"
Verbose mode.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH EXAMPLES
.TP
partx \-\-show /dev/sdb3
.TQ
partx \-\-show \-\-nr 3 /dev/sdb
.TQ
partx \-\-show /dev/sdb3 /dev/sdb
All three commands list partition 3 of /dev/sdb.
.TP
partx \-\-show \- /dev/sdb3
Lists all subpartitions on /dev/sdb3 (the device is used as
whole-disk).
.TP
partx \-o START \-g \-\-nr 5 /dev/sdb
Prints the start sector of partition 5 on /dev/sdb without header.
.TP
partx \-o SECTORS,SIZE /dev/sda5 /dev/sda
Lists the length in sectors and human-readable size of partition 5 on
/dev/sda.
.TP
partx \-\-add \-\-nr 3:5 /dev/sdd
Adds all available partitions from 3 to 5 (inclusive) on /dev/sdd.
.TP
partx \-d \-\-nr :\-1 /dev/sdd
Removes the last partition on /dev/sdd.
.SH SEE ALSO
.BR addpart (8),
.BR delpart (8),
.BR fdisk (8),
.BR parted (8),
.BR partprobe (8)
.SH AUTHORS
.MT dave@gnu.org
Davidlohr Bueso
.ME
.br
.MT kzak@redhat.com
Karel Zak
.ME
.PP
The original version was written by
.MT aeb@cwi.nl
Andries E.\& Brouwer
.ME .
.SH ENVIRONMENT
.IP LIBBLKID_DEBUG=all
enables libblkid debug output.
.SH AVAILABILITY
The partx command is part of the util-linux package and is available from
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
