/* Automatically generated by po2tbl.sed from util-linux.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"booted from MILO\n", 2},
  {"Ruffian BCD clock\n", 3},
  {"clockport adjusted to 0x%x\n", 4},
  {"funky TOY!\n", 5},
  {"%s: atomic %s failed for 1000 iterations!", 6},
  {"Cannot open /dev/port: %s", 7},
  {"I failed to get permission because I didnt try.\n", 8},
  {"%s is unable to get I/O port access:  the iopl(3) call failed.\n", 9},
  {"Probably you need root privileges.\n", 10},
  {"Assuming hardware clock is kept in %s time.\n", 11},
  {"UTC", 12},
  {"local", 13},
  {"%s: Warning: unrecognized third line in adjtime file\n", 14},
  {"(Expected: `UTC' or `LOCAL' or nothing.)\n", 15},
  {"Last drift adjustment done at %d seconds after 1969\n", 16},
  {"Last calibration done at %d seconds after 1969\n", 17},
  {"Hardware clock is on %s time\n", 18},
  {"unknown", 19},
  {"Waiting for clock tick...\n", 20},
  {"...got clock tick\n", 21},
  {"Invalid values in hardware clock: %4d/%.2d/%.2d %.2d:%.2d:%.2d\n", 22},
  {"Hw clock time : %4d/%.2d/%.2d %.2d:%.2d:%.2d = %ld seconds since 1969\n", 23},
  {"Time read from Hardware Clock: %4d/%.2d/%.2d %02d:%02d:%02d\n", 24},
  {"Setting Hardware Clock to %.2d:%.2d:%.2d = %d seconds since 1969\n", 25},
  {"Clock not changed - testing only.\n", 26},
  {"\
Time elapsed since reference time has been %.6f seconds.\n\
Delaying further to reach the next full second.\n", 27},
  {"\
The Hardware Clock registers contain values that are either invalid (e.g. \
50th day of month) or beyond the range we can handle (e.g. Year 2095).\n", 28},
  {"%s  %.6f seconds\n", 29},
  {"No --date option specified.\n", 30},
  {"\
The value of the --date option is not a valid date.\n\
In particular, it contains quotation marks.\n", 31},
  {"Issuing date command: %s\n", 32},
  {"Unable to run 'date' program in /bin/sh shell. popen() failed", 33},
  {"response from date command = %s\n", 34},
  {"\
The date command issued by %s returned unexpected results.\n\
The command was:\n\
  %s\n\
The response was:\n\
  %s\n", 35},
  {"\
The date command issued by %s returned something other than an integer where \
the converted time value was expected.\n\
The command was:\n\
  %s\n\
The response was:\n\
 %s\n", 36},
  {"date string %s equates to %d seconds since 1969.\n", 37},
  {"\
The Hardware Clock does not contain a valid time, so we cannot set the \
System Time from it.\n", 38},
  {"Calling settimeofday:\n", 39},
  {"\ttv.tv_sec = %ld, tv.tv_usec = %ld\n", 40},
  {"\ttz.tz_minuteswest = %d\n", 41},
  {"Not setting system clock because running in test mode.\n", 42},
  {"Must be superuser to set system clock.\n", 43},
  {"settimeofday() failed", 44},
  {"\
Not adjusting drift factor because the Hardware Clock previously contained \
garbage.\n", 45},
  {"\
Not adjusting drift factor because it has been less than a day since the \
last calibration.\n", 46},
  {"\
Clock drifted %d seconds in the past %d seconds in spite of a drift factor \
of %f seconds/day.\n\
Adjusting drift factor by %f seconds/day\n", 47},
  {"Time since last adjustment is %d seconds\n", 48},
  {"Need to insert %d seconds and refer time back %.6f seconds ago\n", 49},
  {"Not updating adjtime file because of testing mode.\n", 50},
  {"\
Would have written the following to %s:\n\
%s", 51},
  {"Drift adjustment parameters not updated.\n", 52},
  {"\
The Hardware Clock does not contain a valid time, so we cannot adjust it.\n", 53},
  {"Needed adjustment is less than one second, so not setting clock.\n", 54},
  {"Using %s.\n", 55},
  {"No usable clock interface found.\n", 56},
  {"Unable to set system clock.\n", 57},
  {"\
The kernel keeps an epoch value for the Hardware Clock only on an Alpha \
machine.\n\
This copy of hwclock was built for a machine other than Alpha\n\
(and thus is presumably not running on an Alpha now).  No action taken.\n", 58},
  {"Unable to get the epoch value from the kernel.\n", 59},
  {"Kernel is assuming an epoch value of %lu\n", 60},
  {"\
To set the epoch value, you must use the 'epoch' option to tell to what \
value to set it.\n", 61},
  {"Not setting the epoch to %d - testing only.\n", 62},
  {"Unable to set the epoch value in the kernel.\n", 63},
  {"\
hwclock - query and set the hardware clock (RTC)\n\
\n\
Usage: hwclock [function] [options...]\n\
\n\
Functions:\n\
  --help        show this help\n\
  --show        read hardware clock and print result\n\
  --set         set the rtc to the time given with --date\n\
  --hctosys     set the system time from the hardware clock\n\
  --systohc     set the hardware clock to the current system time\n\
  --adjust      adjust the rtc to account for systematic drift since \n\
                the clock was last set or adjusted\n\
  --getepoch    print out the kernel's hardware clock epoch value\n\
  --setepoch    set the kernel's hardware clock epoch value to the \n\
                value given with --epoch\n\
  --version     print out the version of hwclock to stdout\n\
\n\
Options: \n\
  --utc         the hardware clock is kept in coordinated universal time\n\
  --localtime   the hardware clock is kept in local time\n\
  --directisa   access the ISA bus directly instead of %s\n\
  --badyear     ignore rtc's year because the bios is broken\n\
  --date        specifies the time to which to set the hardware clock\n\
  --epoch=year  specifies the year which is the beginning of the \n\
                hardware clock's epoch value\n", 64},
  {"\
  --jensen, --arc, --srm, --funky-toy\n\
                tell hwclock the type of alpha you have (see hwclock(8))\n", 65},
  {"%s takes no non-option arguments.  You supplied %d.\n", 66},
  {"\
You have specified multiple function options.\n\
You can only perform one function at a time.\n", 67},
  {"\
%s: The --utc and --localtime options are mutually exclusive.  You specified \
both.\n", 68},
  {"No usable set-to time.  Cannot set clock.\n", 69},
  {"Sorry, only the superuser can change the Hardware Clock.\n", 70},
  {"Sorry, only the superuser can change the System Clock.\n", 71},
  {"\
Sorry, only the superuser can change the Hardware Clock epoch in the \
kernel.\n", 72},
  {"Cannot access the Hardware Clock via any known method.\n", 73},
  {"\
Use the --debug option to see the details of our search for an access \
method.\n", 74},
  {"Waiting in loop for time from KDGHWCLK to change\n", 75},
  {"KDGHWCLK ioctl to read time failed", 76},
  {"Timed out waiting for time change.\n", 77},
  {"KDGHWCLK ioctl to read time failed in loop", 78},
  {"ioctl() failed to read time from  /dev/tty1", 79},
  {"ioctl() to open /dev/tty1 failed", 80},
  {"KDGHWCLK ioctl failed", 81},
  {"Can't open /dev/tty1", 82},
  {"ioctl() to %s to read the time failed.\n", 83},
  {"Waiting in loop for time from %s to change\n", 84},
  {"open() of %s failed", 85},
  {"%s does not have interrupt functions. ", 86},
  {"read() to %s to wait for clock tick failed", 87},
  {"ioctl() to %s to turn off update interrupts failed", 88},
  {"ioctl() to %s to turn on update interrupts failed unexpectedly", 89},
  {"Unable to open %s", 90},
  {"ioctl() to %s to set the time failed.\n", 91},
  {"ioctl(%s) was successful.\n", 92},
  {"Open of %s failed", 93},
  {"\
To manipulate the epoch value in the kernel, we must access the Linux 'rtc' \
device driver via the device special file %s.  This file does not exist on \
this system.\n", 94},
  {"ioctl(RTC_EPOCH_READ) to %s failed", 95},
  {"we have read epoch %ld from %s with RTC_EPOCH_READ ioctl.\n", 96},
  {"The epoch value may not be less than 1900.  You requested %ld\n", 97},
  {"setting epoch to %ld with RTC_EPOCH_SET ioctl to %s.\n", 98},
  {"\
The kernel device driver for %s does not have the RTC_EPOCH_SET ioctl.\n", 99},
  {"ioctl(RTC_EPOCH_SET) to %s failed", 100},
  {"invalid number `%s'\n", 101},
  {"number `%s' to `%s' out of range\n", 102},
  {"unrecognized option `%s'\n", 103},
  {"option `%s' requires an argument\n", 104},
  {"option `%s' doesn't allow an argument\n", 105},
  {"unrecognized option `-%c'\n", 106},
  {"set read-only", 107},
  {"set read-write", 108},
  {"get read-only", 109},
  {"get sectorsize", 110},
  {"get size", 111},
  {"set readahead", 112},
  {"get readahead", 113},
  {"flush buffers", 114},
  {"reread partition table", 115},
  {"Usage: %s [-V] [-v|-q] commands devices\n", 116},
  {"Available commands:\n", 117},
  {"%s: Unknown command: %s\n", 118},
  {"%s requires an argument\n", 119},
  {"Formatting ... ", 120},
  {"done\n", 121},
  {"Verifying ... ", 122},
  {"Read: ", 123},
  {"Problem reading cylinder %d, expected %d, read %d\n", 124},
  {"\
bad data in cyl %d\n\
Continuing ... ", 125},
  {"usage: %s [ -n ] device\n", 126},
  {"%s from %s\n", 127},
  {"%s: not a floppy device\n", 128},
  {"Could not determine current format type", 129},
  {"%s-sided, %d tracks, %d sec/track. Total capacity %d kB.\n", 130},
  {"Double", 131},
  {"Single", 132},
  {"Usage: %s [-larvsmf] /dev/name\n", 133},
  {"%s is mounted.\t ", 134},
  {"Do you really want to continue", 135},
  {"check aborted.\n", 136},
  {"Zone nr < FIRSTZONE in file `", 137},
  {"Zone nr >= ZONES in file `", 138},
  {"Remove block", 139},
  {"Read error: unable to seek to block in file '", 140},
  {"Read error: bad block in file '", 141},
  {"\
Internal error: trying to write bad block\n\
Write request ignored\n", 142},
  {"seek failed in write_block", 143},
  {"Write error: bad block in file '", 144},
  {"seek failed in write_super_block", 145},
  {"unable to write super-block", 146},
  {"Unable to write inode map", 147},
  {"Unable to write zone map", 148},
  {"Unable to write inodes", 149},
  {"seek failed", 150},
  {"unable to read super block", 151},
  {"bad magic number in super-block", 152},
  {"Only 1k blocks/zones supported", 153},
  {"bad s_imap_blocks field in super-block", 154},
  {"bad s_zmap_blocks field in super-block", 155},
  {"Unable to allocate buffer for inode map", 156},
  {"Unable to allocate buffer for inodes", 157},
  {"Unable to allocate buffer for inode count", 158},
  {"Unable to allocate buffer for zone count", 159},
  {"Unable to read inode map", 160},
  {"Unable to read zone map", 161},
  {"Unable to read inodes", 162},
  {"Warning: Firstzone != Norm_firstzone\n", 163},
  {"%ld inodes\n", 164},
  {"%ld blocks\n", 165},
  {"Firstdatazone=%ld (%ld)\n", 166},
  {"Zonesize=%d\n", 167},
  {"Maxsize=%ld\n", 168},
  {"Filesystem state=%d\n", 169},
  {"\
namelen=%d\n\
\n", 170},
  {"Inode %d marked not used, but used for file '", 171},
  {"Mark in use", 172},
  {" has mode %05o\n", 173},
  {"Warning: inode count too big.\n", 174},
  {"root inode isn't a directory", 175},
  {"Block has been used before. Now in file `", 176},
  {"Clear", 177},
  {"Block %d in file `", 178},
  {"' is marked not in use.", 179},
  {"Correct", 180},
  {" contains a bad inode number for file '", 181},
  {" Remove", 182},
  {": bad directory: '.' isn't first\n", 183},
  {": bad directory: '..' isn't second\n", 184},
  {"internal error", 185},
  {": bad directory: size<32", 186},
  {": bad directory: size < 32", 187},
  {"seek failed in bad_zone", 188},
  {"Inode %d mode not cleared.", 189},
  {"Inode %d not used, marked used in the bitmap.", 190},
  {"Inode %d used, marked unused in the bitmap.", 191},
  {"Inode %d (mode = %07o), i_nlinks=%d, counted=%d.", 192},
  {"Set i_nlinks to count", 193},
  {"Zone %d: marked in use, no file uses it.", 194},
  {"Unmark", 195},
  {"Zone %d: %sin use, counted=%d\n", 196},
  {"not ", 197},
  {"Set", 198},
  {"bad inode size", 199},
  {"bad v2 inode size", 200},
  {"need terminal for interactive repairs", 201},
  {"unable to open '%s'", 202},
  {"%s is clean, no check.\n", 203},
  {"Forcing filesystem check on %s.\n", 204},
  {"Filesystem on %s is dirty, needs checking.\n", 205},
  {"\
\n\
%6ld inodes used (%ld%%)\n", 206},
  {"%6ld zones used (%ld%%)\n", 207},
  {"\
\n\
%6d regular files\n\
%6d directories\n\
%6d character device files\n\
%6d block device files\n\
%6d links\n\
%6d symbolic links\n\
------\n\
%6d files\n", 208},
  {"\
----------------------------\n\
FILE SYSTEM HAS BEEN CHANGED\n\
----------------------------\n", 209},
  {"%s: failed to open: %s\n", 210},
  {"%s: seek error on %s\n", 211},
  {"%s: read error on %s\n", 212},
  {"sector count: %d, sector size: %d\n", 213},
  {"%s: option parse error\n", 214},
  {"Usage: %s [-x] [-d <num>] iso9660-image\n", 215},
  {"Usage: mkfs [-V] [-t fstype] [fs-options] device [size]\n", 216},
  {"%s: Out of memory!\n", 217},
  {"mkfs version %s (%s)\n", 218},
  {"Usage: %s [-c | -l filename] [-nXX] [-iXX] /dev/name [blocks]\n", 219},
  {"%s is mounted; will not make a filesystem here!", 220},
  {"seek to boot block failed in write_tables", 221},
  {"unable to clear boot sector", 222},
  {"seek failed in write_tables", 223},
  {"unable to write inode map", 224},
  {"unable to write zone map", 225},
  {"unable to write inodes", 226},
  {"write failed in write_block", 227},
  {"too many bad blocks", 228},
  {"not enough good blocks", 229},
  {"unable to allocate buffers for maps", 230},
  {"unable to allocate buffer for inodes", 231},
  {"\
Maxsize=%ld\n\
\n", 232},
  {"seek failed during testing of blocks", 233},
  {"Weird values in do_check: probably bugs\n", 234},
  {"seek failed in check_blocks", 235},
  {"bad blocks before data-area: cannot make fs", 236},
  {"%d bad blocks\n", 237},
  {"one bad block\n", 238},
  {"can't open file of bad blocks", 239},
  {"%s: not compiled with minix v2 support\n", 240},
  {"strtol error: number of blocks not specified", 241},
  {"unable to open %s", 242},
  {"unable to stat %s", 243},
  {"will not try to make filesystem on '%s'", 244},
  {"Bad user-specified page size %d\n", 245},
  {"Using user-specified page size %d, instead of the system values %d/%d\n", 246},
  {"Assuming pages of size %d (not %d)\n", 247},
  {"Usage: %s [-c] [-v0|-v1] [-pPAGESZ] /dev/name [blocks]\n", 248},
  {"too many bad pages", 249},
  {"Out of memory", 250},
  {"one bad page\n", 251},
  {"%d bad pages\n", 252},
  {"%s: error: Nowhere to set up swap on?\n", 253},
  {"%s: error: size %ld is larger than device size %d\n", 254},
  {"%s: error: unknown version %d\n", 255},
  {"%s: error: swap area needs to be at least %ldkB\n", 256},
  {"%s: warning: truncating swap area to %ldkB\n", 257},
  {"Will not try to make swapdevice on '%s'", 258},
  {"fatal: first page unreadable", 259},
  {"\
%s: Device '%s' contains a valid Sun disklabel.\n\
This probably means creating v0 swap would destroy your partition table\n\
No swap created. If you really want to create swap v0 on that device, use\n\
the -f option to force it.\n", 260},
  {"Unable to set up swap-space: unreadable", 261},
  {"Setting up swapspace version %d, size = %ld bytes\n", 262},
  {"unable to rewind swap-device", 263},
  {"unable to write signature page", 264},
  {"fsync failed", 265},
  {"Invalid number: %s\n", 266},
  {"Syntax error: '%s'\n", 267},
  {"No such parameter set: '%s'\n", 268},
  {"usage: %s [ -p ] dev name\n", 269},
  {"\
       %s [ -p ] dev size sect heads tracks stretch gap rate spec1 fmt_gap\n", 270},
  {"       %s [ -c | -y | -n | -d ] dev\n", 271},
  {"       %s [ -c | -y | -n ] dev\n", 272},
  {"Unusable", 273},
  {"Free Space", 274},
  {"Linux ext2", 275},
  {"Linux", 276},
  {"OS/2 HPFS", 277},
  {"OS/2 IFS", 278},
  {"NTFS", 279},
  {"Disk has been changed.\n", 280},
  {"Reboot the system to ensure the partition table is correctly updated.\n", 281},
  {"\
\n\
WARNING: If you have created or modified any\n\
DOS 6.x partitions, please see the cfdisk manual\n\
page for additional information.\n", 282},
  {"FATAL ERROR", 283},
  {"Press any key to exit cfdisk", 284},
  {"Cannot seek on disk drive", 285},
  {"Cannot read disk drive", 286},
  {"Cannot write disk drive", 287},
  {"Too many partitions", 288},
  {"Partition begins before sector 0", 289},
  {"Partition ends before sector 0", 290},
  {"Partition begins after end-of-disk", 291},
  {"Partition ends after end-of-disk", 292},
  {"logical partitions not in disk order", 293},
  {"logical partitions overlap", 294},
  {"enlarged logical partitions overlap", 295},
  {"\
!!!! Internal error creating logical drive with no extended partition !!!!", 296},
  {"\
Cannot create logical drive here -- would create two extended partitions", 297},
  {"Menu item too long. Menu may look odd.", 298},
  {"Menu without direction. Defaulting horizontal.", 299},
  {"Illegal key", 300},
  {"Press a key to continue", 301},
  {"Primary", 302},
  {"Create a new primary partition", 303},
  {"Logical", 304},
  {"Create a new logical partition", 305},
  {"Cancel", 306},
  {"Don't create a partition", 307},
  {"!!! Internal error !!!", 308},
  {"Size (in MB): ", 309},
  {"Beginning", 310},
  {"Add partition at beginning of free space", 311},
  {"End", 312},
  {"Add partition at end of free space", 313},
  {"No room to create the extended partition", 314},
  {"Bad signature on partition table", 315},
  {"You specified more cylinders than fit on disk", 316},
  {"Cannot open disk drive", 317},
  {"Opened disk read-only - you have no permission to write", 318},
  {"Cannot get disk size", 319},
  {"Bad primary partition", 320},
  {"Bad logical partition", 321},
  {"Warning!!  This may destroy data on your disk!", 322},
  {"Are you sure you want write the partition table to disk? (yes or no): ", 323},
  {"no", 324},
  {"Did not write partition table to disk", 325},
  {"yes", 326},
  {"Please enter `yes' or `no'", 327},
  {"Writing partition table to disk...", 328},
  {"Wrote partition table to disk", 329},
  {"\
Wrote partition table, but re-read table failed.  Reboot to update table.", 330},
  {"\
Not precisely one primary partition is bootable. DOS MBR cannot boot this.", 331},
  {"Enter filename or press RETURN to display on screen: ", 332},
  {"Cannot open file '%s'", 333},
  {"Disk Drive: %s\n", 334},
  {"Sector 0:\n", 335},
  {"Sector %d:\n", 336},
  {"   None   ", 337},
  {"   Pri/Log", 338},
  {"   Primary", 339},
  {"   Logical", 340},
  {"Unknown", 341},
  {"Boot (%02X)", 342},
  {"Unknown (%02X)", 343},
  {"None (%02X)", 344},
  {"Partition Table for %s\n", 345},
  {"            First    Last\n", 346},
  {"\
 # Type     Sector   Sector   Offset  Length   Filesystem Type (ID)   Flags\n", 347},
  {"\
-- ------- -------- --------- ------ --------- ---------------------- \
---------\n", 348},
  {"         ---Starting---      ----Ending----    Start Number of\n", 349},
  {" # Flags Head Sect Cyl   ID  Head Sect Cyl    Sector  Sectors\n", 350},
  {"-- ----- ---- ---- ---- ---- ---- ---- ---- -------- ---------\n", 351},
  {"Raw", 352},
  {"Print the table using raw data format", 353},
  {"Sectors", 354},
  {"Print the table ordered by sectors", 355},
  {"Table", 356},
  {"Just print the partition table", 357},
  {"Don't print the table", 358},
  {"Help Screen for cfdisk", 359},
  {"This is cfdisk, a curses based disk partitioning program, which", 360},
  {"allows you to create, delete and modify partitions on your hard", 361},
  {"disk drive.", 362},
  {"Copyright (C) 1994-1999 Kevin E. Martin & aeb", 363},
  {"Command      Meaning", 364},
  {"-------      -------", 365},
  {"  b          Toggle bootable flag of the current partition", 366},
  {"  d          Delete the current partition", 367},
  {"  g          Change cylinders, heads, sectors-per-track parameters", 368},
  {"             WARNING: This option should only be used by people who", 369},
  {"             know what they are doing.", 370},
  {"  h          Print this screen", 371},
  {"  m          Maximize disk usage of the current partition", 372},
  {"             Note: This may make the partition incompatible with", 373},
  {"             DOS, OS/2, ...", 374},
  {"  n          Create new partition from free space", 375},
  {"  p          Print partition table to the screen or to a file", 376},
  {"             There are several different formats for the partition", 377},
  {"             that you can choose from:", 378},
  {"                r - Raw data (exactly what would be written to disk)", 379},
  {"                s - Table ordered by sectors", 380},
  {"                t - Table in raw format", 381},
  {"  q          Quit program without writing partition table", 382},
  {"  t          Change the filesystem type", 383},
  {"  u          Change units of the partition size display", 384},
  {"             Rotates through MB, sectors and cylinders", 385},
  {"  W          Write partition table to disk (must enter upper case W)", 386},
  {"             Since this might destroy data on the disk, you must", 387},
  {"             either confirm or deny the write by entering `yes' or", 388},
  {"             `no'", 389},
  {"Up Arrow     Move cursor to the previous partition", 390},
  {"Down Arrow   Move cursor to the next partition", 391},
  {"CTRL-L       Redraws the screen", 392},
  {"  ?          Print this screen", 393},
  {"Note: All of the commands can be entered with either upper or lower", 394},
  {"case letters (except for Writes).", 395},
  {"Cylinders", 396},
  {"Change cylinder geometry", 397},
  {"Heads", 398},
  {"Change head geometry", 399},
  {"Change sector geometry", 400},
  {"Done", 401},
  {"Done with changing geometry", 402},
  {"Enter the number of cylinders: ", 403},
  {"Illegal cylinders value", 404},
  {"Enter the number of heads: ", 405},
  {"Illegal heads value", 406},
  {"Enter the number of sectors per track: ", 407},
  {"Illegal sectors value", 408},
  {"Enter filesystem type: ", 409},
  {"Cannot change FS Type to empty", 410},
  {"Cannot change FS Type to extended", 411},
  {"Boot", 412},
  {"Unk(%02X)", 413},
  {", NC", 414},
  {"NC", 415},
  {"Pri/Log", 416},
  {"Disk Drive: %s", 417},
  {"Size: %lld bytes", 418},
  {"Heads: %d   Sectors per Track: %d   Cylinders: %d", 419},
  {"Name", 420},
  {"Flags", 421},
  {"Part Type", 422},
  {"FS Type", 423},
  {"[Label]", 424},
  {"  Sectors", 425},
  {"Size (MB)", 426},
  {"Size (GB)", 427},
  {"Bootable", 428},
  {"Toggle bootable flag of the current partition", 429},
  {"Delete", 430},
  {"Delete the current partition", 431},
  {"Geometry", 432},
  {"Change disk geometry (experts only)", 433},
  {"Help", 434},
  {"Print help screen", 435},
  {"Maximize", 436},
  {"Maximize disk usage of the current partition (experts only)", 437},
  {"New", 438},
  {"Create new partition from free space", 439},
  {"Print", 440},
  {"Print partition table to the screen or to a file", 441},
  {"Quit", 442},
  {"Quit program without writing partition table", 443},
  {"Type", 444},
  {"Change the filesystem type (DOS, Linux, OS/2 and so on)", 445},
  {"Units", 446},
  {"Change units of the partition size display (MB, sect, cyl)", 447},
  {"Write", 448},
  {"Write partition table to disk (this might destroy data)", 449},
  {"Cannot make this partition bootable", 450},
  {"Cannot delete an empty partition", 451},
  {"Cannot maximize this partition", 452},
  {"This partition is unusable", 453},
  {"This partition is already in use", 454},
  {"Cannot change the type of an empty partition", 455},
  {"No more partitions", 456},
  {"Illegal command", 457},
  {"Copyright (C) 1994-2000 Kevin E. Martin & aeb\n", 458},
  {"\
\n\
Usage:\n\
Print version:\n\
        %s -v\n\
Print partition table:\n\
        %s -P {r|s|t} [options] device\n\
Interactive use:\n\
        %s [options] device\n\
\n\
Options:\n\
-a: Use arrow instead of highlighting;\n\
-z: Start with a zero partition table, instead of reading the pt from disk;\n\
-c C -h H -s S: Override the kernel's idea of the number of cylinders,\n\
                the number of heads and the number of sectors/track.\n\
\n", 459},
  {"\
Usage: fdisk [-b SSZ] [-u] DISK     Change partition table\n\
       fdisk -l [-b SSZ] [-u] DISK  List partition table(s)\n\
       fdisk -s PARTITION           Give partition size(s) in blocks\n\
       fdisk -v                     Give fdisk version\n\
Here DISK is something like /dev/hdb or /dev/sda\n\
and PARTITION is something like /dev/hda7\n\
-u: give Start and End in sector (instead of cylinder) units\n\
-b 2048: (for certain MO drives) use 2048-byte sectors\n", 460},
  {"\
Usage: fdisk [-l] [-b SSZ] [-u] device\n\
E.g.: fdisk /dev/hda  (for the first IDE disk)\n\
  or: fdisk /dev/sdc  (for the third SCSI disk)\n\
  or: fdisk /dev/eda  (for the first PS/2 ESDI drive)\n\
  or: fdisk /dev/rd/c0d0  or: fdisk /dev/ida/c0d0  (for RAID devices)\n\
  ...\n", 461},
  {"Unable to open %s\n", 462},
  {"Unable to read %s\n", 463},
  {"Unable to seek on %s\n", 464},
  {"Unable to write %s\n", 465},
  {"BLKGETSIZE ioctl failed on %s\n", 466},
  {"Unable to allocate any more memory\n", 467},
  {"Fatal error\n", 468},
  {"Command action", 469},
  {"   a   toggle a read only flag", 470},
  {"   b   edit bsd disklabel", 471},
  {"   c   toggle the mountable flag", 472},
  {"   d   delete a partition", 473},
  {"   l   list known partition types", 474},
  {"   m   print this menu", 475},
  {"   n   add a new partition", 476},
  {"   o   create a new empty DOS partition table", 477},
  {"   p   print the partition table", 478},
  {"   q   quit without saving changes", 479},
  {"   s   create a new empty Sun disklabel", 480},
  {"   t   change a partition's system id", 481},
  {"   u   change display/entry units", 482},
  {"   v   verify the partition table", 483},
  {"   w   write table to disk and exit", 484},
  {"   x   extra functionality (experts only)", 485},
  {"   a   select bootable partition", 486},
  {"   b   edit bootfile entry", 487},
  {"   c   select sgi swap partition", 488},
  {"   a   toggle a bootable flag", 489},
  {"   c   toggle the dos compatibility flag", 490},
  {"   a   change number of alternate cylinders", 491},
  {"   c   change number of cylinders", 492},
  {"   d   print the raw data in the partition table", 493},
  {"   e   change number of extra sectors per cylinder", 494},
  {"   h   change number of heads", 495},
  {"   i   change interleave factor", 496},
  {"   o   change rotation speed (rpm)", 497},
  {"   r   return to main menu", 498},
  {"   s   change number of sectors/track", 499},
  {"   y   change number of physical cylinders", 500},
  {"   b   move beginning of data in a partition", 501},
  {"   e   list extended partitions", 502},
  {"   g   create an IRIX partition table", 503},
  {"   f   fix partition order", 504},
  {"You must set", 505},
  {"heads", 506},
  {"sectors", 507},
  {"cylinders", 508},
  {"\
%s%s.\n\
You can do this from the extra functions menu.\n", 509},
  {" and ", 510},
  {"\
\n\
The number of cylinders for this disk is set to %d.\n\
There is nothing wrong with that, but this is larger than 1024,\n\
and could in certain setups cause problems with:\n\
1) software that runs at boot time (e.g., old versions of LILO)\n\
2) booting and partitioning software from other OSs\n\
   (e.g., DOS FDISK, OS/2 FDISK)\n", 511},
  {"Bad offset in primary extended partition\n", 512},
  {"Warning: deleting partitions after %d\n", 513},
  {"Warning: extra link pointer in partition table %d\n", 514},
  {"Warning: ignoring extra data in partition table %d\n", 515},
  {"\
Building a new DOS disklabel. Changes will remain in memory only,\n\
until you decide to write them. After that, of course, the previous\n\
content won't be recoverable.\n\
\n", 516},
  {"Note: sector size is %d (not %d)\n", 517},
  {"You will not be able to write the partition table.\n", 518},
  {"\
Device contains neither a valid DOS partition table, nor Sun, SGI or OSF \
disklabel\n", 519},
  {"Internal error\n", 520},
  {"Ignoring extra extended partition %d\n", 521},
  {"\
Warning: invalid flag 0x%04x of partition table %d will be corrected by \
w(rite)\n", 522},
  {"\
\n\
got EOF thrice - exiting..\n", 523},
  {"Hex code (type L to list codes): ", 524},
  {"%s (%d-%d, default %d): ", 525},
  {"Using default value %d\n", 526},
  {"Value out of range.\n", 527},
  {"Partition number", 528},
  {"Warning: partition %d has empty type\n", 529},
  {"cylinder", 530},
  {"sector", 531},
  {"Changing display/entry units to %s\n", 532},
  {"WARNING: Partition %d is an extended partition\n", 533},
  {"DOS Compatibility flag is set\n", 534},
  {"DOS Compatibility flag is not set\n", 535},
  {"Partition %d does not exist yet!\n", 536},
  {"\
Type 0 means free space to many systems\n\
(but not to Linux). Having partitions of\n\
type 0 is probably unwise. You can delete\n\
a partition using the `d' command.\n", 537},
  {"\
You cannot change a partition into an extended one or vice versa\n\
Delete it first.\n", 538},
  {"\
Consider leaving partition 3 as Whole disk (5),\n\
as SunOS/Solaris expects it and even Linux likes it.\n\
\n", 539},
  {"\
Consider leaving partition 9 as volume header (0),\n\
and partition 11 as entire volume (6)as IRIX expects it.\n\
\n", 540},
  {"Changed system type of partition %d to %x (%s)\n", 541},
  {"Partition %d has different physical/logical beginnings (non-Linux?):\n", 542},
  {"     phys=(%d, %d, %d) ", 543},
  {"logical=(%d, %d, %d)\n", 544},
  {"Partition %d has different physical/logical endings:\n", 545},
  {"Partition %i does not start on cylinder boundary:\n", 546},
  {"should be (%d, %d, 1)\n", 547},
  {"Partition %i does not end on cylinder boundary:\n", 548},
  {"should be (%d, %d, %d)\n", 549},
  {"\
\n\
Disk %s: %d heads, %d sectors, %d cylinders\n\
Units = %s of %d * %d bytes\n\
\n", 550},
  {"\
Nothing to do. Ordering is correct already.\n\
\n", 551},
  {"%*s Boot    Start       End    Blocks   Id  System\n", 552},
  {"Device", 553},
  {"\
\n\
Partition table entries are not in disk order\n", 554},
  {"\
\n\
Disk %s: %d heads, %d sectors, %d cylinders\n\
\n", 555},
  {"Nr AF  Hd Sec  Cyl  Hd Sec  Cyl    Start     Size ID\n", 556},
  {"Warning: partition %d contains sector 0\n", 557},
  {"Partition %d: head %d greater than maximum %d\n", 558},
  {"Partition %d: sector %d greater than maximum %d\n", 559},
  {"Partitions %d: cylinder %d greater than maximum %d\n", 560},
  {"Partition %d: previous sectors %d disagrees with total %d\n", 561},
  {"Warning: bad start-of-data in partition %d\n", 562},
  {"Warning: partition %d overlaps partition %d.\n", 563},
  {"Warning: partition %d is empty\n", 564},
  {"Logical partition %d not entirely in partition %d\n", 565},
  {"Total allocated sectors %d greater than the maximum %d\n", 566},
  {"%d unallocated sectors\n", 567},
  {"Partition %d is already defined.  Delete it before re-adding it.\n", 568},
  {"First %s", 569},
  {"Sector %d is already allocated\n", 570},
  {"No free sectors available\n", 571},
  {"Last %s or +size or +sizeM or +sizeK", 572},
  {"Warning: partition %d has an odd number of sectors.\n", 573},
  {"The maximum number of partitions has been created\n", 574},
  {"You must delete some partition and add an extended partition first\n", 575},
  {"\
Command action\n\
   %s\n\
   p   primary partition (1-4)\n", 576},
  {"l   logical (5 or over)", 577},
  {"e   extended", 578},
  {"Invalid partition number for type `%c'\n", 579},
  {"\
The partition table has been altered!\n\
\n", 580},
  {"Calling ioctl() to re-read partition table.\n", 581},
  {"\
Re-read table failed with error %d: %s.\n\
Reboot your system to ensure the partition table is updated.\n", 582},
  {"\
\n\
WARNING: If you have created or modified any DOS 6.x\n\
partitions, please see the fdisk manual page for additional\n\
information.\n", 583},
  {"Syncing disks.\n", 584},
  {"Device: %s\n", 585},
  {"Partition %d has no data area\n", 586},
  {"New beginning of data", 587},
  {"Expert command (m for help): ", 588},
  {"Number of cylinders", 589},
  {"Number of heads", 590},
  {"Number of sectors", 591},
  {"Warning: setting sector offset for DOS compatiblity\n", 592},
  {"Disk %s doesn't contain a valid partition table\n", 593},
  {"Cannot open %s\n", 594},
  {"cannot open %s\n", 595},
  {"%c: unknown command\n", 596},
  {"This kernel finds the sector size itself - -b option ignored\n", 597},
  {"\
Warning: the -b (set sector size) option should be used with one specified \
device\n", 598},
  {"\
Detected an OSF/1 disklabel on %s, entering disklabel mode.\n\
To return to DOS partition table mode, use the 'r' command.\n", 599},
  {"Command (m for help): ", 600},
  {"\
\n\
The current boot file is: %s\n", 601},
  {"Please enter the name of the new boot file: ", 602},
  {"Boot file unchanged\n", 603},
  {"\
\n\
\tSorry, no experts menu for SGI partition tables available.\n\
\n", 604},
  {"\
\n\
\tThere is a valid AIX label on this disk.\n\
\tUnfortunately Linux cannot handle these\n\
\tdisks at the moment.  Nevertheless some\n\
\tadvice:\n\
\t1. fdisk will destroy its contents on write.\n\
\t2. Be sure that this disk is NOT a still vital\n\
\t   part of a volume group. (Otherwise you may\n\
\t   erase the other disks as well, if unmirrored.)\n\
\t3. Before deleting this physical volume be sure\n\
\t   to remove the disk logically from your AIX\n\
\t   machine.  (Otherwise you become an AIXpert).", 605},
  {"\
\n\
BSD label for device: %s\n", 606},
  {"   d   delete a BSD partition", 607},
  {"   e   edit drive data", 608},
  {"   i   install bootstrap", 609},
  {"   l   list known filesystem types", 610},
  {"   n   add a new BSD partition", 611},
  {"   p   print BSD partition table", 612},
  {"   s   show complete disklabel", 613},
  {"   t   change a partition's filesystem id", 614},
  {"   u   change units (cylinders/sectors)", 615},
  {"   w   write disklabel to disk", 616},
  {"   x   link BSD partition to non-BSD partition", 617},
  {"Partition %s has invalid starting sector 0.\n", 618},
  {"Reading disklabel of %s at sector %d.\n", 619},
  {"There is no *BSD partition on %s.\n", 620},
  {"BSD disklabel command (m for help): ", 621},
  {"type: %s\n", 622},
  {"type: %d\n", 623},
  {"disk: %.*s\n", 624},
  {"label: %.*s\n", 625},
  {"flags:", 626},
  {" removable", 627},
  {" ecc", 628},
  {" badsect", 629},
  {"bytes/sector: %ld\n", 630},
  {"sectors/track: %ld\n", 631},
  {"tracks/cylinder: %ld\n", 632},
  {"sectors/cylinder: %ld\n", 633},
  {"cylinders: %ld\n", 634},
  {"rpm: %d\n", 635},
  {"interleave: %d\n", 636},
  {"trackskew: %d\n", 637},
  {"cylinderskew: %d\n", 638},
  {"headswitch: %ld\t\t# milliseconds\n", 639},
  {"track-to-track seek: %ld\t# milliseconds\n", 640},
  {"drivedata: ", 641},
  {"\
\n\
%d partitions:\n", 642},
  {"#       start       end      size     fstype   [fsize bsize   cpg]\n", 643},
  {"Writing disklabel to %s.\n", 644},
  {"%s contains no disklabel.\n", 645},
  {"Do you want to create a disklabel? (y/n) ", 646},
  {"bytes/sector", 647},
  {"sectors/track", 648},
  {"tracks/cylinder", 649},
  {"sectors/cylinder", 650},
  {"Must be <= sectors/track * tracks/cylinder (default).\n", 651},
  {"rpm", 652},
  {"interleave", 653},
  {"trackskew", 654},
  {"cylinderskew", 655},
  {"headswitch", 656},
  {"track-to-track seek", 657},
  {"Bootstrap: %sboot -> boot%s (%s): ", 658},
  {"Bootstrap overlaps with disk label!\n", 659},
  {"Bootstrap installed on %s.\n", 660},
  {"Partition (a-%c): ", 661},
  {"This partition already exists.\n", 662},
  {"Warning: too many partitions (%d, maximum is %d).\n", 663},
  {"\
\n\
Syncing disks.\n", 664},
  {"SGI volhdr", 665},
  {"SGI trkrepl", 666},
  {"SGI secrepl", 667},
  {"SGI raw", 668},
  {"SGI bsd", 669},
  {"SGI sysv", 670},
  {"SGI volume", 671},
  {"SGI efs", 672},
  {"SGI lvol", 673},
  {"SGI rlvol", 674},
  {"SGI xfs", 675},
  {"SGI xlvol", 676},
  {"SGI rxlvol", 677},
  {"Linux swap", 678},
  {"Linux native", 679},
  {"Linux LVM", 680},
  {"\
According to MIPS Computer Systems, Inc the Label must not contain more than \
512 bytes\n", 681},
  {"Detected sgi disklabel with wrong checksum.\n", 682},
  {"\
\n\
Disk %s (SGI disk label): %d heads, %d sectors\n\
%d cylinders, %d physical cylinders\n\
%d extra sects/cyl, interleave %d:1\n\
%s\n\
Units = %s of %d * 512 bytes\n\
\n", 683},
  {"\
\n\
Disk %s (SGI disk label): %d heads, %d sectors, %d cylinders\n\
Units = %s of %d * 512 bytes\n\
\n", 684},
  {"\
----- partitions -----\n\
%*s  Info      Start       End   Sectors  Id  System\n", 685},
  {"\
----- bootinfo -----\n\
Bootfile: %s\n\
----- directory entries -----\n", 686},
  {"%2d: %-10s sector%5u size%8u\n", 687},
  {"\
\n\
Invalid Bootfile!\n\
\tThe bootfile must be an absolute non-zero pathname,\n\
\te.g. \"/unix\" or \"/unix.save\".\n", 688},
  {"\
\n\
\tName of Bootfile too long:  16 bytes maximum.\n", 689},
  {"\
\n\
\tBootfile must have a fully qualified pathname.\n", 690},
  {"\
\n\
\tBe aware, that the bootfile is not checked for existence.\n\
\tSGI's default is \"/unix\" and for backup \"/unix.save\".\n", 691},
  {"\
\n\
\tBootfile is changed to \"%s\".\n", 692},
  {"More than one entire disk entry present.\n", 693},
  {"No partitions defined\n", 694},
  {"IRIX likes when Partition 11 covers the entire disk.\n", 695},
  {"\
The entire disk partition should start at block 0,\n\
not at diskblock %d.\n", 696},
  {"\
The entire disk partition is only %d diskblock large,\n\
but the disk is %d diskblocks long.\n", 697},
  {"One Partition (#11) should cover the entire disk.\n", 698},
  {"Partition %d does not start on cylinder boundary.\n", 699},
  {"Partition %d does not end on cylinder boundary.\n", 700},
  {"The Partition %d and %d overlap by %d sectors.\n", 701},
  {"Unused gap of %8d sectors - sectors %8d-%d\n", 702},
  {"\
\n\
The boot partition does not exist.\n", 703},
  {"\
\n\
The swap partition does not exist.\n", 704},
  {"\
\n\
The swap partition has no swap type.\n", 705},
  {"\tYou have chosen an unusual boot file name.\n", 706},
  {"Sorry You may change the Tag of non-empty partitions.\n", 707},
  {"\
It is highly recommended that the partition at offset 0\n\
is of type \"SGI volhdr\", the IRIX system will rely on it to\n\
retrieve from its directory standalone tools like sash and fx.\n\
Only the \"SGI volume\" entire disk section may violate this.\n\
Type YES if you are sure about tagging this partition differently.\n", 708},
  {"Do You know, You got a partition overlap on the disk?\n", 709},
  {"Attempting to generate entire disk entry automatically.\n", 710},
  {"The entire disk is already covered with partitions.\n", 711},
  {"You got a partition overlap on the disk. Fix it first!\n", 712},
  {"\
It is highly recommended that eleventh partition\n\
covers the entire disk and is of type `SGI volume'\n", 713},
  {"You will get a partition overlap on the disk. Fix it first!\n", 714},
  {" Last %s", 715},
  {"\
Building a new SGI disklabel. Changes will remain in memory only,\n\
until you decide to write them. After that, of course, the previous\n\
content will be unrecoverably lost.\n\
\n", 716},
  {"Trying to keep parameters of partition %d.\n", 717},
  {"ID=%02x\tSTART=%d\tLENGTH=%d\n", 718},
  {"Empty", 719},
  {"SunOS root", 720},
  {"SunOS swap", 721},
  {"SunOS usr", 722},
  {"Whole disk", 723},
  {"SunOS stand", 724},
  {"SunOS var", 725},
  {"SunOS home", 726},
  {"\
Detected sun disklabel with wrong checksum.\n\
Probably you'll have to set all the values,\n\
e.g. heads, sectors, cylinders and partitions\n\
or force a fresh label (s command in main menu)\n", 727},
  {"Autoconfigure found a %s%s%s\n", 728},
  {"\
Building a new sun disklabel. Changes will remain in memory only,\n\
until you decide to write them. After that, of course, the previous\n\
content won't be recoverable.\n\
\n", 729},
  {"\
Drive type\n\
   ?   auto configure\n\
   0   custom (with hardware detected defaults)", 730},
  {"Select type (? for auto, 0 for custom): ", 731},
  {"Autoconfigure failed.\n", 732},
  {"Sectors/track", 733},
  {"Alternate cylinders", 734},
  {"Physical cylinders", 735},
  {"Rotation speed (rpm)", 736},
  {"Interleave factor", 737},
  {"Extra sectors per cylinder", 738},
  {"You may change all the disk params from the x menu", 739},
  {"3,5\" floppy", 740},
  {"Linux custom", 741},
  {"Partition %d doesn't end on cylinder boundary\n", 742},
  {"Partition %d overlaps with others in sectors %d-%d\n", 743},
  {"Unused gap - sectors 0-%d\n", 744},
  {"Unused gap - sectors %d-%d\n", 745},
  {"\
Other partitions already cover the whole disk.\n\
Delete some/shrink them before retry.\n", 746},
  {"\
You haven't covered the whole disk with the 3rd partition, but your value\n\
%d %s covers some other partition. Your entry has been changed\n\
to %d %s\n", 747},
  {"\
If you want to maintain SunOS/Solaris compatibility, consider leaving this\n\
partition as Whole disk (5), starting at 0, with %u sectors\n", 748},
  {"\
It is highly recommended that the partition at offset 0\n\
is UFS, EXT2FS filesystem or SunOS swap. Putting Linux swap\n\
there may destroy your partition table and bootblock.\n\
Type YES if you're very sure you would like that partition\n\
tagged with 82 (Linux swap): ", 749},
  {"\
\n\
Disk %s (Sun disk label): %d heads, %d sectors, %d rpm\n\
%d cylinders, %d alternate cylinders, %d physical cylinders\n\
%d extra sects/cyl, interleave %d:1\n\
%s\n\
Units = %s of %d * 512 bytes\n\
\n", 750},
  {"\
\n\
Disk %s (Sun disk label): %d heads, %d sectors, %d cylinders\n\
Units = %s of %d * 512 bytes\n\
\n", 751},
  {"%*s Flag    Start       End    Blocks   Id  System\n", 752},
  {"Number of alternate cylinders", 753},
  {"Number of physical cylinders", 754},
  {"FAT12", 755},
  {"XENIX root", 756},
  {"XENIX usr", 757},
  {"FAT16 <32M", 758},
  {"Extended", 759},
  {"FAT16", 760},
  {"HPFS/NTFS", 761},
  {"AIX", 762},
  {"AIX bootable", 763},
  {"OS/2 Boot Manager", 764},
  {"Win95 FAT32", 765},
  {"Win95 FAT32 (LBA)", 766},
  {"Win95 FAT16 (LBA)", 767},
  {"Win95 Ext'd (LBA)", 768},
  {"OPUS", 769},
  {"Hidden FAT12", 770},
  {"Compaq diagnostics", 771},
  {"Hidden FAT16 <32M", 772},
  {"Hidden FAT16", 773},
  {"Hidden HPFS/NTFS", 774},
  {"AST Windows swapfile", 775},
  {"Hidden Win95 FAT32", 776},
  {"Hidden Win95 FAT32 (LBA)", 777},
  {"Hidden Win95 FAT16 (LBA)", 778},
  {"NEC DOS", 779},
  {"Plan 9", 780},
  {"PartitionMagic recovery", 781},
  {"Venix 80286", 782},
  {"PPC PReP Boot", 783},
  {"SFS", 784},
  {"QNX4.x", 785},
  {"QNX4.x 2nd part", 786},
  {"QNX4.x 3rd part", 787},
  {"OnTrack DM", 788},
  {"OnTrack DM6 Aux1", 789},
  {"CP/M", 790},
  {"OnTrack DM6 Aux3", 791},
  {"OnTrackDM6", 792},
  {"EZ-Drive", 793},
  {"Golden Bow", 794},
  {"Priam Edisk", 795},
  {"SpeedStor", 796},
  {"GNU HURD or SysV", 797},
  {"Novell Netware 286", 798},
  {"Novell Netware 386", 799},
  {"DiskSecure Multi-Boot", 800},
  {"PC/IX", 801},
  {"Old Minix", 802},
  {"Minix / old Linux", 803},
  {"OS/2 hidden C: drive", 804},
  {"Linux extended", 805},
  {"NTFS volume set", 806},
  {"Amoeba", 807},
  {"Amoeba BBT", 808},
  {"BSD/OS", 809},
  {"IBM Thinkpad hibernation", 810},
  {"BSD/386", 811},
  {"OpenBSD", 812},
  {"NeXTSTEP", 813},
  {"BSDI fs", 814},
  {"BSDI swap", 815},
  {"DRDOS/sec (FAT-12)", 816},
  {"DRDOS/sec (FAT-16 < 32M)", 817},
  {"DRDOS/sec (FAT-16)", 818},
  {"Syrinx", 819},
  {"Non-FS data", 820},
  {"CP/M / CTOS / ...", 821},
  {"DOS access", 822},
  {"DOS R/O", 823},
  {"BeOS fs", 824},
  {"DOS secondary", 825},
  {"Linux raid autodetect", 826},
  {"LANstep", 827},
  {"BBT", 828},
  {"seek error on %s - cannot seek to %lu\n", 829},
  {"seek error: wanted 0x%08x%08x, got 0x%08x%08x\n", 830},
  {"out of memory - giving up\n", 831},
  {"read error on %s - cannot read sector %lu\n", 832},
  {"ERROR: sector %lu does not have an msdos signature\n", 833},
  {"write error on %s - cannot write sector %lu\n", 834},
  {"cannot open partition sector save file (%s)\n", 835},
  {"write error on %s\n", 836},
  {"cannot stat partition restore file (%s)\n", 837},
  {"partition restore file has wrong size - not restoring\n", 838},
  {"out of memory?\n", 839},
  {"cannot open partition restore file (%s)\n", 840},
  {"error reading %s\n", 841},
  {"cannot open device %s for writing\n", 842},
  {"error writing sector %lu on %s\n", 843},
  {"Disk %s: cannot get size\n", 844},
  {"Disk %s: cannot get geometry\n", 845},
  {"\
Warning: start=%lu - this looks like a partition rather than\n\
the entire disk. Using fdisk on it is probably meaningless.\n\
[Use the --force option if you really want this]\n", 846},
  {"Warning: HDIO_GETGEO says that there are %lu heads\n", 847},
  {"Warning: HDIO_GETGEO says that there are %lu sectors\n", 848},
  {"Warning: BLKGETSIZE/HDIO_GETGEO says that there are %lu cylinders\n", 849},
  {"\
Warning: unlikely number of sectors (%lu) - usually at most 63\n\
This will give problems with all software that uses C/H/S addressing.\n", 850},
  {"\
\n\
Disk %s: %lu cylinders, %lu heads, %lu sectors/track\n", 851},
  {"\
%s of partition %s has impossible value for head: %lu (should be in 0-%lu)\n", 852},
  {"\
%s of partition %s has impossible value for sector: %lu (should be in \
1-%lu)\n", 853},
  {"\
%s of partition %s has impossible value for cylinders: %lu (should be in \
0-%lu)\n", 854},
  {"\
Id  Name\n\
\n", 855},
  {"Re-reading the partition table ...\n", 856},
  {"\
The command to re-read the partition table failed\n\
Reboot your system now, before using mkfs\n", 857},
  {"Error closing %s\n", 858},
  {"%s: no such partition\n", 859},
  {"unrecognized format - using sectors\n", 860},
  {"# partition table of %s\n", 861},
  {"unimplemented format - using %s\n", 862},
  {"\
Units = cylinders of %lu bytes, blocks of 1024 bytes, counting from %d\n\
\n", 863},
  {"   Device Boot Start     End   #cyls   #blocks   Id  System\n", 864},
  {"\
Units = sectors of 512 bytes, counting from %d\n\
\n", 865},
  {"   Device Boot    Start       End  #sectors  Id  System\n", 866},
  {"\
Units = blocks of 1024 bytes, counting from %d\n\
\n", 867},
  {"   Device Boot   Start       End   #blocks   Id  System\n", 868},
  {"\
Units = megabytes of 1048576 bytes, blocks of 1024 bytes, counting from %d\n\
\n", 869},
  {"   Device Boot Start   End     MB   #blocks   Id  System\n", 870},
  {"\t\tstart: (c,h,s) expected (%ld,%ld,%ld) found (%ld,%ld,%ld)\n", 871},
  {"\t\tend: (c,h,s) expected (%ld,%ld,%ld) found (%ld,%ld,%ld)\n", 872},
  {"partition ends on cylinder %ld, beyond the end of the disk\n", 873},
  {"No partitions found\n", 874},
  {"\
Warning: The first partition looks like it was made\n\
  for C/H/S=*/%ld/%ld (instead of %ld/%ld/%ld).\n\
For this listing I'll assume that geometry.\n", 875},
  {"no partition table present.\n", 876},
  {"strange, only %d partitions defined.\n", 877},
  {"Warning: partition %s has size 0 but is not marked Empty\n", 878},
  {"Warning: partition %s has size 0 and is bootable\n", 879},
  {"Warning: partition %s has size 0 and nonzero start\n", 880},
  {"Warning: partition %s ", 881},
  {"is not contained in partition %s\n", 882},
  {"Warning: partitions %s ", 883},
  {"and %s overlap\n", 884},
  {"Warning: partition %s contains part of ", 885},
  {"the partition table (sector %lu),\n", 886},
  {"and will destroy it when filled\n", 887},
  {"Warning: partition %s starts at sector 0\n", 888},
  {"Warning: partition %s extends past end of disk\n", 889},
  {"Among the primary partitions, at most one can be extended\n", 890},
  {" (although this is not a problem under Linux)\n", 891},
  {"Warning: partition %s does not start at a cylinder boundary\n", 892},
  {"Warning: partition %s does not end at a cylinder boundary\n", 893},
  {"\
Warning: more than one primary partition is marked bootable (active)\n\
This does not matter for LILO, but the DOS MBR will not boot this disk.\n", 894},
  {"\
Warning: usually one can boot from primary partitions only\n\
LILO disregards the `bootable' flag.\n", 895},
  {"\
Warning: no primary partition is marked bootable (active)\n\
This does not matter for LILO, but the DOS MBR will not boot this disk.\n", 896},
  {"\
partition %s: start: (c,h,s) expected (%ld,%ld,%ld) found (%ld,%ld,%ld)\n", 897},
  {"partition %s: end: (c,h,s) expected (%ld,%ld,%ld) found (%ld,%ld,%ld)\n", 898},
  {"partition %s ends on cylinder %ld, beyond the end of the disk\n", 899},
  {"Warning: shifted start of the extd partition from %ld to %ld\n", 900},
  {"(For listing purposes only. Do not change its contents.)\n", 901},
  {"Warning: extended partition does not start at a cylinder boundary.\n", 902},
  {"DOS and Linux will interpret the contents differently.\n", 903},
  {"too many partitions - ignoring those past nr (%d)\n", 904},
  {"tree of partitions?\n", 905},
  {"detected Disk Manager - unable to handle that\n", 906},
  {"DM6 signature found - giving up\n", 907},
  {"strange..., an extended partition of size 0?\n", 908},
  {"strange..., a BSD partition of size 0?\n", 909},
  {" %s: unrecognized partition\n", 910},
  {"-n flag was given: Nothing changed\n", 911},
  {"Failed saving the old sectors - aborting\n", 912},
  {"Failed writing the partition on %s\n", 913},
  {"long or incomplete input line - quitting\n", 914},
  {"input error: `=' expected after %s field\n", 915},
  {"input error: unexpected character %c after %s field\n", 916},
  {"unrecognized input: %s\n", 917},
  {"number too big\n", 918},
  {"trailing junk after number\n", 919},
  {"no room for partition descriptor\n", 920},
  {"cannot build surrounding extended partition\n", 921},
  {"too many input fields\n", 922},
  {"No room for more\n", 923},
  {"Illegal type\n", 924},
  {"Warning: given size (%lu) exceeds max allowable size (%lu)\n", 925},
  {"Warning: empty partition\n", 926},
  {"Warning: bad partition start (earliest %lu)\n", 927},
  {"unrecognized bootable flag - choose - or *\n", 928},
  {"partial c,h,s specification?\n", 929},
  {"Extended partition not where expected\n", 930},
  {"bad input\n", 931},
  {"too many partitions\n", 932},
  {"\
Input in the following format; absent fields get a default value.\n\
<start> <size> <type [E,S,L,X,hex]> <bootable [-,*]> <c,h,s> <c,h,s>\n\
Usually you only need to specify <start> and <size> (and perhaps <type>).\n", 933},
  {"version", 934},
  {"Usage: %s [options] device ...\n", 935},
  {"device: something like /dev/hda or /dev/sda", 936},
  {"useful options:", 937},
  {"    -s [or --show-size]: list size of a partition", 938},
  {"    -c [or --id]:        print or change partition Id", 939},
  {"    -l [or --list]:      list partitions of each device", 940},
  {"    -d [or --dump]:      idem, but in a format suitable for later input", 941},
  {"    -i [or --increment]: number cylinders etc. from 1 instead of from 0", 942},
  {"\
    -uS, -uB, -uC, -uM:  accept/report in units of \
sectors/blocks/cylinders/MB", 943},
  {"    -T [or --list-types]:list the known partition types", 944},
  {"    -D [or --DOS]:       for DOS-compatibility: waste a little space", 945},
  {"    -R [or --re-read]:   make kernel reread partition table", 946},
  {"    -N# :                change only the partition with number #", 947},
  {"    -n :                 do not actually write to disk", 948},
  {"\
    -O file :            save the sectors that will be overwritten to file", 949},
  {"    -I file :            restore these sectors again", 950},
  {"    -v [or --version]:   print version", 951},
  {"    -? [or --help]:      print this message", 952},
  {"dangerous options:", 953},
  {"    -g [or --show-geometry]: print the kernel's idea of the geometry", 954},
  {"\
    -x [or --show-extended]: also list extended partitions on output\n\
                             or expect descriptors for them on input", 955},
  {"\
    -L  [or --Linux]:      do not complain about things irrelevant for Linux", 956},
  {"    -q  [or --quiet]:      suppress warning messages", 957},
  {"    You can override the detected geometry using:", 958},
  {"    -C# [or --cylinders #]:set the number of cylinders to use", 959},
  {"    -H# [or --heads #]:    set the number of heads to use", 960},
  {"    -S# [or --sectors #]:  set the number of sectors to use", 961},
  {"You can disable all consistency checking with:", 962},
  {"    -f  [or --force]:      do what I say, even if it is stupid", 963},
  {"Usage:", 964},
  {"%s device\t\t list active partitions on device\n", 965},
  {"%s device n1 n2 ... activate partitions n1 ..., inactivate the rest\n", 966},
  {"%s -An device\t activate partition n, inactivate the other ones\n", 967},
  {"no command?\n", 968},
  {"total: %d blocks\n", 969},
  {"usage: sfdisk --print-id device partition-number\n", 970},
  {"usage: sfdisk --change-id device partition-number Id\n", 971},
  {"usage: sfdisk --id device partition-number [Id]\n", 972},
  {"can specify only one device (except with -l or -s)\n", 973},
  {"cannot open %s %s\n", 974},
  {"read-write", 975},
  {"for reading", 976},
  {"%s: OK\n", 977},
  {"%s: %ld cylinders, %ld heads, %ld sectors/track\n", 978},
  {"BLKGETSIZE ioctl failed for %s\n", 979},
  {"bad active byte: 0x%x instead of 0x80\n", 980},
  {"\
Done\n\
\n", 981},
  {"\
You have %d active primary partitions. This does not matter for LILO,\n\
but the DOS MBR will only boot a disk with 1 active partition.\n", 982},
  {"partition %s has id %x and is not hidden\n", 983},
  {"Bad Id %lx\n", 984},
  {"This disk is currently in use.\n", 985},
  {"Fatal error: cannot find %s\n", 986},
  {"Warning: %s is not a block device\n", 987},
  {"Checking that no-one is using this disk right now ...\n", 988},
  {"\
\n\
This disk is currently in use - repartitioning is probably a bad idea.\n\
Umount all file systems, and swapoff all swap partitions on this disk.\n\
Use the --no-reread flag to suppress this check.\n", 989},
  {"Use the --force flag to overrule all checks.\n", 990},
  {"OK\n", 991},
  {"Old situation:\n", 992},
  {"Partition %d does not exist, cannot change it\n", 993},
  {"New situation:\n", 994},
  {"\
I don't like these partitions - nothing changed.\n\
(If you really want this, use the --force option.)\n", 995},
  {"I don't like this - probably you should answer No\n", 996},
  {"Are you satisfied with this? [ynq] ", 997},
  {"Do you want to write this to disk? [ynq] ", 998},
  {"\
\n\
sfdisk: premature end of input\n", 999},
  {"Quitting - nothing changed\n", 1000},
  {"Please answer one of y,n,q\n", 1001},
  {"\
Successfully wrote the new partition table\n\
\n", 1002},
  {"\
If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)\n\
to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1\n\
(See fdisk(8).)\n", 1003},
  {"usage: banner [-w width]\n", 1004},
  {"Message: ", 1005},
  {"The character '%c' is not in my character set", 1006},
  {"Message '%s' is OK\n", 1007},
  {"Try `getopt --help' for more information.\n", 1008},
  {"empty long option after -l or --long argument", 1009},
  {"unknown shell after -s or --shell argument", 1010},
  {"Usage: getopt optstring parameters\n", 1011},
  {"       getopt [options] [--] optstring parameters\n", 1012},
  {"       getopt [options] -o|--options optstring [options] [--]\n", 1013},
  {"              parameters\n", 1014},
  {"\
  -a, --alternative            Allow long options starting with single -\n", 1015},
  {"  -h, --help                   This small usage guide\n", 1016},
  {"  -l, --longoptions=longopts   Long options to be recognized\n", 1017},
  {"\
  -n, --name=progname          The name under which errors are reported\n", 1018},
  {"  -o, --options=optstring      Short options to be recognized\n", 1019},
  {"  -q, --quiet                  Disable error reporting by getopt(3)\n", 1020},
  {"  -Q, --quiet-output           No normal output\n", 1021},
  {"  -s, --shell=shell            Set shell quoting conventions\n", 1022},
  {"  -T, --test                   Test for getopt(1) version\n", 1023},
  {"  -u, --unqote                 Do not quote the output\n", 1024},
  {"  -V, --version                Output version information\n", 1025},
  {"missing optstring argument", 1026},
  {"getopt (enhanced) 1.1.0\n", 1027},
  {"internal error, contact the author.", 1028},
  {"calling open_tty\n", 1029},
  {"calling termio_init\n", 1030},
  {"writing init string\n", 1031},
  {"before autobaud\n", 1032},
  {"waiting for cr-lf\n", 1033},
  {"read %c\n", 1034},
  {"reading login name\n", 1035},
  {"%s: can't exec %s: %m", 1036},
  {"can't malloc initstring", 1037},
  {"bad timeout value: %s", 1038},
  {"after getopt loop\n", 1039},
  {"exiting parseargs\n", 1040},
  {"entered parse_speeds\n", 1041},
  {"bad speed: %s", 1042},
  {"too many alternate speeds", 1043},
  {"exiting parsespeeds\n", 1044},
  {"%s: open for update: %m", 1045},
  {"%s: no utmp entry", 1046},
  {"/dev: chdir() failed: %m", 1047},
  {"/dev/%s: not a character device", 1048},
  {"open(2)\n", 1049},
  {"/dev/%s: cannot open as standard input: %m", 1050},
  {"%s: not open for read/write", 1051},
  {"duping\n", 1052},
  {"%s: dup problem: %m", 1053},
  {"term_io 2\n", 1054},
  {"user", 1055},
  {"users", 1056},
  {"%s: read: %m", 1057},
  {"%s: input overrun", 1058},
  {"\
Usage: %s [-hiLmw] [-l login_program] [-t timeout] [-I initstring] [-H \
login_host] baud_rate,... line [termtype]\n\
or\t[-hiLmw] [-l login_program] [-t timeout] [-I initstring] [-H login_host] \
line baud_rate,... [termtype]\n", 1059},
  {"login: memory low, login may fail\n", 1060},
  {"can't malloc for ttyclass", 1061},
  {"can't malloc for grplist", 1062},
  {"Login on %s from %s denied by default.\n", 1063},
  {"Login on %s from %s denied.\n", 1064},
  {"%s: you (user %d) don't exist.\n", 1065},
  {"%s: user \"%s\" does not exist.\n", 1066},
  {"%s: can only change local entries; use yp%s instead.\n", 1067},
  {"Changing finger information for %s.\n", 1068},
  {"Password error.", 1069},
  {"Password: ", 1070},
  {"Incorrect password.", 1071},
  {"Finger information not changed.\n", 1072},
  {"Usage: %s [ -f full-name ] [ -o office ] ", 1073},
  {"\
[ -p office-phone ]\n\
\t[ -h home-phone ] ", 1074},
  {"[ --help ] [ --version ]\n", 1075},
  {"\
\n\
Aborted.\n", 1076},
  {"field is too long.\n", 1077},
  {"'%c' is not allowed.\n", 1078},
  {"Control characters are not allowed.\n", 1079},
  {"Finger information *NOT* changed.  Try again later.\n", 1080},
  {"Finger information changed.\n", 1081},
  {"malloc failed", 1082},
  {"%s: Your shell is not in /etc/shells, shell change denied\n", 1083},
  {"Changing shell for %s.\n", 1084},
  {"New shell", 1085},
  {"Shell not changed.\n", 1086},
  {"Shell *NOT* changed.  Try again later.\n", 1087},
  {"Shell changed.\n", 1088},
  {"Usage: %s [ -s shell ] ", 1089},
  {"[ --list-shells ] [ --help ] [ --version ]\n", 1090},
  {"       [ username ]\n", 1091},
  {"%s: shell must be a full path name.\n", 1092},
  {"%s: \"%s\" does not exist.\n", 1093},
  {"%s: \"%s\" is not executable.\n", 1094},
  {"%s: '%c' is not allowed.\n", 1095},
  {"%s: Control characters are not allowed.\n", 1096},
  {"Warning: \"%s\" is not listed in /etc/shells\n", 1097},
  {"%s: \"%s\" is not listed in /etc/shells.\n", 1098},
  {"%s: use -l option to see list\n", 1099},
  {"Warning: \"%s\" is not listed in /etc/shells.\n", 1100},
  {"Use %s -l to see list.\n", 1101},
  {"No known shells.\n", 1102},
  {"couldn't open /dev/urandom", 1103},
  {"couldn't read random data from /dev/urandom", 1104},
  {"can't open %s for reading", 1105},
  {"can't stat(%s)", 1106},
  {"%s doesn't have the correct filemodes", 1107},
  {"can't read data from %s", 1108},
  {"Can't read %s, exiting.", 1109},
  {"usage: last [-#] [-f file] [-t tty] [-h hostname] [user ...]\n", 1110},
  {"  still logged in", 1111},
  {"\
\n\
wtmp begins %s", 1112},
  {"last: malloc failure.\n", 1113},
  {"last: gethostname", 1114},
  {"\
\n\
interrupted %10.10s %5.5s \n", 1115},
  {"login: -h for super-user only.\n", 1116},
  {"usage: login [-fp] [username]\n", 1117},
  {"login: PAM Failure, aborting: %s\n", 1118},
  {"Couldn't initialize PAM: %s", 1119},
  {"login: ", 1120},
  {"FAILED LOGIN %d FROM %s FOR %s, %s", 1121},
  {"\
Login incorrect\n\
\n", 1122},
  {"TOO MANY LOGIN TRIES (%d) FROM %s FOR %s, %s", 1123},
  {"FAILED LOGIN SESSION FROM %s FOR %s, %s", 1124},
  {"\
\n\
Login incorrect\n", 1125},
  {"Illegal username", 1126},
  {"%s login refused on this terminal.\n", 1127},
  {"LOGIN %s REFUSED FROM %s ON TTY %s", 1128},
  {"LOGIN %s REFUSED ON TTY %s", 1129},
  {"Login incorrect\n", 1130},
  {"\
Too many users logged on already.\n\
Try again later.\n", 1131},
  {"You have too many processes running.\n", 1132},
  {"Warning: no Kerberos tickets issued\n", 1133},
  {"Sorry -- your password has expired.\n", 1134},
  {"Warning: your password expires on %d %s %d.\n", 1135},
  {"Sorry -- your account has expired.\n", 1136},
  {"Warning: your account expires on %d %s %d.\n", 1137},
  {"DIALUP AT %s BY %s", 1138},
  {"ROOT LOGIN ON %s FROM %s", 1139},
  {"ROOT LOGIN ON %s", 1140},
  {"LOGIN ON %s BY %s FROM %s", 1141},
  {"LOGIN ON %s BY %s", 1142},
  {"You have %smail.\n", 1143},
  {"new ", 1144},
  {"login: failure forking: %s", 1145},
  {"setuid() failed", 1146},
  {"No directory %s!\n", 1147},
  {"Logging in with home = \"/\".\n", 1148},
  {"login: no memory for shell script.\n", 1149},
  {"login: couldn't exec shell script: %s.\n", 1150},
  {"login: no shell: %s.\n", 1151},
  {"\
\n\
%s login: ", 1152},
  {"login name much too long.\n", 1153},
  {"NAME too long", 1154},
  {"login names may not start with '-'.\n", 1155},
  {"too many bare linefeeds.\n", 1156},
  {"EXCESSIVE linefeeds", 1157},
  {"Login timed out after %d seconds\n", 1158},
  {"Last login: %.*s ", 1159},
  {"from %.*s\n", 1160},
  {"on %.*s\n", 1161},
  {"LOGIN FAILURE FROM %s, %s", 1162},
  {"LOGIN FAILURE ON %s, %s", 1163},
  {"%d LOGIN FAILURES FROM %s, %s", 1164},
  {"%d LOGIN FAILURES ON %s, %s", 1165},
  {"is y\n", 1166},
  {"is n\n", 1167},
  {"usage: mesg [y | n]\n", 1168},
  {"newgrp: Who are you?", 1169},
  {"newgrp: setgid", 1170},
  {"newgrp: No such group.", 1171},
  {"newgrp: Permission denied", 1172},
  {"newgrp: setuid", 1173},
  {"No shell", 1174},
  {"The password must have at least 6 characters, try again.\n", 1175},
  {"The password must contain characters out of two of the following\n", 1176},
  {"classes:  upper and lower case letters, digits and non alphanumeric\n", 1177},
  {"characters. See passwd(1) for more information.\n", 1178},
  {"You cannot reuse the old password.\n", 1179},
  {"Please don't use something like your username as password!\n", 1180},
  {"Please don't use something like your realname as password!\n", 1181},
  {"Usage: passwd [username [password]]\n", 1182},
  {"Only root may use the one and two argument forms.\n", 1183},
  {"Usage: passwd [-foqsvV] [user [password]]\n", 1184},
  {"Can't exec %s: %s\n", 1185},
  {"Cannot find login name", 1186},
  {"Only root can change the password for others.\n", 1187},
  {"Too many arguments.\n", 1188},
  {"Can't find username anywhere. Is `%s' really a user?", 1189},
  {"Sorry, I can only change local passwords. Use yppasswd instead.", 1190},
  {"UID and username does not match, imposter!", 1191},
  {"Changing password for %s\n", 1192},
  {"Enter old password: ", 1193},
  {"Illegal password, imposter.", 1194},
  {"Enter new password: ", 1195},
  {"Password not changed.", 1196},
  {"Re-type new password: ", 1197},
  {"You misspelled it. Password not changed.", 1198},
  {"password changed, user %s", 1199},
  {"ROOT PASSWORD CHANGED", 1200},
  {"password changed by root, user %s", 1201},
  {"calling setpwnam to set password.\n", 1202},
  {"Password *NOT* changed.  Try again later.\n", 1203},
  {"Password changed.\n", 1204},
  {"Usage: shutdown [-h|-r] [-fqs] [now|hh:ss|+mins]\n", 1205},
  {"Shutdown process aborted", 1206},
  {"%s: Only root can shut a system down.\n", 1207},
  {"That must be tomorrow, can't you wait till then?\n", 1208},
  {"for maintenance; bounce, bounce", 1209},
  {"timeout = %d, quiet = %d, reboot = %d\n", 1210},
  {"The system is being shut down within 5 minutes", 1211},
  {"Login is therefore prohibited.", 1212},
  {"%s by %s: %s", 1213},
  {"rebooted", 1214},
  {"halted", 1215},
  {"\
\n\
Why am I still alive after reboot?", 1216},
  {"\
\n\
Now you can turn off the power...", 1217},
  {"Calling kernel power-off facility...\n", 1218},
  {"Error powering off\t%s\n", 1219},
  {"Executing the program \"%s\" ...\n", 1220},
  {"Error executing\t%s\n", 1221},
  {"URGENT: broadcast message from %s:", 1222},
  {"System going down in %d hours %d minutes", 1223},
  {"System going down in 1 hour %d minutes", 1224},
  {"System going down in %d minutes\n", 1225},
  {"System going down in 1 minute\n", 1226},
  {"System going down IMMEDIATELY!\n", 1227},
  {"\t... %s ...\n", 1228},
  {"Cannot fork for swapoff. Shrug!", 1229},
  {"Cannot exec swapoff, hoping umount will do the trick.", 1230},
  {"Cannot fork for umount, trying manually.", 1231},
  {"Cannot exec %s, trying umount.\n", 1232},
  {"Cannot exec umount, giving up on umount.", 1233},
  {"Unmounting any remaining filesystems...", 1234},
  {"shutdown: Couldn't umount %s: %s\n", 1235},
  {"Booting to single user mode.\n", 1236},
  {"exec of single user shell failed\n", 1237},
  {"fork of single user shell failed\n", 1238},
  {"error opening fifo\n", 1239},
  {"error running finalprog\n", 1240},
  {"error forking finalprog\n", 1241},
  {"\
\n\
Wrong password.\n", 1242},
  {"stat of path failed\n", 1243},
  {"open of directory failed\n", 1244},
  {"fork failed\n", 1245},
  {"exec failed\n", 1246},
  {"cannot open inittab\n", 1247},
  {"no TERM or cannot stat tty\n", 1248},
  {"error running programme\n", 1249},
  {"too many iov's (change code in wall/ttymsg.c)", 1250},
  {"excessively long line arg", 1251},
  {"cannot fork", 1252},
  {"fork: %s", 1253},
  {"%s: BAD ERROR", 1254},
  {"%s: the %s file is busy.\n", 1255},
  {"%s: the %s file is busy (%s present)\n", 1256},
  {"%s: can't link %s: %s\n", 1257},
  {"%s: can't unlock %s: %s (your changes are still in %s)\n", 1258},
  {"%s: Cannot fork\n", 1259},
  {"%s: %s unchanged\n", 1260},
  {"%s: no changes made\n", 1261},
  {"usage: %s [file]\n", 1262},
  {"%s: can't open temporary file.\n", 1263},
  {"Broadcast Message from %s@%s", 1264},
  {"%s: will not read %s - use stdin.\n", 1265},
  {"%s: can't read %s.\n", 1266},
  {"%s: can't stat temporary file.\n", 1267},
  {"%s: can't read temporary file.\n", 1268},
  {"illegal month value: use 1-12", 1269},
  {"illegal year value: use 1-9999", 1270},
  {"usage: cal [-mjyV] [[month] year]\n", 1271},
  {"usage: %s [+format] [day month year]\n", 1272},
  {"St. Tib's Day", 1273},
  {"%s: unknown signal %s\n", 1274},
  {"%s: can't find process \"%s\"\n", 1275},
  {"%s: unknown signal %s; valid signals:\n", 1276},
  {"usage: %s [ -s signal | -p ] [ -a ] pid ...\n", 1277},
  {"       %s -l [ signal ]\n", 1278},
  {"logger: %s: %s.\n", 1279},
  {"logger: unknown facility name: %s.\n", 1280},
  {"logger: unknown priority name: %s.\n", 1281},
  {"\
usage: logger [-is] [-f file] [-p pri] [-t tag] [-u socket] [ message ... ]\n", 1282},
  {"usage: look [-dfa] [-t char] string [file]\n", 1283},
  {"Could not open %s\n", 1284},
  {"Got %d bytes from %s\n", 1285},
  {"namei: unable to get current directory - %s\n", 1286},
  {"namei: unable to chdir to %s - %s (%d)\n", 1287},
  {"usage: namei [-mx] pathname [pathname ...]\n", 1288},
  {"namei: could not chdir to root!\n", 1289},
  {"namei: could not stat root!\n", 1290},
  {" ? could not chdir into %s - %s (%d)\n", 1291},
  {" ? problems reading symlink %s - %s (%d)\n", 1292},
  {"  *** EXCEEDED UNIX LIMIT OF SYMLINKS ***\n", 1293},
  {"namei: unknown file type 0%06o on file %s\n", 1294},
  {"\
Warning: `%s' is a symlink.\n\
Use `%s [options] %s' if you really want to use it.\n\
Script not started.\n", 1295},
  {"usage: script [-a] [-f] [-q] [file]\n", 1296},
  {"Script started, file is %s\n", 1297},
  {"Script started on %s", 1298},
  {"\
\n\
Script done on %s", 1299},
  {"Script done, file is %s\n", 1300},
  {"openpty failed\n", 1301},
  {"Out of pty's\n", 1302},
  {"%s: Argument error, usage\n", 1303},
  {"  [ -term terminal_name ]\n", 1304},
  {"  [ -reset ]\n", 1305},
  {"  [ -initialize ]\n", 1306},
  {"  [ -cursor [on|off] ]\n", 1307},
  {"  [ -snow [on|off] ]\n", 1308},
  {"  [ -softscroll [on|off] ]\n", 1309},
  {"  [ -repeat [on|off] ]\n", 1310},
  {"  [ -appcursorkeys [on|off] ]\n", 1311},
  {"  [ -linewrap [on|off] ]\n", 1312},
  {"  [ -default ]\n", 1313},
  {"  [ -foreground black|blue|green|cyan", 1314},
  {"|red|magenta|yellow|white|default ]\n", 1315},
  {"  [ -background black|blue|green|cyan", 1316},
  {"  [ -ulcolor black|grey|blue|green|cyan", 1317},
  {"|red|magenta|yellow|white ]\n", 1318},
  {"  [ -ulcolor bright blue|green|cyan", 1319},
  {"  [ -hbcolor black|grey|blue|green|cyan", 1320},
  {"  [ -hbcolor bright blue|green|cyan", 1321},
  {"  [ -standout [ attr ] ]\n", 1322},
  {"  [ -inversescreen [on|off] ]\n", 1323},
  {"  [ -bold [on|off] ]\n", 1324},
  {"  [ -half-bright [on|off] ]\n", 1325},
  {"  [ -blink [on|off] ]\n", 1326},
  {"  [ -reverse [on|off] ]\n", 1327},
  {"  [ -underline [on|off] ]\n", 1328},
  {"  [ -store ]\n", 1329},
  {"  [ -clear [all|rest] ]\n", 1330},
  {"  [ -tabs [ tab1 tab2 tab3 ... ] ]      (tabn = 1-160)\n", 1331},
  {"  [ -clrtabs [ tab1 tab2 tab3 ... ] ]   (tabn = 1-160)\n", 1332},
  {"  [ -regtabs [1-160] ]\n", 1333},
  {"  [ -blank [0-60] ]\n", 1334},
  {"  [ -dump   [1-NR_CONSOLES] ]\n", 1335},
  {"  [ -append [1-NR_CONSOLES] ]\n", 1336},
  {"  [ -file dumpfilename ]\n", 1337},
  {"  [ -msg [on|off] ]\n", 1338},
  {"  [ -msglevel [0-8] ]\n", 1339},
  {"  [ -powersave [on|vsync|hsync|powerdown|off] ]\n", 1340},
  {"  [ -powerdown [0-60] ]\n", 1341},
  {"  [ -blength [0-2000] ]\n", 1342},
  {"  [ -bfreq freqnumber ]\n", 1343},
  {"snow.on", 1344},
  {"snow.off", 1345},
  {"softscroll.on", 1346},
  {"softscroll.off", 1347},
  {"cannot (un)set powersave mode\n", 1348},
  {"klogctl error: %s\n", 1349},
  {"Error reading %s\n", 1350},
  {"Error writing screendump\n", 1351},
  {"couldn't read %s, and cannot ioctl dump\n", 1352},
  {"%s: $TERM is not defined.\n", 1353},
  {"usage: tsort [ inputfile ]\n", 1354},
  {"tsort: odd data count.\n", 1355},
  {"tsort: cycle in data.\n", 1356},
  {"tsort: internal error -- could not find cycle.\n", 1357},
  {"whereis [ -sbmu ] [ -SBM dir ... -f ] name...\n", 1358},
  {"write: can't find your tty's name\n", 1359},
  {"write: you have write permission turned off.\n", 1360},
  {"write: %s is not logged in on %s.\n", 1361},
  {"write: %s has messages disabled on %s\n", 1362},
  {"usage: write user [tty]\n", 1363},
  {"write: %s is not logged in\n", 1364},
  {"write: %s has messages disabled\n", 1365},
  {"write: %s is logged in more than once; writing to %s\n", 1366},
  {"Message from %s@%s (as %s) on %s at %s ...", 1367},
  {"Message from %s@%s on %s at %s ...", 1368},
  {"warning: error reading %s: %s", 1369},
  {"warning: can't open %s: %s", 1370},
  {"mount: could not open %s - using %s instead\n", 1371},
  {"can't create lock file %s: %s (use -n flag to override)", 1372},
  {"can't link lock file %s: %s (use -n flag to override)", 1373},
  {"can't open lock file %s: %s (use -n flag to override)", 1374},
  {"Can't lock lock file %s: %s\n", 1375},
  {"can't lock lock file %s: %s", 1376},
  {"timed out", 1377},
  {"\
Cannot create link %s\n\
Perhaps there is a stale lock file?\n", 1378},
  {"cannot open %s (%s) - mtab not updated", 1379},
  {"error writing %s: %s", 1380},
  {"error changing mode of %s: %s\n", 1381},
  {"can't rename %s to %s: %s\n", 1382},
  {"loop: can't open device %s: %s\n", 1383},
  {"loop: can't get info on device %s: %s\n", 1384},
  {"%s: [%04x]:%ld (%s) offset %d, %s encryption\n", 1385},
  {"mount: could not find any device /dev/loop#", 1386},
  {"\
mount: Could not find any loop device.\n\
       Maybe /dev/loop# has a wrong major number?", 1387},
  {"\
mount: Could not find any loop device, and, according to %s,\n\
       this kernel does not know about the loop device.\n\
       (If so, then recompile or `insmod loop.o'.)", 1388},
  {"\
mount: Could not find any loop device. Maybe this kernel does not know\n\
       about the loop device (then recompile or `insmod loop.o'), or\n\
       maybe /dev/loop# has the wrong major number?", 1389},
  {"mount: could not find any free loop device", 1390},
  {"Unsupported encryption type %s\n", 1391},
  {"Couldn't lock into memory, exiting.\n", 1392},
  {"Init (up to 16 hex digits): ", 1393},
  {"Non-hex digit '%c'.\n", 1394},
  {"Don't know how to get key for encryption system %d\n", 1395},
  {"set_loop(%s,%s,%d): success\n", 1396},
  {"loop: can't delete device %s: %s\n", 1397},
  {"del_loop(%s): success\n", 1398},
  {"This mount was compiled without loop support. Please recompile.\n", 1399},
  {"\
usage:\n\
  %s loop_device                                      # give info\n\
  %s -d loop_device                                   # delete\n\
  %s [ -e encryption ] [ -o offset ] loop_device file # setup\n", 1400},
  {"not enough memory", 1401},
  {"No loop support was available at compile time. Please recompile.\n", 1402},
  {"[mntent]: warning: no final newline at the end of %s\n", 1403},
  {"[mntent]: line %d in %s is bad%s\n", 1404},
  {"; rest of file ignored", 1405},
  {"mount: according to mtab, %s is already mounted on %s", 1406},
  {"mount: according to mtab, %s is mounted on %s", 1407},
  {"mount: can't open %s for writing: %s", 1408},
  {"mount: error writing %s: %s", 1409},
  {"mount: error changing mode of %s: %s", 1410},
  {"%s looks like swapspace - not mounted", 1411},
  {"mount failed", 1412},
  {"mount: only root can mount %s on %s", 1413},
  {"mount: loop device specified twice", 1414},
  {"mount: type specified twice", 1415},
  {"mount: skipping the setup of a loop device\n", 1416},
  {"mount: going to use the loop device %s\n", 1417},
  {"mount: failed setting up loop device\n", 1418},
  {"mount: setup loop device successfully\n", 1419},
  {"mount: can't open %s: %s", 1420},
  {"mount: cannot not open %s for setting speed", 1421},
  {"mount: cannot set speed: %s", 1422},
  {"mount: cannot fork: %s", 1423},
  {"mount: this version was compiled without support for the type `nfs'", 1424},
  {"mount: failed with nfs mount version 4, trying 3..\n", 1425},
  {"\
mount: I could not determine the filesystem type, and none was specified", 1426},
  {"mount: you must specify the filesystem type", 1427},
  {"mount: mount failed", 1428},
  {"mount: mount point %s is not a directory", 1429},
  {"mount: permission denied", 1430},
  {"mount: must be superuser to use mount", 1431},
  {"mount: %s is busy", 1432},
  {"mount: proc already mounted", 1433},
  {"mount: %s already mounted or %s busy", 1434},
  {"mount: mount point %s does not exist", 1435},
  {"mount: mount point %s is a symbolic link to nowhere", 1436},
  {"mount: special device %s does not exist", 1437},
  {"\
mount: special device %s does not exist\n\
       (a path prefix is not a directory)\n", 1438},
  {"mount: %s not mounted already, or bad option", 1439},
  {"\
mount: wrong fs type, bad option, bad superblock on %s,\n\
       or too many mounted file systems", 1440},
  {"mount table full", 1441},
  {"mount: %s: can't read superblock", 1442},
  {"mount: %s: unknown device", 1443},
  {"mount: fs type %s not supported by kernel", 1444},
  {"mount: probably you meant %s", 1445},
  {"mount: maybe you meant iso9660 ?", 1446},
  {"mount: %s has wrong device number or fs type %s not supported", 1447},
  {"mount: %s is not a block device, and stat fails?", 1448},
  {"\
mount: the kernel does not recognize %s as a block device\n\
       (maybe `insmod driver'?)", 1449},
  {"mount: %s is not a block device (maybe try `-o loop'?)", 1450},
  {"mount: %s is not a block device", 1451},
  {"mount: %s is not a valid block device", 1452},
  {"block device ", 1453},
  {"mount: cannot mount %s%s read-only", 1454},
  {"mount: %s%s is write-protected but explicit `-w' flag given", 1455},
  {"mount: %s%s is write-protected, mounting read-only", 1456},
  {"mount: going to mount %s by %s\n", 1457},
  {"UUID", 1458},
  {"label", 1459},
  {"mount: no such partition found", 1460},
  {"mount: no type was given - I'll assume nfs because of the colon\n", 1461},
  {"mount: backgrounding \"%s\"\n", 1462},
  {"mount: giving up \"%s\"\n", 1463},
  {"mount: %s already mounted on %s\n", 1464},
  {"\
Usage: mount -V                 : print version\n\
       mount -h                 : print this help\n\
       mount                    : list mounted filesystems\n\
       mount -l                 : idem, including volume labels\n\
So far the informational part. Next the mounting.\n\
The command is `mount [-t fstype] something somewhere'.\n\
Details found in /etc/fstab may be omitted.\n\
       mount -a                 : mount all stuff from /etc/fstab\n\
       mount device             : mount device at the known place\n\
       mount directory          : mount known device here\n\
       mount -t type dev dir    : ordinary mount command\n\
Note that one does not really mount a device, one mounts\n\
a filesystem (of the given type) found on the device.\n\
One can also mount an already visible directory tree elsewhere:\n\
       mount --bind olddir newdir\n\
A device can be given by name, say /dev/hda1 or /dev/cdrom,\n\
or by label, using  -L label  or by uuid, using  -U uuid .\n\
Union or stack mounts are specified using one of\n\
       --replace, --after, --before, --over\n\
Other options: [-nfFrsvw] [-o options].\n\
For many more details, say  man 8 mount .\n", 1465},
  {"mount: only root can do that", 1466},
  {"mount: no %s found - creating it..\n", 1467},
  {"mount: mounting %s\n", 1468},
  {"not mounted anything", 1469},
  {"mount: cannot find %s in %s", 1470},
  {"mount: can't find %s in %s or %s", 1471},
  {"\
mount: could not open %s, so UUID and LABEL conversion cannot be done.\n", 1472},
  {"mount: bad UUID", 1473},
  {"mount: you didn't specify a filesystem type for %s\n", 1474},
  {"       I will try all types mentioned in %s or %s\n", 1475},
  {"       and it looks like this is swapspace\n", 1476},
  {"       I will try type %s\n", 1477},
  {"Trying %s\n", 1478},
  {"mount: excessively long host:dir argument\n", 1479},
  {"mount: warning: multiple hostnames not supported\n", 1480},
  {"mount: directory to mount not in host:dir format\n", 1481},
  {"mount: can't get address for %s\n", 1482},
  {"mount: got bad hp->h_length\n", 1483},
  {"mount: excessively long option argument\n", 1484},
  {"Warning: Unrecognized proto= option.\n", 1485},
  {"Warning: Option namlen is not supported.\n", 1486},
  {"unknown nfs mount parameter: %s=%d\n", 1487},
  {"Warning: option nolock is not supported.\n", 1488},
  {"unknown nfs mount option: %s%s\n", 1489},
  {"mount: got bad hp->h_length?\n", 1490},
  {"NFS over TCP is not supported.\n", 1491},
  {"nfs socket", 1492},
  {"nfs bindresvport", 1493},
  {"used portmapper to find NFS port\n", 1494},
  {"using port %d for nfs deamon\n", 1495},
  {"nfs connect", 1496},
  {"unknown nfs status return value: %d", 1497},
  {"bug in xstrndup call", 1498},
  {"\
usage: %s [-hV]\n\
       %s -a [-v]\n\
       %s [-v] [-p priority] special ...\n\
       %s [-s]\n", 1499},
  {"%s on %s\n", 1500},
  {"swapon: cannot stat %s: %s\n", 1501},
  {"swapon: warning: %s has insecure permissions %04o, 0600 suggested\n", 1502},
  {"swapon: Skipping file %s - it appears to have holes.\n", 1503},
  {"%s: cannot open %s: %s\n", 1504},
  {"umount: compiled without support for -f\n", 1505},
  {"host: %s, directory: %s\n", 1506},
  {"umount: can't get address for %s\n", 1507},
  {"umount: got bad hostp->h_length\n", 1508},
  {"umount: %s: invalid block device", 1509},
  {"umount: %s: not mounted", 1510},
  {"umount: %s: can't write superblock", 1511},
  {"umount: %s: device is busy", 1512},
  {"umount: %s: not found", 1513},
  {"umount: %s: must be superuser to umount", 1514},
  {"umount: %s: block devices not permitted on fs", 1515},
  {"umount: %s: %s", 1516},
  {"no umount2, trying umount...\n", 1517},
  {"could not umount %s - trying %s instead\n", 1518},
  {"umount: %s busy - remounted read-only\n", 1519},
  {"umount: could not remount %s read-only\n", 1520},
  {"%s umounted\n", 1521},
  {"umount: cannot find list of filesystems to unmount", 1522},
  {"\
Usage: umount [-hV]\n\
       umount -a [-f] [-r] [-n] [-v] [-t vfstypes]\n\
       umount [-f] [-r] [-n] [-v] special | node...\n", 1523},
  {"umount: only root can do that", 1524},
  {"Trying to umount %s\n", 1525},
  {"Could not find %s in mtab\n", 1526},
  {"umount: %s is not mounted (according to mtab)", 1527},
  {"umount: it seems %s is mounted multiple times", 1528},
  {"umount: %s is not in the fstab (and you are not root)", 1529},
  {"umount: %s mount disagrees with the fstab", 1530},
  {"umount: only root can unmount %s from %s", 1531},
  {"umount: only %s can unmount %s from %s", 1532},
  {"You must be root to set the Ctrl-Alt-Del behaviour.\n", 1533},
  {"Usage: ctrlaltdel hard|soft\n", 1534},
  {"\
File %s, For threshold value %lu, Maximum characters in fifo were %d,\n\
and the maximum transfer rate in characters/second was %f\n", 1535},
  {"\
File %s, For threshold value %lu and timrout value %lu, Maximum characters \
in fifo were %d,\n\
and the maximum transfer rate in characters/second was %f\n", 1536},
  {"Invalid interval value: %s\n", 1537},
  {"Invalid set value: %s\n", 1538},
  {"Invalid default value: %s\n", 1539},
  {"Invalid set time value: %s\n", 1540},
  {"Invalid default time value: %s\n", 1541},
  {"\
Usage: %s [-q [-i interval]] ([-s value]|[-S value]) ([-t value]|[-T value]) \
[-g|-G] file [file...]\n", 1542},
  {"Can't open %s: %s\n", 1543},
  {"Can't set %s to threshold %d: %s\n", 1544},
  {"Can't set %s to time threshold %d: %s\n", 1545},
  {"Can't get threshold for %s: %s\n", 1546},
  {"Can't get timeout for %s: %s\n", 1547},
  {"%s: %ld %s threshold and %ld %s timeout\n", 1548},
  {"current", 1549},
  {"default", 1550},
  {"Can't set signal handler", 1551},
  {"gettimeofday failed", 1552},
  {"Can't issue CYGETMON on %s: %s\n", 1553},
  {"%s: %lu ints, %lu/%lu chars; ", 1554},
  {"fifo: %lu thresh, %lu tmout, ", 1555},
  {"%lu max, %lu now\n", 1556},
  {"   %f int/sec; %f rec, %f send (char/sec)\n", 1557},
  {"\
%s: %lu ints, %lu chars; fifo: %lu thresh, %lu tmout, %lu max, %lu now\n", 1558},
  {"   %f int/sec; %f rec (char/sec)\n", 1559},
  {"Usage: %s [-c] [-n level] [-s bufsize]\n", 1560},
  {"invalid id: %s\n", 1561},
  {"cannot remove id %s (%s)\n", 1562},
  {"usage: %s {shm | msg | sem} id ...\n", 1563},
  {"unknown resource type: %s\n", 1564},
  {"resource(s) deleted\n", 1565},
  {"usage : %s -asmq -tclup \n", 1566},
  {"\t%s [-s -m -q] -i id\n", 1567},
  {"\t%s -h for help.\n", 1568},
  {"%s provides information on ipc facilities for", 1569},
  {" which you have read access.\n", 1570},
  {"\
Resource Specification:\n\
\t-m : shared_mem\n\
\t-q : messages\n", 1571},
  {"\
\t-s : semaphores\n\
\t-a : all (default)\n", 1572},
  {"\
Output Format:\n\
\t-t : time\n\
\t-p : pid\n\
\t-c : creator\n", 1573},
  {"\
\t-l : limits\n\
\t-u : summary\n", 1574},
  {"-i id [-s -q -m] : details on resource identified by id\n", 1575},
  {"kernel not configured for shared memory\n", 1576},
  {"------ Shared Memory Limits --------\n", 1577},
  {"max number of segments = %ld\n", 1578},
  {"max seg size (kbytes) = %ld\n", 1579},
  {"max total shared memory (kbytes) = %ld\n", 1580},
  {"min seg size (bytes) = %ld\n", 1581},
  {"------ Shared Memory Status --------\n", 1582},
  {"segments allocated %d\n", 1583},
  {"pages allocated %ld\n", 1584},
  {"pages resident  %ld\n", 1585},
  {"pages swapped   %ld\n", 1586},
  {"Swap performance: %ld attempts\t %ld successes\n", 1587},
  {"------ Shared Memory Segment Creators/Owners --------\n", 1588},
  {"%-10s%-10s%-10s%-10s%-10s%-10s\n", 1589},
  {"shmid", 1590},
  {"perms", 1591},
  {"cuid", 1592},
  {"cgid", 1593},
  {"uid", 1594},
  {"gid", 1595},
  {"------ Shared Memory Attach/Detach/Change Times --------\n", 1596},
  {"%-10s%-10s  %-20s%-20s%-20s\n", 1597},
  {"owner", 1598},
  {"attached", 1599},
  {"detached", 1600},
  {"changed", 1601},
  {"------ Shared Memory Creator/Last-op --------\n", 1602},
  {"%-10s%-10s%-10s%-10s\n", 1603},
  {"cpid", 1604},
  {"lpid", 1605},
  {"------ Shared Memory Segments --------\n", 1606},
  {"%-10s%-10s%-10s%-10s%-10s%-10s%-12s\n", 1607},
  {"key", 1608},
  {"bytes", 1609},
  {"nattch", 1610},
  {"status", 1611},
  {"Not set", 1612},
  {"dest", 1613},
  {"locked", 1614},
  {"kernel not configured for semaphores\n", 1615},
  {"------ Semaphore Limits --------\n", 1616},
  {"max number of arrays = %d\n", 1617},
  {"max semaphores per array = %d\n", 1618},
  {"max semaphores system wide = %d\n", 1619},
  {"max ops per semop call = %d\n", 1620},
  {"semaphore max value = %d\n", 1621},
  {"------ Semaphore Status --------\n", 1622},
  {"used arrays = %d\n", 1623},
  {"allocated semaphores = %d\n", 1624},
  {"------ Semaphore Arrays Creators/Owners --------\n", 1625},
  {"semid", 1626},
  {"------ Shared Memory Operation/Change Times --------\n", 1627},
  {"%-8s%-10s  %-26.24s %-26.24s\n", 1628},
  {"last-op", 1629},
  {"last-changed", 1630},
  {"------ Semaphore Arrays --------\n", 1631},
  {"%-10s%-10s%-10s%-10s%-10s%-12s\n", 1632},
  {"nsems", 1633},
  {"------ Messages: Limits --------\n", 1634},
  {"max queues system wide = %d\n", 1635},
  {"max size of message (bytes) = %d\n", 1636},
  {"default max size of queue (bytes) = %d\n", 1637},
  {"------ Messages: Status --------\n", 1638},
  {"allocated queues = %d\n", 1639},
  {"used headers = %d\n", 1640},
  {"used space = %d bytes\n", 1641},
  {"------ Message Queues: Creators/Owners --------\n", 1642},
  {"msqid", 1643},
  {"------ Message Queues Send/Recv/Change Times --------\n", 1644},
  {"%-8s%-10s  %-20s%-20s%-20s\n", 1645},
  {"send", 1646},
  {"recv", 1647},
  {"change", 1648},
  {"------ Message Queues PIDs --------\n", 1649},
  {"lspid", 1650},
  {"lrpid", 1651},
  {"------ Message Queues --------\n", 1652},
  {"%-10s%-10s%-10s%-10s%-12s%-12s\n", 1653},
  {"used-bytes", 1654},
  {"messages", 1655},
  {"\
\n\
Shared memory Segment shmid=%d\n", 1656},
  {"uid=%d\tgid=%d\tcuid=%d\tcgid=%d\n", 1657},
  {"mode=%#o\taccess_perms=%#o\n", 1658},
  {"bytes=%d\tlpid=%d\tcpid=%d\tnattch=%ld\n", 1659},
  {"att_time=%s", 1660},
  {"Not set\n", 1661},
  {"det_time=%s", 1662},
  {"change_time=%s", 1663},
  {"\
\n\
Message Queue msqid=%d\n", 1664},
  {"uid=%d\tgid=%d\tcuid=%d\tcgid=%d\tmode=%#o\n", 1665},
  {"cbytes=%ld\tqbytes=%ld\tqnum=%ld\tlspid=%d\tlrpid=%d\n", 1666},
  {"send_time=%srcv_time=%schange_time=%s", 1667},
  {"Not Set\n", 1668},
  {"\
\n\
Semaphore Array semid=%d\n", 1669},
  {"uid=%d\t gid=%d\t cuid=%d\t cgid=%d\n", 1670},
  {"mode=%#o, access_perms=%#o\n", 1671},
  {"nsems = %ld\n", 1672},
  {"otime = %s", 1673},
  {"ctime = %s", 1674},
  {"%-10s%-10s%-10s%-10s%-10s\n", 1675},
  {"semnum", 1676},
  {"value", 1677},
  {"ncount", 1678},
  {"zcount", 1679},
  {"pid", 1680},
  {"usage: rdev [ -rsv ] [ -o OFFSET ] [ IMAGE [ VALUE [ OFFSET ] ] ]", 1681},
  {"\
  rdev /dev/fd0  (or rdev /linux, etc.) displays the current ROOT device", 1682},
  {"  rdev /dev/fd0 /dev/hda2         sets ROOT to /dev/hda2", 1683},
  {"  rdev -R /dev/fd0 1              set the ROOTFLAGS (readonly status)", 1684},
  {"  rdev -s /dev/fd0 /dev/hda2      set the SWAP device", 1685},
  {"  rdev -r /dev/fd0 627            set the RAMDISK size", 1686},
  {"  rdev -v /dev/fd0 1              set the bootup VIDEOMODE", 1687},
  {"  rdev -o N ...                   use the byte offset N", 1688},
  {"  rootflags ...                   same as rdev -R", 1689},
  {"  swapdev ...                     same as rdev -s", 1690},
  {"  ramsize ...                     same as rdev -r", 1691},
  {"  vidmode ...                     same as rdev -v", 1692},
  {"\
Note: video modes are: -3=Ask, -2=Extended, -1=NormalVga, 1=key1, 2=key2,...", 1693},
  {"      use -R 1 to mount root readonly, -R 0 for read/write.", 1694},
  {"\
%s: Usage: \"%s [options]\n\
\t -m <mapfile>  (default = \"%s\")\n\
\t -p <pro-file> (default = \"%s\")\n\
\t -i            print only info about the sampling step\n\
\t -v            print verbose data\n\
\t -a            print all symbols, even if count is 0\n\
\t -r            reset all the counters (root only)\n\
\t -V            print version and exit\n", 1695},
  {"%s Version %s\n", 1696},
  {"anything\n", 1697},
  {"Sampling_step: %i\n", 1698},
  {"%s: %s(%i): wrong map line\n", 1699},
  {"%s: can't find \"_stext\" in %s\n", 1700},
  {"total", 1701},
  {"\
usage: renice priority [ [ -p ] pids ] [ [ -g ] pgrps ] [ [ -u ] users ]\n", 1702},
  {"renice: %s: unknown user\n", 1703},
  {"renice: %s: bad value\n", 1704},
  {"getpriority", 1705},
  {"setpriority", 1706},
  {"%d: old priority %d, new priority %d\n", 1707},
  {"usage: %s program [arg ...]\n", 1708},
  {"\
Usage: %s <device> [ -i <IRQ> | -t <TIME> | -c <CHARS> | -w <WAIT> | \n\
          -a [on|off] | -o [on|off] | -C [on|off] | -q [on|off] | -s | \n\
          -T [on|off] ]\n", 1709},
  {"malloc error", 1710},
  {"%s: bad value\n", 1711},
  {"%s: %s not an lp device.\n", 1712},
  {"%s status is %d", 1713},
  {", busy", 1714},
  {", ready", 1715},
  {", out of paper", 1716},
  {", on-line", 1717},
  {", error", 1718},
  {"LPGETIRQ error", 1719},
  {"%s using IRQ %d\n", 1720},
  {"%s using polling\n", 1721},
  {"col: bad -l argument %s.\n", 1722},
  {"usage: col [-bfpx] [-l nline]\n", 1723},
  {"col: write error.\n", 1724},
  {"col: warning: can't back up %s.\n", 1725},
  {"past first line", 1726},
  {"-- line already flushed", 1727},
  {"usage: %s [ - ] [ -2 ] [ file ... ]\n", 1728},
  {"line too long", 1729},
  {"usage: column [-tx] [-c columns] [file ...]\n", 1730},
  {"hexdump: bad length value.\n", 1731},
  {"hexdump: bad skip value.\n", 1732},
  {"\
hexdump: [-bcdovx] [-e fmt] [-f fmt_file] [-n length] [-s skip] [file ...]\n", 1733},
  {"usage: %s [-dflpcsu] [+linenum | +/pattern] name1 name2 ...\n", 1734},
  {"\
\n\
*** %s: directory ***\n\
\n", 1735},
  {"\
\n\
******** %s: Not a text file ********\n\
\n", 1736},
  {"[Use q or Q to quit]", 1737},
  {"--More--", 1738},
  {"(Next file: %s)", 1739},
  {"[Press space to continue, 'q' to quit.]", 1740},
  {"...back %d page", 1741},
  {"...skipping %d line", 1742},
  {"\
\n\
***Back***\n\
\n", 1743},
  {"Can't open help file", 1744},
  {"[Press 'h' for instructions.]", 1745},
  {"\"%s\" line %d", 1746},
  {"[Not a file] line %d", 1747},
  {"  Overflow\n", 1748},
  {"...skipping\n", 1749},
  {"Regular expression botch", 1750},
  {"\
\n\
Pattern not found\n", 1751},
  {"Pattern not found", 1752},
  {"can't fork\n", 1753},
  {"\
\n\
...Skipping ", 1754},
  {"...Skipping ", 1755},
  {"to file ", 1756},
  {"back to file ", 1757},
  {"Line too long", 1758},
  {"No previous command to substitute for", 1759},
  {"od: od(1) has been deprecated for hexdump(1).\n", 1760},
  {"od: hexdump(1) compatibility doesn't support the -%c option%s\n", 1761},
  {"; see strings(1).", 1762},
  {"hexdump: can't read %s.\n", 1763},
  {"hexdump: line too long.\n", 1764},
  {"hexdump: byte count with multiple conversion characters.\n", 1765},
  {"hexdump: bad byte count for conversion character %s.\n", 1766},
  {"hexdump: %%s requires a precision or a byte count.\n", 1767},
  {"hexdump: bad format {%s}\n", 1768},
  {"hexdump: bad conversion character %%%s.\n", 1769},
  {"Unable to allocate bufferspace\n", 1770},
  {"usage: rev [file ...]\n", 1771},
  {"usage: %s [ -i ] [ -tTerm ] file...\n", 1772},
  {"trouble reading terminfo", 1773},
  {"Unknown escape sequence in input: %o, %o\n", 1774},
  {"Unable to allocate buffer.\n", 1775},
  {"Input line too long.\n", 1776},
  {"Out of memory when growing buffer.\n", 1777},
  {"Typematic Rate set to %.1f cps (delay = %d ms)\n", 1778},
  {"Usage: kbdrate [-V] [-s] [-r rate] [-d delay]\n", 1779},
  {"Cannot open /dev/port", 1780},
};

int _msg_tbl_length = 1780;
