#!/bin/sh
#
# Copyright (C) 2009 Karel Zak <kzak@redhat.com>
#

# find all *.c files, 
# sort the list
# exclude ../tests/ from the list 
#         and remove "../" prefix

find ../ -name "*.c" | \
sort | \
gawk '! /^\.\.\/tests\// { print gensub(/^\.\.\//, "", 1) }' > POTFILES.in
