#!/bin/sh
#
# Copyright (C) 2009 Karel Zak <kzak@redhat.com>
#

# find all *.c files, 
# sort the list
# exclude ./tests/ from the list 
#         and remove "./" prefix

[ ! -f "po/Makevars" ] && \
	echo "You must run this script in the top-level directory"

find -name "*.c" | \
  sort | \
  gawk '! /^\.\/tests\// { print gensub(/^\.\//, "", 1) }' \
  > po/POTFILES.in
