#!/bin/bash
#
# Copyright (C) 2026 WanBingjiang <wanbingjiang@webray.com.cn>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="send-recv"

. "$TS_TOPDIR/functions.sh"
ts_init "$*"

ts_check_test_command "$TS_CMD_FDSEND"
ts_check_test_command "$TS_CMD_FDRECV"

TESTFILE="$TS_OUTDIR/fdsend_test_data"
SOCKPATH="$(cd "$TS_OUTDIR" 2>/dev/null && pwd)/fdsend_test.sock"
mkdir -p "$TS_OUTDIR"
echo "hello" > "$TESTFILE"

{
	# Start fdrecv in background: receive fd, dup to stdin, run cat
	# Options (e.g. --stdin) must come before SOCKSPEC
	$TS_CMD_FDRECV --stdin "$SOCKPATH" --run cat &
	FDRECV_PID=$!
	# Wait for socket to be created
	sleep 1
	# Send fd 3 (testfile) to fdrecv; -b blocks until socket appears
	exec 3<"$TESTFILE"
	$TS_CMD_FDSEND -f 3 -b "$SOCKPATH"
	exec 3<&-
	wait $FDRECV_PID
} > "$TS_OUTPUT" 2>&1

ts_finalize
