#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="format-file read error"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_HEXDUMP"

format_file="$TS_OUTDIR/format-file-read-error.dir"
actual="$TS_OUTDIR/format-file-read-error.actual"
mkdir -p "$format_file"

printf '\1' | "$TS_CMD_HEXDUMP" -f "$format_file" > "$actual" 2> /dev/null
rc=$?

ts_init_subtest "exit-status"
[ "$rc" -ne 0 ] || ts_failed "hexdump exited successfully after a format-file read error"
ts_finalize_subtest

ts_init_subtest "no-default-output"
[ ! -s "$actual" ] || ts_failed "hexdump produced default output after a format-file read error"
ts_finalize_subtest

ts_finalize
