#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="write-error"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_HEXDUMP"

[ -c /dev/full ] || ts_skip "/dev/full not found"

$TS_CMD_HEXDUMP -C --no-squeezing -n 1048576 /dev/zero > /dev/full 2> "$TS_ERRLOG"
rc=$?
printf "exit code: %d\n" "$rc" >> "$TS_OUTPUT"

ts_finalize
