#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2026 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="choom"

. "$TS_TOPDIR/functions.sh"
ts_init "$*"


ts_check_test_command "$TS_CMD_CHOOM"

PID=$$
oom_score_adj=$("$TS_CMD_CHOOM" --pid $PID \
                        | awk -F: '/score adjust value/ {print $2}' \
                        | tr -d ' ')

(( oom_score_adj++ ))

"$TS_CMD_CHOOM" --pid $PID --adjust $oom_score_adj &>/dev/null

if [[ "$?" != 0 ]]; then
        ts_failed "OOM adjust score change failed"
fi

new_oom_score_adj=$("$TS_CMD_CHOOM" --pid $PID \
                        | awk -F: '/score adjust value/ {print $2}' \
                        | tr -d ' ')

if (( "$new_oom_score_adj" == "$oom_score_adj" )); then
        echo "ok" >> "$TS_OUTPUT"
fi

ts_finalize