#!/bin/bash

#
# Copyright (C) 2007 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux-ng.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
. ./commands.sh
. ./functions.sh

TS_COMPONENT="fstab"
TS_DESC="symlink"

ts_init "$*"
ts_skip_nonroot

set -o pipefail

LINKNAME="$(pwd)/$TS_OUTDIR/${TS_NAME}_lnk"

DEVICE=$(ts_device_init)
[ "$?" == 0 ] || ts_die "Cannot init device"

mkfs.ext3 $DEVICE &> /dev/null || ts_die "Cannot make ext3 on $DEVICE" $DEVICE

ts_device_has "TYPE" "ext3" $DEVICE || ts_die "Cannot found ext3 on $DEVICE" $DEVICE

[ -d "$TS_MOUNTPOINT" ] || mkdir -p $TS_MOUNTPOINT

ln -s $DEVICE $LINKNAME

ts_fstab_add $LINKNAME $TS_MOUNTPOINT "auto" "defaults,user"

# variant A) -- UID=0
$TS_CMD_MOUNT $LINKNAME 2>&1 >> $TS_OUTPUT
ts_is_mounted $DEVICE || ts_die "A) Cannot found $DEVICE in /proc/mounts" $DEVICE
$TS_CMD_UMOUNT $LINKNAME || ts_die "A) Cannot umount $LINKNAME" $DEVICE

# varian B)
ts_init_suid $TS_CMD_MOUNT
ts_init_suid $TS_CMD_UMOUNT

su $TS_TESTUSER -c "$TS_CMD_MOUNT $LINKNAME" 2>&1 >> $TS_OUTPUT
ts_is_mounted $DEVICE || ts_die "B) Cannot found $DEVICE in /proc/mounts" $DEVICE
su $TS_TESTUSER -c "$TS_CMD_UMOUNT $LINKNAME" 2>&1 >> $TS_OUTPUT \
 || ts_die "B) Cannot umount $LINKNAME" $DEVICE

ts_device_deinit $DEVICE
ts_fstab_clean
rm -f $LINKNAME

ts_log "Success"
ts_finalize

