#!/bin/bash

# Copyright (C) 2011 Karel Zak <kzak@redhat.com>
# This file is part of util-linux.

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="regular file"

. $TS_TOPDIR/functions.sh
ts_init "$*"
ts_skip_nonroot

set -o pipefail

IMAGE=$(ts_image_init)
mkfs.ext3 -F $IMAGE &> /dev/null || ts_die "Cannot make ext3 on $IMAGE"

[ -d "$TS_MOUNTPOINT" ] || mkdir -p $TS_MOUNTPOINT

$TS_CMD_MOUNT $IMAGE $TS_MOUNTPOINT 2>&1 >> $TS_OUTPUT

grep -q "$TS_MOUNTPOINT" /proc/mounts || ts_die "Cannot found $TS_MOUNTPOINT in /proc/mounts"

$TS_CMD_UMOUNT $IMAGE || ts_die "Cannot umount $IMAGE"

grep -q "$TS_MOUNTPOINT" /proc/mounts && ts_die "$TS_MOUNTPOINT still in /proc/mounts"

ts_log "Success"
ts_finalize

