#!/bin/bash

#
# Copyright (C) 2022 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
TS_TOPDIR="${0%/*}/../.."
TS_DESC="X-mount.subdir"

. $TS_TOPDIR/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MOUNT"
ts_check_test_command "$TS_CMD_FINDMNT"
ts_skip_nonroot
ts_check_losetup

# unshared session is possible to support only on kernels with new mount API
if [ "$("$TS_HELPER_SYSINFO" fsopen-ok)" = "0" ]; then
	prop=$($TS_CMD_FINDMNT --task "$$" -n -o PROPAGATION "/")
	[[ "$prop" == *"private"* ]] && ts_skip "unsupported session"
fi

ts_device_init
DEVICE=$TS_LODEV

mkfs.ext2 $DEVICE &> /dev/null || ts_die "Cannot make ext2 on $DEVICE"
ts_udevadm_settle "$DEVICE"

# use the same mountpoiunt for all subtests
MOUNTPOINT="$TS_MOUNTPOINT"
[ -d "$MOUNTPOINT" ] || mkdir -p $MOUNTPOINT


# create subdirectory on the filesystem
ts_init_subtest "init"
$TS_CMD_MOUNT $DEVICE $MOUNTPOINT >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_is_mounted $DEVICE || ts_log "Cannot find $DEVICE in /proc/mounts"
mkdir -p $MOUNTPOINT/submnt
touch $MOUNTPOINT/submnt/file
$TS_CMD_UMOUNT $MOUNTPOINT >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest


ts_init_subtest "subdir"
$TS_CMD_MOUNT -o X-mount.subdir=submnt $DEVICE $MOUNTPOINT >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_is_mounted $DEVICE || ts_log "Cannot find $DEVICE in /proc/mounts"
if [ ! -f "$MOUNTPOINT/file" ]; then
	echo "$MOUNTPOINT/file not found" >> $TS_OUTPUT 
fi
$TS_CMD_UMOUNT $MOUNTPOINT >> $TS_OUTPUT 2>> $TS_ERRLOG
ts_finalize_subtest


ts_finalize
