#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="options"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MCOOKIE"

ts_init_subtest "file"
$TS_CMD_MCOOKIE --file /etc/services |\
	# The sed will convert only 32 characters long hexadecimal string
	# to expected string, but nothing else.
	sed 's/^[0-9a-f]\{32\}$/the string meets expecations/' >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"
ts_finalize_subtest

ts_init_subtest "max-size"
$TS_CMD_MCOOKIE --file /etc/services --max-size 4 --verbose 2>&1 \
                        | grep -Eo '^Got 4 bytes.*' >> "$TS_OUTPUT"
ts_finalize_subtest

ts_finalize
