#!/bin/bash

# Derrived from all_syscalls.

set -e
set -o pipefail

AWK="$1"
shift
OUTPUT=errnos.h
ERRNO_INCLUDES="
#include <sys/errno.h>
"

trap 'rm -f $OUTPUT $OUTPUT.deps' ERR

"$@" -MD -MF "$OUTPUT.deps" <<< "$ERRNO_INCLUDES" -dM -E - \
	| "$AWK" 'match($0, /^#[ \t]*define[ \t]*E([^ ]+)/, res) { print "UL_ERRNO(\"E" res[1] "\", E" res[1] ")" }' \
	| sort \
	> "$OUTPUT"
