#!/bin/bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="the columns enabled with -D and -I options"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_FINDMNT"
ts_check_prog "head"

ts_cd "$TS_OUTDIR"

D_expectation="SOURCE FSTYPE SIZE USED AVAIL USE% TARGET"
I_expectation="SOURCE FSTYPE INO.TOTAL INO.USED INO.AVAIL INO.USE% TARGET"
{
	if [[ $($TS_CMD_FINDMNT --raw -D | head -1) == "$D_expectation" ]]; then
	    echo "-D: OK"
	else
	    echo "-D: ERROR"
	    $TS_CMD_FINDMNT --raw -D
	    echo $?
	fi

	if [[ $($TS_CMD_FINDMNT --raw -I | head -1) == "$I_expectation" ]]; then
	    echo "-I: OK"
	else
	    echo "-I: ERROR"
	    $TS_CMD_FINDMNT --raw -I
	    echo $?
	fi

	if [[ $($TS_CMD_FINDMNT --raw --df | head -1) == "$D_expectation" ]]; then
	    echo "--df: OK"
	else
	    echo "--df: ERROR"
	    $TS_CMD_FINDMNT --raw --df
	    echo $?
	fi

	if [[ $($TS_CMD_FINDMNT --raw --dfi | head -1) == "$I_expectation" ]]; then
	    echo "--dfi: OK"
	else
	    echo "--dfi: ERROR"
	    $TS_CMD_FINDMNT --raw --dfi
	    echo $?
	fi
} >> "$TS_OUTPUT" 2>> "$TS_ERRLOG"

ts_finalize
