#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2026 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="uniq-id"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_skip_nonroot

ts_check_test_command "$TS_CMD_FINDMNT"
ts_check_test_command "$TS_CMD_MOUNT"
ts_check_test_command "$TS_CMD_UMOUNT"
ts_check_prog "mkfs.ext2"
ts_check_losetup

[ -d "$TS_MOUNTPOINT" ] || mkdir -p "$TS_MOUNTPOINT"

[ "$("$TS_HELPER_SYSINFO" statmount-ok)" = "1" ] || ts_skip "no statmount"
[ "$("$TS_HELPER_SYSINFO" listmount-ok)" = "1" ] || ts_skip "no listmount"

ts_device_init 10
dev="$TS_LODEV"

mkfs.ext2 -U "76c21844-40cb-46c5-8a3c-0e5e3163d7f4" "$dev" &>/dev/null \
    || ts_die "Cannot make ext2 on $dev"

$TS_CMD_MOUNT "$dev" "$TS_MOUNTPOINT" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
udevadm settle
if ! ts_is_mounted "$dev"; then
    $TS_CMD_UMOUNT --detach-loop --force "$dev" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
    udevadm settle
    ts_die "$dev cannot be found in /proc/mounts"
fi

uniq_id=$($TS_CMD_FINDMNT --noheadings --kernel=listmount --output UNIQ-ID "$dev" 2>>"$TS_ERRLOG")
$TS_CMD_FINDMNT --noheadings --kernel=listmount --uniq-id "$uniq_id" \
    --output SOURCE --raw >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"

sed -i "s@$dev@<source>@" "$TS_OUTPUT" 2>>"$TS_ERRLOG"

$TS_CMD_UMOUNT --detach-loop --force "$dev" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
udevadm settle

ts_finalize
