#!/bin/bash

#
# Copyright (C) 2019 Radka Skvarilova <rskvaril@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="${0%/*}/../.."
TS_DESC="gecos"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

export LIBUSER_CONF=/dev/null

ts_skip_nonroot
ts_check_test_command "$TS_CMD_CHFN"
ts_check_prog "useradd"
ts_check_prog "userdel"

ts_log "Initialize user"
useradd -u 9899 --shell /bin/bash testuser_chfn_test
grep testuser /etc/passwd >> $TS_OUTPUT
$TS_CMD_CHFN -f test_gecos testuser_chfn_test >>$TS_OUTPUT
grep testuser /etc/passwd >> $TS_OUTPUT
userdel --remove testuser_chfn_test &> /dev/null
ts_finalize
