---
# vi: ts=2 sw=2 et:
# See: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

name: CIFuzz
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**'
jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   if: github.repository == 'karelzak/util-linux'
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, undefined]
   steps:
   - name: Build Fuzzers (${{ matrix.sanitizer }})
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
     with:
       oss-fuzz-project-name: 'util-linux'
       dry-run: false
       allowed-broken-targets-percentage: 0
       sanitizer: ${{ matrix.sanitizer }}
   - name: Run Fuzzers (${{ matrix.sanitizer }})
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
     with:
       oss-fuzz-project-name: 'util-linux'
       fuzz-seconds: 180
       dry-run: false
       sanitizer: ${{ matrix.sanitizer }}
   - name: Upload Crash
     uses: actions/upload-artifact@v1
     if: failure() && steps.build.outcome == 'success'
     with:
       name: ${{ matrix.sanitizer }}-artifacts
       path: ./out/artifacts
